#!/usr/bin/env python3
"""FS3 v131 - M31 turns in place, and a fullscreen button on the title.

M31 Der Aufstand
  The NTF Leviathan did not appear where the GTVA one had been. The rebuilt
  ship went through assignStation(), which picks a free lane for a ship
  that is arriving - and moved her to another height. A ship that changes
  sides is not arriving: she keeps her place, so that call is gone.

Title screen
  A FULLSCREEN button in the top right corner. Until now full screen was
  only reachable from the settings panel, which only opens during a run.
  It reads EXIT FULLSCREEN while the game is in full screen, and it only
  shows where the browser offers full screen at all. The F key now works
  on the title and the end screen as well.

Needs v130 applied first. Edits src/30_waves.js and src/70_ui.js in place,
and writes the updated shipsim.js and fieldsim.js. Run assemble.py afterwards.
"""
import sys


def replace_once(text, old, new, label):
    n = text.count(old)
    if n != 1:
        sys.exit("Abbruch (%s): Suchtext %d-mal gefunden, erwartet einmal." % (label, n))
    return text.replace(old, new)


def load(p):
    return open(p, encoding="utf-8").read()


wv = load("src/30_waves.js")
ui = load("src/70_ui.js")

# ══ 30_waves.js ═════════════════════════════════════════════════════════
wv = replace_once(
    wv,
    "  initWeapons(e); initSecAmmo(e); initLuciShield(e); initSubsystems(e); assignStation(e);\n",
    "  // No assignStation(): that picks a free lane for a ship that arrives,\n"
    "  // and a ship that changes sides keeps the place she is in.\n"
    "  initWeapons(e); initSecAmmo(e); initLuciShield(e); initSubsystems(e);\n",
    "defectCap: keep place")

# ══ 70_ui.js ════════════════════════════════════════════════════════════

# ── The button ─────────────────────────────────────────────────────────
ui = replace_once(
    ui,
    "function drawTitle(){\n",
    "// Full screen from the title. The settings panel has the same switch, but\n"
    "// it only opens during a run, and on a PC the full screen is wanted\n"
    "// before the first wave, not after it. Built from the kit like the\n"
    "// buttons in the bar: lit while pointed at, nothing otherwise.\n"
    "const TFS_W = 136, TFS_H = 26, TFS_PAD = 14;\n"
    "function titleFsRect(){\n"
    "  if(!fullscreenAvailable()) return null;\n"
    "  return {x:W-TFS_W-TFS_PAD, y:TFS_PAD, w:TFS_W, h:TFS_H};\n"
    "}\n"
    "function drawTitleFullscreen(){\n"
    "  const r = titleFsRect();\n"
    "  window._titleFsRect = r;\n"
    "  if(!r) return;\n"
    "  const hv = hovering(r.x, r.y, r.w, r.h);\n"
    "  thButton(r.x, r.y, r.w, r.h, hv ? 'on' : null);\n"
    "  ctx.textAlign='center'; ctx.textBaseline='middle';\n"
    "  ctx.fillStyle = hv ? TH('textBright') : TH('text');\n"
    "  ctx.font = thLabel(11);\n"
    "  ctx.fillText(thFit(isFullscreen() ? 'EXIT FULLSCREEN' : 'FULLSCREEN', r.w-16),\n"
    "               r.x+r.w/2, r.y+r.h/2+1);\n"
    "}\n"
    "// A click on the button switches full screen and does nothing else - it\n"
    "// must not also start the run the rest of the title starts.\n"
    "function titleFsHit(p){\n"
    "  if(GS!=='title') return false;\n"
    "  const r = window._titleFsRect;\n"
    "  return !!r && p.x>=r.x && p.x<=r.x+r.w && p.y>=r.y && p.y<=r.y+r.h;\n"
    "}\n"
    "function drawTitle(){\n",
    "title fullscreen: button")

ui = replace_once(
    ui,
    "  ctx.fillText('PRESS SPACE OR ENTER', W/2, H-52);\n"
    "  ctx.restore();\n"
    "\n"
    "  ctx.textAlign='left'; ctx.textBaseline='top';\n"
    "}\n",
    "  ctx.fillText('PRESS SPACE OR ENTER', W/2, H-52);\n"
    "  ctx.restore();\n"
    "\n"
    "  drawTitleFullscreen();\n"
    "  ctx.textAlign='left'; ctx.textBaseline='top';\n"
    "}\n",
    "title fullscreen: draw")

# ── Mouse and touch: the button before the launch ───────────────────────
ui = replace_once(
    ui,
    "CVS.addEventListener('mousedown',function(ev){\n",
    "CVS.addEventListener('mousedown',function(ev){\n"
    "  if(ev.button===0 && titleFsHit(toGC(ev.clientX,ev.clientY))){ toggleFullscreen(); return; }\n",
    "title fullscreen: mouse")

ui = replace_once(
    ui,
    "  var t=ev.touches[0];\n"
    "  var p=toGC(t.clientX,t.clientY);\n"
    "  if(pointerConsumed(p)) return;\n",
    "  var t=ev.touches[0];\n"
    "  var p=toGC(t.clientX,t.clientY);\n"
    "  if(titleFsHit(p)){ toggleFullscreen(); return; }\n"
    "  if(pointerConsumed(p)) return;\n",
    "title fullscreen: touch")

# ── F on the title and the end screen too ──────────────────────────────
ui = replace_once(
    ui,
    "  if(ev.code==='KeyF' && GS==='playing'){\n",
    "  if(ev.code==='KeyF' && (GS==='playing'||GS==='title'||GS==='gameover')){\n",
    "F key")

open("src/30_waves.js", "w", encoding="utf-8").write(wv)
open("src/70_ui.js", "w", encoding="utf-8").write(ui)

# ── Test files ─────────────────────────────────────────────────────────
# The updated checks travel inside the patch, because .js files cannot be
# downloaded from the chat. Written last.
import base64
TEST_FILES = {
    'shipsim.js': (
        'Ly8gU2hpcCBzd2l0Y2ggc2ltdWxhdGlvbi4gUHVsbHMgdGhlIFJFQUwgZnVuY3Rpb25zIG91dCBv'
        'ZiB0aGUgbG9naWMgZmlsZSBhbmQKLy8gcnVucyB0aGVtIGFnYWluc3Qgc3RhbmQtaW5zIGZvciB0'
        'aGUgd29ybGQuIFVzYWdlOiBub2RlIHNoaXBzaW0uanMgPGxvZ2ljLmh0bWw+CmNvbnN0IGZzID0g'
        'cmVxdWlyZSgnZnMnKTsKY29uc3QgaHRtbCA9IGZzLnJlYWRGaWxlU3luYyhwcm9jZXNzLmFyZ3Zb'
        'Ml0sICd1dGY4Jyk7CmNvbnN0IHNyYyA9IGh0bWwubWF0Y2goLzxzY3JpcHRbXj5dKj4oW1xzXFNd'
        'Kik8XC9zY3JpcHQ+LylbMV07CgpmdW5jdGlvbiBibG9ja0VuZChzLCBpKXsKICBpID0gcy5pbmRl'
        'eE9mKCd7JywgaSk7IGxldCBkID0gMDsKICBmb3IoOyBpIDwgcy5sZW5ndGg7IGkrKyl7CiAgICBj'
        'b25zdCBjID0gc1tpXTsKICAgIGlmKGM9PT0iJyJ8fGM9PT0nIid8fGM9PT0nYCcpeyBjb25zdCBx'
        'PWM7IGkrKzsgd2hpbGUoaTxzLmxlbmd0aCAmJiBzW2ldIT09cSl7IGlmKHNbaV09PT0nXFwnKSBp'
        'Kys7IGkrKzsgfSB9CiAgICBlbHNlIGlmKHMuc3RhcnRzV2l0aCgnLy8nLCBpKSkgaSA9IHMuaW5k'
        'ZXhPZignXG4nLCBpKTsKICAgIGVsc2UgaWYocy5zdGFydHNXaXRoKCcvKicsIGkpKSBpID0gcy5p'
        'bmRleE9mKCcqLycsIGkpICsgMTsKICAgIGVsc2UgaWYoYz09PSd7JykgZCsrOwogICAgZWxzZSBp'
        'ZihjPT09J30nKXsgZC0tOyBpZihkPT09MCkgcmV0dXJuIGkrMTsgfQogIH0KICB0aHJvdyBuZXcg'
        'RXJyb3IoJ25vIGJsb2NrIGVuZCcpOwp9CmZ1bmN0aW9uIGZuKG5hbWUpewogIGNvbnN0IGkgPSBz'
        'cmMuaW5kZXhPZignXG5mdW5jdGlvbiAnK25hbWUrJygnKTsKICBpZihpPDApIHRocm93IG5ldyBF'
        'cnJvcignbWlzc2luZyBmdW5jdGlvbiAnK25hbWUpOwogIHJldHVybiBzcmMuc2xpY2UoaSsxLCBi'
        'bG9ja0VuZChzcmMsIGkpKTsKfQpmdW5jdGlvbiBiZXR3ZWVuKHN0YXJ0VGV4dCl7CiAgY29uc3Qg'
        'aSA9IHNyYy5pbmRleE9mKHN0YXJ0VGV4dCk7IGlmKGk8MCkgdGhyb3cgbmV3IEVycm9yKCdtaXNz'
        'aW5nICcrc3RhcnRUZXh0KTsKICBjb25zdCBqID0gc3JjLmluZGV4T2YoJ2Z1bmN0aW9uJywgaSk7'
        'CiAgcmV0dXJuIHNyYy5zbGljZShqLCBibG9ja0VuZChzcmMsIGopKTsKfQpjb25zdCBzaGlwc0Rl'
        'Y2wgPSBzcmMubWF0Y2goL2NvbnN0IFBMQVlFUl9TSElQUyA9IFxbW1xzXFNdKj9cXTsvKVswXTsK'
        'Ly8gVGhlIGN5Y2xlIHRhYmxlcyBhbmQgdGhlIHN1cHBvcnQgY29sdW1ucyB0aGV5IHN3aXRjaC4K'
        'Y29uc3QgY3ljbGVEZWNsID0gc3JjLm1hdGNoKC9jb25zdCBST1NURVJfSE9MW1xzXFNdKj9cbmxl'
        'dCBjeWNsZUJhc2UgPSAwO1teXG5dKi8pWzBdOwpjb25zdCBmYWNPbkRlY2wgPSBzcmMubWF0Y2go'
        'L2NvbnN0IEFMTFlfRkFDX09OID0gXHtbXn1dKlx9Oy8pWzBdOwpjb25zdCBodWxsRmFjRGVjbCA9'
        'IHNyYy5tYXRjaCgvY29uc3QgSFVMTF9GQUMgPSBce1tcc1xTXSo/XH07LylbMF07CmNvbnN0IG1l'
        'bnVCZ0RlY2wgPSBzcmMubWF0Y2goL2NvbnN0IE1FTlVfQkdfQUxQSEFbXHNcU10qP2NvbnN0IE1F'
        'TlVfQkdfUEFEXHMqPVxzKltcZC5dKzsvKVswXTsKY29uc3QgaGFuZ2FyRGVjbCA9IHNyYy5tYXRj'
        'aCgvY29uc3QgSEdfV1tcc1xTXSo/XG5cXTsvKVswXTsKY29uc3QgdGhlbWVzRGVjbCA9IHNyYy5t'
        'YXRjaCgvY29uc3QgVEhFTUVTID0gXHtbXHNcU10qP1xuXH07LylbMF07Ci8vIFRoZSB3ZWFwb24g'
        'dGFibGVzIGFuZCB0aGUgcmVhcm0gcGFuZWwncyBtZWFzdXJlbWVudHMuCmNvbnN0IHdwbkRlY2wg'
        'ID0gc3JjLm1hdGNoKC9jb25zdCBQTEFZRVJfRlJfQkFTRVtcc1xTXSo/XG5cXTsvKVswXTsKY29u'
        'c3Qgd3BuRGVjbDIgPSBzcmMubWF0Y2goL2NvbnN0IFNFQ09OREFSSUVTID0gXFtbXHNcU10qP1xu'
        'XF07LylbMF07CmNvbnN0IHJtRGVjbCAgID0gc3JjLm1hdGNoKC9jb25zdCBSTV9XW1xzXFNdKj9j'
        'b25zdCBSTV9DT0xTX1NFQyA9IFxbW1xzXFNdKj9cblxdOy8pWzBdOwovLyBwb2ludGVyQ29uc3Vt'
        'ZWQgcmVhY2hlcyBmb3IgdGhlIHRpdGxlIG9uIGEgZmluaXNoZWQgcnVuLiBTdGFydGluZyBhIHJ1'
        'bgovLyBpcyBub3Qgd2hhdCB0aGVzZSBmaWxlcyB0ZXN0LCBzbyBpdCBpcyBhIHN0dWIuCmNvbnN0'
        'IHdwblN0YXRlID0gJ2xldCByZWFybU1lbnUgPSBmYWxzZTsgbGV0IHJlc3VtZUhvbGQgPSBmYWxz'
        'ZTsnCiAgLy8gVGhlIGJhciBhc2tzIHdoZXJlIHRoZSBwb2ludGVyIGlzIHNpdHRpbmc7IG5vdGhp'
        'bmcgaG92ZXJzIGluIGEgdGVzdC4KICArICcgY29uc3QgSE9WRVIgPSB7eDotMSwgeTotMX07IGZ1'
        'bmN0aW9uIHRvVGl0bGVPckxhdW5jaCgpe307IGNvbnN0IFdQTl9TRUVOID0ge307IGNvbnN0IFVJ'
        'X1dFQVBPTlMgPSBmYWxzZTsnOwoKY29uc3Qgdm9sbGV5RGVjbCA9IHNyYy5tYXRjaCgvY29uc3Qg'
        'Vk9MTEVZX0JBU0VbXHNcU10qP2NvbnN0IFZPTExFWV9QRVJfRVhUUkFccyo9XHMqW1xkLl0rOy8p'
        'WzBdOwpjb25zdCBuYW1lcyA9IFsKICAnc3luY0N1cnNvcicsJ2hvdmVyaW5nJywKICAncGFuZWxP'
        'cGVuJywnaG9sZFJlc3VtZScsJ2NsZWFyUmVzdW1lSG9sZCcsJ2RyYXdSZXN1bWVIaW50JywKICAn'
        'YXBwbHlMb2Fkb3V0JywncmVhcm1GdWxsJywnY3VyUHJpJywnY3VyU2VjJywncHJpRGVmJywnc2Vj'
        'RGVmJywnaHVsbFNlY0NscycsCiAgJ3dlYXBvbk5hbWUnLCd3ZWFwb25PcGVuJywnc2Vjb25kYXJp'
        'ZXNGb3InLCdkZWZhdWx0U2VjJywnY29ydmV0dGVPbkZpZWxkJywKICAncmVhcm1SZWFkeScsJ3Nl'
        'dFJlYXJtTWVudScsJ3RvZ2dsZVJlYXJtTWVudScsJ2ZpdFdlYXBvbicsJ3JlYXJtTGF5b3V0JywK'
        'ICAnZHJhd1JlYXJtTWVudScsJ2RyYXdSZWFybUljb24nLCdyZWFybUdyb3VwcycsJ3JtVmFsdWUn'
        'LCd0aWNrV2VhcG9uVW5sb2NrcycsCiAgJ3RoRml0JywnY2FsbE1lbnVMYXlvdXQnLCdkcmF3QWxs'
        'eVJvdycsJ2RyYXdLZXlDaGlwJywnZHJhd0h1bGxDZWxsJywnaHVsbENsYXNzJywnaXNCb21iZXJI'
        'dWxsJywnc2hpcFN0YXRzJywnYXBwbHlTaGlwJywndGlja1NoaXBVbmxvY2tzJywnc2hpcFN3YXBS'
        'ZWFkeScsCiAgJ3NldFNoaXBNZW51JywndG9nZ2xlU2hpcE1lbnUnLCdzd2FwU2hpcCcsJ2RyYXdT'
        'd2FwSWNvbicsJ3N0YXRQaXBzJywnZHJhd1NoaXBNZW51JywncG9pbnRlckNvbnN1bWVkJywKICAn'
        'cmVzZXRQbGF5ZXJTaGllbGQnLCdwbGF5ZXJTYycsJ3NldENhbGxNZW51JywKICAnaHVsbEZhYycs'
        'J3NoaXBGYWMnLCdoYW5nYXJTZXJ2ZXMnLCdpc0hhbmdhclNoaXAnLCdoYW5nYXJGYWNzJywnY29s'
        'b3NzdXNPbkZpZWxkJywnc2hpcE9mZmVyZWQnLAogICdtb3VudHNGb3InLCdzcHJpdGVGYWNpbmcn'
        'LCdkcmF3SHVsbEJnJywnZHJhd0h1bGxDZWxsJywndm9sbGV5RG1nJywndm9sbGV5VG90YWwnLCdw'
        'cmltYXJ5Q291bnQnLCdzeW5jUGF1c2UnLAogICdoYW5nYXJHcm91cHMnLCdoYW5nYXJMYXlvdXQn'
        'LCdkcmF3TWlzc2lsZUljb24nLCdkcmF3Qm9tYkljb24nLCdkcmF3S2V5Q2hpcCcsCiAgJ2hhbmdh'
        'ck9yZGVyJywnaW5zaWRlUGFuZWwnLCdjeWNsZUF0JywnZW50ZXJDeWNsZScsJ3RpdGxlRnNIaXQn'
        'LAogICd0aENoYW1mZXJQYXRoJywndGhQbGF0ZScsJ3RoR2xvd1BhdGgnLCd0aEJyYWNrZXRzJywn'
        'dGhTY2FsZScsJ3RoRnJhbWUnLCd0aFJHQkEnLCd0aEdsb3NzJywndGhDdXRHbGludCcsCiAgJ1RI'
        'JywndGhMYWJlbCcsJ3RoVmFsdWUnLCd0aEJldmVsJywndGhHbG93JywndGhQYW5lbCcsJ3RoQnV0'
        'dG9uJywndGhEaXZpZGVyJywnZHJhd1N3YXBJY29uJywnVUknLCd1aUhMUCcsJ3VpTGFiZWwnLCd1'
        'aVZhbHVlJywndWlDZWxsJywndWlEaWFsb2cnXTsKY29uc3Qga2V5SGFuZGxlciA9IGJldHdlZW4o'
        'ImRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLGZ1bmN0aW9uKGV2KXtcbiAgaWYo'
        'R1MhPT0ncGxheWluZycpIHJldHVybjsiKTsKY29uc3QgZG93blN0YXJ0ID0gc3JjLmluZGV4T2Yo'
        'IkNWUy5hZGRFdmVudExpc3RlbmVyKCdtb3VzZWRvd24nLCIpOwpjb25zdCBtb3VzZUhhbmRsZXIg'
        'PSBzcmMuc2xpY2Uoc3JjLmluZGV4T2YoJ2Z1bmN0aW9uJywgZG93blN0YXJ0KSwgYmxvY2tFbmQo'
        'c3JjLCBzcmMuaW5kZXhPZignZnVuY3Rpb24nLCBkb3duU3RhcnQpKSk7CmNvbnN0IGxhdW5jaCA9'
        'IGZuKCdsYXVuY2hHYW1lJyk7Cgpjb25zdCBDQUxMUyA9IFtdOwpjb25zdCBjdHhTdHViID0gbmV3'
        'IFByb3h5KHt9LCB7CiAgZ2V0Oih0LGspPT4gayBpbiB0ID8gdFtrXSA6IGZ1bmN0aW9uKCl7CiAg'
        'ICBDQUxMUy5wdXNoKHtmbjpTdHJpbmcoayksIGFyZ3M6W10uc2xpY2UuY2FsbChhcmd1bWVudHMp'
        'fSk7CiAgICAvLyBjcmVhdGVMaW5lYXJHcmFkaWVudCBoYXMgdG8gaGFuZCBiYWNrIHNvbWV0aGlu'
        'ZyB3aXRoIGFkZENvbG9yU3RvcC4KICAgIGlmKGs9PT0nY3JlYXRlTGluZWFyR3JhZGllbnQnKSBy'
        'ZXR1cm4ge2FkZENvbG9yU3RvcDpmdW5jdGlvbigpe319OwogICAgLy8gdGhGaXQgbWVhc3VyZXMg'
        'YmVmb3JlIGl0IGN1dHMsIHNvIHRoZSBzdHViIGhhcyB0byBhbnN3ZXIgd2l0aCBhIHdpZHRoLgog'
        'ICAgLy8gUm91Z2hseSAwLjU1IG9mIHRoZSBzZXQgcG9pbnQgc2l6ZSBwZXIgY2hhcmFjdGVyIGlz'
        'IGNsb3NlIGVub3VnaCBmb3IKICAgIC8vIHRoZSBsYXlvdXQgZGVjaXNpb25zIGJlaW5nIGNoZWNr'
        'ZWQgaGVyZS4KICAgIGlmKGs9PT0nbWVhc3VyZVRleHQnKXsKICAgICAgY29uc3QgcHggPSBwYXJz'
        'ZUZsb2F0KFN0cmluZyh0LmZvbnR8fCcxMHB4JykucmVwbGFjZSgvXmJvbGRccysvLCcnKSkgfHwg'
        'MTA7CiAgICAgIHJldHVybiB7d2lkdGg6IFN0cmluZyhhcmd1bWVudHNbMF18fCcnKS5sZW5ndGgg'
        'KiBweCAqIDAuNTV9OwogICAgfQogIH0sCiAgc2V0Oih0LGssdik9PnsgQ0FMTFMucHVzaCh7Zm46'
        'J3NldCAnK1N0cmluZyhrKSwgYXJnczpbdl19KTsgdFtrXT12OyByZXR1cm4gdHJ1ZTsgfQp9KTsK'
        'Ly8gSGVscGVycyBvdmVyIHRoZSByZWNvcmRlZCBkcmF3aW5nIGNhbGxzLgpjb25zdCBDTFIgICAg'
        'PSAoKT0+eyBDQUxMUy5sZW5ndGggPSAwOyB9Owpjb25zdCBkcmF3cyAgPSAoKT0+IENBTExTLmZp'
        'bHRlcihjPT5jLmZuPT09J2RyYXdJbWFnZScpOwpjb25zdCBjbGlwcyAgPSAoKT0+IENBTExTLmZp'
        'bHRlcihjPT5jLmZuPT09J2NsaXAnKTsKY29uc3QgYWxwaGFzID0gKCk9PiBDQUxMUy5maWx0ZXIo'
        'Yz0+Yy5mbj09PSdzZXQgZ2xvYmFsQWxwaGEnKS5tYXAoYz0+Yy5hcmdzWzBdKTsKLy8gRXZlcnkg'
        'c3ByaXRlIGhhcyB0byBzaXQgaW5zaWRlIGEgc2F2ZS9yZXN0b3JlIHBhaXIsIG90aGVyd2lzZSBp'
        'dHMgY2xpcCBhbmQKLy8gaXRzIGFscGhhIGxlYWsgaW50byB3aGF0ZXZlciBpcyBkcmF3biBuZXh0'
        'LgpmdW5jdGlvbiBiYWxhbmNlZCgpewogIGxldCBkID0gMCwgb2tBbGwgPSB0cnVlOwogIGZvcihj'
        'b25zdCBjIG9mIENBTExTKXsKICAgIGlmKGMuZm49PT0nc2F2ZScpIGQrKzsKICAgIGVsc2UgaWYo'
        'Yy5mbj09PSdyZXN0b3JlJyl7IGQtLTsgaWYoZDwwKSBva0FsbD1mYWxzZTsgfQogICAgZWxzZSBp'
        'ZigoYy5mbj09PSdkcmF3SW1hZ2UnIHx8IGMuZm49PT0nY2xpcCcpICYmIGQ8MSkgb2tBbGw9ZmFs'
        'c2U7CiAgfQogIHJldHVybiBva0FsbCAmJiBkPT09MDsKfQoKY29uc3Qgd29ybGQgPSBgCiAgY29u'
        'c3QgVz04MDAsSD01MDAsSFVEX0g9NTQsIFBMQVlFUl9TUERfRklHSFRFUj0zLjIsIFBMQVlFUl9T'
        'UERfQk9NQkVSPTIuNCwgUExBWUVSX1RVUk49MC4xNDsKICBsZXQgRlMxX01PREU9ZmFsc2UsIEdT'
        'PSdwbGF5aW5nJywgcGF1c2VkPWZhbHNlLCBjYWxsTWVudT1mYWxzZSwgd2F2ZT0xLCBzY29yZT0w'
        'LCBhbGxpZXM9W10sIGp1bXA9ZmFsc2U7CiAgbGV0IHNldHRpbmdzT3Blbj1mYWxzZSwgdXNlclBh'
        'dXNlZD1mYWxzZTsKICBsZXQgU1VCX01TR1M9W10sIE1PVVNFPXt4OjAseTowfSwgbGl2ZXM9Mywg'
        'cGxheWVyPXt4OjEwMCx5OjIwMCxodWxsTXVsdDoxfTsKICBsZXQgZXJhT2ZmPWZhbHNlLCBJTUdT'
        'PXt9LCBpc0ZpcmluZz1mYWxzZSwgbGF1bmNoZWQ9MDsKICBjb25zdCBjdHg9Q1RYLCBkb2N1bWVu'
        'dD17Ym9keTp7Y2xhc3NMaXN0OnthZGQoKXt9LHJlbW92ZSgpe319fSwgZ2V0RWxlbWVudEJ5SWQo'
        'KXtyZXR1cm4ge3N0eWxlOnt9fTt9fTsKICBjb25zdCB3aW5kb3c9e307CiAgZnVuY3Rpb24gaW5K'
        'dW1wKCl7cmV0dXJuIGp1bXA7fSBmdW5jdGlvbiBlcmFTaGllbGRzT2ZmKCl7cmV0dXJuIGVyYU9m'
        'Zjt9CiAgZnVuY3Rpb24gc2V0U2V0dGluZ3MoKXt9IGZ1bmN0aW9uIHRvZ2dsZUZ1bGxzY3JlZW4o'
        'KXt9IGZ1bmN0aW9uIHJlZmluZVRpY2tldCgpe30gZnVuY3Rpb24gY2FsbEFsbHkoKXt9CiAgZnVu'
        'Y3Rpb24gYWxseVJlYWR5KCl7cmV0dXJuIHRydWU7fSBmdW5jdGlvbiB0b2dnbGVDYWxsTWVudSgp'
        'e30gZnVuY3Rpb24gdG9HQyh4LHkpe3JldHVybiB7eDp4LHk6eX07fQogIGxldCBzaGlwVW5sb2Nr'
        'ZWQ9MSwgc2hpcFN3YXBXYXZlPS0xLCBzaGlwTWVudT1mYWxzZSwgZ2FtZU92ZXJBdD0wOwogIGNv'
        'bnN0IEFMTFlfS0VZUz1bXSwgQUxMWV9PUkRFUj1bXSwgQUxMWV9TUEVDSUFMPSd4JywgQUxMWV9T'
        'UEVDSUFMX0tFWT0nUSc7CiAgJHtodWxsRmFjRGVjbH0KICAke3dwbkRlY2x9CiAgJHt3cG5EZWNs'
        'Mn0KICAke3JtRGVjbH0KICAke3dwblN0YXRlfQogICR7dGhlbWVzRGVjbH0KICBsZXQgRUNPPXto'
        'dWQ6J2hscCcsIHNjaGVtZTonZmlyZSd9OwogICR7bWVudUJnRGVjbH0KICAke2hhbmdhckRlY2x9'
        'CiAgJHt2b2xsZXlEZWNsfQogIGxldCBNT1VOVFM9e307CiAgJHtzaGlwc0RlY2x9CiAgbGV0IFVJ'
        'X1NISVBTPTE7CiAgJHtmYWNPbkRlY2x9CiAgJHtjeWNsZURlY2x9CiAgJHtuYW1lcy5tYXAoZm4p'
        'LmpvaW4oJ1xuJyl9CiAgY29uc3Qgb25LZXkgPSAke2tleUhhbmRsZXJ9OwogIGNvbnN0IG9uRG93'
        'biA9ICR7bW91c2VIYW5kbGVyfTsKICByZXR1cm4gewogICAgZ2V0OihrKT0+ZXZhbChrKSwgc2V0'
        'OihrLHYpPT5ldmFsKGsrJz12JyksIHJ1bjooY29kZSk9PmV2YWwoY29kZSkKICB9O2A7CmNvbnN0'
        'IFcgPSBuZXcgRnVuY3Rpb24oJ0NUWCcsIHdvcmxkKShjdHhTdHViKTsKbGV0IGZhaWxzID0gMDsK'
        'ZnVuY3Rpb24gb2sobGFiZWwsIGNvbmQpeyBjb25zb2xlLmxvZygoY29uZD8nICBvayAgICAnOicg'
        'IEZBSUwgICcpK2xhYmVsKTsgaWYoIWNvbmQpIGZhaWxzKys7IH0KY29uc3QgUCA9ICgpPT5XLmdl'
        'dCgncGxheWVyJyk7CmNvbnN0IHJlc2V0ID0gKCk9PnsgVy5ydW4oIkdTPSdwbGF5aW5nJztwYXVz'
        'ZWQ9ZmFsc2U7cmVzdW1lSG9sZD1mYWxzZTtjYWxsTWVudT1mYWxzZTtzaGlwTWVudT1mYWxzZTt3'
        'YXZlPTE7c2NvcmU9MDthbGxpZXM9W107anVtcD1mYWxzZTtGUzFfTU9ERT1mYWxzZTtzaGlwVW5s'
        'b2NrZWQ9MTtzaGlwU3dhcFdhdmU9LTE7U1VCX01TR1M9W107cGxheWVyPXt4OjEwMCx5OjIwMCxo'
        'dWxsTXVsdDoxfTthcHBseVNoaXAoUExBWUVSX1NISVBTWzBdLmtleSkiKTsgfTsKY29uc3QgZGVz'
        'dHJveWVyID0gKG8pPT5PYmplY3QuYXNzaWduKHtpbWc6J2RlaGF0c2hlcHN1dCcsIHNtYWxsOmZh'
        'bHNlLCBkZWFkOmZhbHNlLCB3YXJwT3V0OmZhbHNlfSwgb3x8e30pOwoKY29uc29sZS5sb2coJ1N0'
        'YXJ0IHNoaXAnKTsKcmVzZXQoKTsKb2soJ3N0YXJ0cyBpbiB0aGUgVGhvdGgnLCBQKCkuc2hpcD09'
        'PSdmaXRvdGgnKTsKb2soJ1Rob3RoIHN0YXRzIDMuNSAvIDAuMTcgLyAxMDAgLyAxMDAgLyAyMCBt'
        'aXNzaWxlcycsIFAoKS5zcGQ9PT0zLjUgJiYgUCgpLnR1cm49PT0wLjE3ICYmIFAoKS5tYXhIcD09'
        'PTEwMCAmJiBQKCkubWF4U2g9PT0xMDAgJiYgUCgpLnNlY01heD09PTIwICYmIFAoKS5zZWNUeXBl'
        'PT09J21pc3NpbGUnKTsKCmNvbnNvbGUubG9nKCdVbmxvY2tzJyk7CnJlc2V0KCk7ClcucnVuKCJz'
        'Y29yZT0zOTk5OyB0aWNrU2hpcFVubG9ja3MoKSIpOyBvaygnMzk5OSBwb2ludHM6IG5vdGhpbmcg'
        'dW5sb2NrZWQnLCBXLmdldCgnc2hpcFVubG9ja2VkJyk9PT0xKTsKVy5ydW4oInNjb3JlPTQwMDA7'
        'IHRpY2tTaGlwVW5sb2NrcygpIik7IG9rKCc0MDAwIHBvaW50czogSG9ydXMgdW5sb2NrZWQsIG9u'
        'ZSBtZXNzYWdlJywgVy5nZXQoJ3NoaXBVbmxvY2tlZCcpPT09MiAmJiBXLmdldCgnU1VCX01TR1Mn'
        'KS5sZW5ndGg9PT0xICYmIC9IT1JVUy8udGVzdChXLmdldCgnU1VCX01TR1MnKVswXS50eHQpKTsK'
        'Vy5ydW4oInNjb3JlPTIzMDAwOyB0aWNrU2hpcFVubG9ja3MoKSIpOyBvaygnanVtcCB0byAyMzAw'
        'MDogT3NpcmlzLCBTZXJhcGlzLCBTZXRoIGF0IG9uY2UnLCBXLmdldCgnc2hpcFVubG9ja2VkJyk9'
        'PT01ICYmIFcuZ2V0KCdTVUJfTVNHUycpLmxlbmd0aD09PTQpOwpXLnJ1bigic2NvcmU9OTk5OTk5'
        'OyB0aWNrU2hpcFVubG9ja3MoKSIpOyBvaygnbmV2ZXIgcGFzdCB0aGUgZW5kIG9mIHRoZSBsaXN0'
        'JywgVy5nZXQoJ3NoaXBVbmxvY2tlZCcpPT09OCk7ClcucnVuKCJ0aWNrU2hpcFVubG9ja3MoKSIp'
        'OyBvaygnc2V2ZW4gdW5sb2NrIG1lc3NhZ2VzIGluIHRvdGFsLCBub25lIHJlcGVhdGVkJywgVy5n'
        'ZXQoJ1NVQl9NU0dTJykubGVuZ3RoPT09Nyk7CnJlc2V0KCk7IFcucnVuKCJGUzFfTU9ERT10cnVl'
        'OyBzY29yZT05OTk5OTsgdGlja1NoaXBVbmxvY2tzKCkiKTsgb2soJ0ZTMSBtb2RlOiBubyB1bmxv'
        'Y2tzJywgVy5nZXQoJ3NoaXBVbmxvY2tlZCcpPT09MSk7CnJlc2V0KCk7IFcucnVuKCJHUz0nZ2Ft'
        'ZW92ZXInOyBzY29yZT05OTk5OTsgdGlja1NoaXBVbmxvY2tzKCkiKTsgb2soJ25vdCBvdXRzaWRl'
        'IHBsYXknLCBXLmdldCgnc2hpcFVubG9ja2VkJyk9PT0xKTsKCmNvbnNvbGUubG9nKCdXaGVuIHRo'
        'ZSBzd2l0Y2ggaXMgYXZhaWxhYmxlJyk7CmNvbnN0IHJlYWR5ID0gKHNldHVwKT0+eyByZXNldCgp'
        'OyBXLnJ1bigic2hpcFVubG9ja2VkPTMiKTsgc2V0dXAoKTsgcmV0dXJuIFcucnVuKCdzaGlwU3dh'
        'cFJlYWR5KCknKTsgfTsKb2soJ25vIGRlc3Ryb3llcjogbm90IHJlYWR5JywgcmVhZHkoKCk9Pnt9'
        'KT09PWZhbHNlKTsKb2soJ2FsbGllZCBWYXN1ZGFuIGRlc3Ryb3llcjogcmVhZHknLCByZWFkeSgo'
        'KT0+Vy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigpXSkpPT09dHJ1ZSk7Cm9rKCdOVEYgaHVsbCAo'
        'bnRmZGVoZWNhdGUpIGlzIFRlcnJhbiwgbm8gVGVycmFuIGh1bGxzIGV4aXN0OiBub3QgcmVhZHkn'
        'LAogICByZWFkeSgoKT0+Vy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcih7aW1nOidudGZkZWhlY2F0'
        'ZSd9KV0pKT09PWZhbHNlKTsKb2soJ2NydWlzZXIgb25seTogbm90IHJlYWR5JywgcmVhZHkoKCk9'
        'Plcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoe2ltZzonY3JtZW50dSd9KV0pKT09PWZhbHNlKTsK'
        'b2soJ0NvbG9zc3VzIGFsb25lIGlzIGEgam9pbnQgeWFyZDogcmVhZHknLAogICByZWFkeSgoKT0+'
        'Vy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcih7aW1nOidzZGNvbG9zc3VzJywgY29sb3NzdXM6dHJ1'
        'ZX0pXSkpPT09dHJ1ZSk7Cm9rKCdkZWFkIGRlc3Ryb3llcjogbm90IHJlYWR5JywgcmVhZHkoKCk9'
        'Plcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoe2RlYWQ6dHJ1ZX0pXSkpPT09ZmFsc2UpOwpvaygn'
        'ZGVzdHJveWVyIHdhcnBpbmcgb3V0OiBub3QgcmVhZHknLCByZWFkeSgoKT0+Vy5zZXQoJ2FsbGll'
        'cycsW2Rlc3Ryb3llcih7d2FycE91dDp0cnVlfSldKSk9PT1mYWxzZSk7Cm9rKCdvbmx5IHRoZSBz'
        'dGFydCBzaGlwIHVubG9ja2VkOiBub3QgcmVhZHknLCByZWFkeSgoKT0+eyBXLnNldCgnYWxsaWVz'
        'JyxbZGVzdHJveWVyKCldKTsgVy5ydW4oJ3NoaXBVbmxvY2tlZD0xJyk7IH0pPT09ZmFsc2UpOwpv'
        'aygnZHVyaW5nIGEganVtcDogbm90IHJlYWR5JywgcmVhZHkoKCk9PnsgVy5zZXQoJ2FsbGllcycs'
        'W2Rlc3Ryb3llcigpXSk7IFcucnVuKCdqdW1wPXRydWUnKTsgfSk9PT1mYWxzZSk7Cm9rKCdGUzEg'
        'bW9kZTogbm90IHJlYWR5JywgcmVhZHkoKCk9PnsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigp'
        'XSk7IFcucnVuKCdGUzFfTU9ERT10cnVlJyk7IH0pPT09ZmFsc2UpOwoKY29uc29sZS5sb2coJ1N3'
        'aXRjaGluZycpOwpyZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTM7IHBsYXllci5ocD0xMjsg'
        'cGxheWVyLnNoPTU7IHBsYXllci5zZWNBbW1vPTEiKTsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3ll'
        'cigpXSk7ClcucnVuKCd0b2dnbGVTaGlwTWVudSgpJyk7IG9rKCdidXR0b24gb3BlbnMgdGhlIG1l'
        'bnUgYW5kIHBhdXNlcycsIFcuZ2V0KCdzaGlwTWVudScpPT09dHJ1ZSAmJiBXLmdldCgncGF1c2Vk'
        'Jyk9PT10cnVlKTsKVy5ydW4oInN3YXBTaGlwKCdmaXNlcmFwaXMnKSIpOyBvaygnbG9ja2VkIGh1'
        'bGwgKFNlcmFwaXMpIHJlZnVzZWQnLCBQKCkuc2hpcD09PSdmaXRvdGgnICYmIFcuZ2V0KCdzaGlw'
        'TWVudScpPT09dHJ1ZSk7ClcucnVuKCJzd2FwU2hpcCgnZml0b3RoJykiKTsgb2soJ2N1cnJlbnQg'
        'aHVsbCByZWZ1c2VkJywgVy5nZXQoJ3NoaXBNZW51Jyk9PT10cnVlICYmIFcuZ2V0KCdzaGlwU3dh'
        'cFdhdmUnKT09PS0xKTsKVy5ydW4oInN3YXBTaGlwKCdib29zaXJpcycpIik7Ci8vIFRoZSBwYW5l'
        'bCBjbG9zZXMsIGJ1dCB0aGUgZ2FtZSBzdGF5cyBzdG9wcGVkOiBjb21pbmcgYmFjayBpbnRvIHRo'
        'ZQovLyBmaWdodCBpcyB0aGUgcGxheWVyJ3MgdG8gdGltZSBub3csIHdoYXRldmVyIHRoZSBwYW5l'
        'bCBhbmQgaG93ZXZlciBpdAovLyB3YXMgbGVmdC4Kb2soJ09zaXJpcyB0YWtlbiBhbmQgdGhlIG1l'
        'bnUgY2xvc2VkJywgUCgpLnNoaXA9PT0nYm9vc2lyaXMnICYmIFcuZ2V0KCdzaGlwTWVudScpPT09'
        'ZmFsc2UpOwpvaygnYnV0IHRoZSBnYW1lIGlzIHN0aWxsIGhlbGQnLCBXLmdldCgncGF1c2VkJyk9'
        'PT10cnVlICYmIFcuZ2V0KCdyZXN1bWVIb2xkJyk9PT10cnVlKTsKVy5ydW4oJ3BvaW50ZXJDb25z'
        'dW1lZCh7eDo0MDAseTozMDB9KScpOwpvaygnYW5kIG9uZSB0YXAgcHV0cyB5b3UgYmFjayBpbiBp'
        'dCcsIFcuZ2V0KCdwYXVzZWQnKT09PWZhbHNlICYmIFcuZ2V0KCdyZXN1bWVIb2xkJyk9PT1mYWxz'
        'ZSk7Cm9rKCdPc2lyaXMgc3RhdHMgMi41IC8gMC4xMCAvIDE0MCAvIDEwMCAvIDEwIGJvbWJzJywg'
        'UCgpLnNwZD09PTIuNSAmJiBQKCkudHVybj09PTAuMTAgJiYgUCgpLm1heEhwPT09MTQwICYmIFAo'
        'KS5tYXhTaD09PTEwMCAmJiBQKCkuc2VjTWF4PT09MTAgJiYgUCgpLnNlY1R5cGU9PT0nYm9tYicp'
        'OwpvaygncmVmaWxsZWQ6IGh1bGwgMTQwLCBzaGllbGRzIDEwMCwgMTAgYm9tYnMnLCBQKCkuaHA9'
        'PT0xNDAgJiYgUCgpLnNoPT09MTAwICYmIFAoKS5zZWNBbW1vPT09MTApOwpvaygnc3dpdGNoIHNw'
        'ZW50IGZvciB0aGlzIHdhdmUnLCBXLnJ1bignc2hpcFN3YXBSZWFkeSgpJyk9PT1mYWxzZSk7Clcu'
        'cnVuKCd0b2dnbGVTaGlwTWVudSgpJyk7IG9rKCdtZW51IGRvZXMgbm90IG9wZW4gYWdhaW4gdGhp'
        'cyB3YXZlJywgVy5nZXQoJ3NoaXBNZW51Jyk9PT1mYWxzZSk7ClcucnVuKCd3YXZlPTInKTsgb2so'
        'J25leHQgd2F2ZTogYXZhaWxhYmxlIGFnYWluJywgVy5ydW4oJ3NoaXBTd2FwUmVhZHkoKScpPT09'
        'dHJ1ZSk7Cgpjb25zb2xlLmxvZygnQ3ljbGUgc2NhbGluZyBhbmQgc2hpZWxkcycpOwpyZXNldCgp'
        'OyBXLnJ1bigicGxheWVyLmh1bGxNdWx0PTEuNTsgc2hpcFVubG9ja2VkPTgiKTsgVy5zZXQoJ2Fs'
        'bGllcycsW2Rlc3Ryb3llcigpXSk7ClcucnVuKCJ0b2dnbGVTaGlwTWVudSgpOyBzd2FwU2hpcCgn'
        'Ym9zZWtobWV0JykiKTsgb2soJ1Nla2htZXQgYXQgY3ljbGUgeDEuNTogaHVsbCAyMTAnLCBQKCku'
        'bWF4SHA9PT0yMTAgJiYgUCgpLmhwPT09MjEwKTsKcmVzZXQoKTsgVy5ydW4oImVyYU9mZj10cnVl'
        'OyBzaGlwVW5sb2NrZWQ9MiIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsKVy5ydW4o'
        'InRvZ2dsZVNoaXBNZW51KCk7IHN3YXBTaGlwKCdmaWhvcnVzJykiKTsgb2soJ2VyYSB3aXRob3V0'
        'IHNoaWVsZHM6IHNoaWVsZHMgc3RheSAwJywgUCgpLnNoPT09MCAmJiBQKCkubWF4U2g9PT0xMDAp'
        'OwpXLnJ1bignZXJhT2ZmPWZhbHNlJyk7Cgpjb25zb2xlLmxvZygnQ2FsbCBtZW51IGFuZCBzd2l0'
        'Y2ggbWVudSBleGNsdWRlIGVhY2ggb3RoZXInKTsKcmVzZXQoKTsgVy5ydW4oInNoaXBVbmxvY2tl'
        'ZD0yOyBjYWxsTWVudT10cnVlOyBwYXVzZWQ9dHJ1ZSIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJv'
        'eWVyKCldKTsKVy5ydW4oJ3RvZ2dsZVNoaXBNZW51KCknKTsgb2soJ29wZW5pbmcgdGhlIHN3aXRj'
        'aCBjbG9zZXMgdGhlIGNhbGwgbWVudScsIFcuZ2V0KCdjYWxsTWVudScpPT09ZmFsc2UgJiYgVy5n'
        'ZXQoJ3NoaXBNZW51Jyk9PT10cnVlKTsKCmNvbnNvbGUubG9nKCdNZW51IGRyYXdpbmcgYW5kIHRh'
        'cHMnKTsKcmVzZXQoKTsgVy5ydW4oInNoaXBVbmxvY2tlZD0zIik7IFcuc2V0KCdhbGxpZXMnLFtk'
        'ZXN0cm95ZXIoKV0pOyBXLnJ1bigndG9nZ2xlU2hpcE1lbnUoKTsgZHJhd1NoaXBNZW51KCknKTsK'
        'Y29uc3QgcmVjdHMgPSBXLnJ1bignd2luZG93Ll9zaGlwUmVjdHMnKTsKY29uc3Qgcm93T2YgPSAo'
        'a2V5KT0+Vy5ydW4oJ3dpbmRvdy5fc2hpcFJlY3RzJykuZmluZChyPT5yLnNoaXA9PT1rZXkpOwpv'
        'aygnZWlnaHQgcm93cyBkcmF3bicsIHJlY3RzLmxlbmd0aD09PTgpOwpvaygnbWVudSBmaXRzIG9u'
        'IHRoZSA4MDB4NTAwIGZpZWxkJywgcmVjdHMuZXZlcnkocj0+ci54Pj0wICYmIHIueT49MCAmJiBy'
        'Lngrci53PD04MDAgJiYgci55K3IuaDw9NTAwKSk7Cm9rKCdmaWdodGVycyBmaXJzdCwgdGhlbiBi'
        'b21iZXJzJywKICAgcmVjdHMubWFwKHI9PnIuc2hpcCkuam9pbigpPT09J2ZpdG90aCxmaWhvcnVz'
        'LGZpc2VyYXBpcyxmaXNldGgsZml0YXVyZXQsYm9vc2lyaXMsYm9iYWtoYSxib3Nla2htZXQnKTsK'
        'b2soJ2V2ZXJ5IHJvdyBpcyBmdWxsIHdpZHRoIGFuZCB0aGV5IGRvIG5vdCBvdmVybGFwJywKICAg'
        'cmVjdHMuZXZlcnkocj0+ci53PT09cmVjdHNbMF0udykgJiYKICAgcmVjdHMuZXZlcnkoKHIsaSk9'
        'Pmk9PT0wIHx8IHIueSA+PSByZWN0c1tpLTFdLnkrcmVjdHNbaS0xXS5oKSk7Cm9rKCdhIGxvY2tl'
        'ZCByb3cgaXMgdGhpbm5lciB0aGFuIG9uZSB0aGF0IGNhbiBiZSB0YWtlbicsCiAgIHJvd09mKCdi'
        'b2Jha2hhJykuaCA8IHJvd09mKCdmaWhvcnVzJykuaCk7Cm9rKCdvbmx5IEhvcnVzIGFuZCBPc2ly'
        'aXMgYXJlIHRhcHBhYmxlJywgcmVjdHMuZmlsdGVyKHI9PnIua2V5KS5tYXAocj0+ci5rZXkpLmpv'
        'aW4oKT09PSdmaWhvcnVzLGJvb3NpcmlzJyk7CmNvbnN0IGxvY2tlZCA9IHJvd09mKCdib2Jha2hh'
        'Jyk7ClcucnVuKGBwb2ludGVyQ29uc3VtZWQoe3g6JHtsb2NrZWQueCs1fSx5OiR7bG9ja2VkLnkr'
        'NX19KWApOyBvaygndGFwIG9uIGxvY2tlZCBCYWtoYSBrZWVwcyB0aGUgbWVudSBvcGVuJywgVy5n'
        'ZXQoJ3NoaXBNZW51Jyk9PT10cnVlICYmIFAoKS5zaGlwPT09J2ZpdG90aCcpOwpjb25zdCBob3J1'
        'cyA9IHJvd09mKCdmaWhvcnVzJyk7ClcucnVuKGBwb2ludGVyQ29uc3VtZWQoe3g6JHtob3J1cy54'
        'KzV9LHk6JHtob3J1cy55KzV9fSlgKTsgb2soJ3RhcCBvbiBIb3J1cyBzd2l0Y2hlcycsIFAoKS5z'
        'aGlwPT09J2ZpaG9ydXMnICYmIFcuZ2V0KCdzaGlwTWVudScpPT09ZmFsc2UpOwpyZXNldCgpOyBX'
        'LnJ1bigic2hpcFVubG9ja2VkPTMiKTsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigpXSk7IFcu'
        'cnVuKCd0b2dnbGVTaGlwTWVudSgpJyk7ClcucnVuKCdwb2ludGVyQ29uc3VtZWQoe3g6Mix5OjJ9'
        'KScpOyBvaygndGFwIG91dHNpZGUgY2xvc2VzIHdpdGhvdXQgc3dpdGNoaW5nJywgVy5nZXQoJ3No'
        'aXBNZW51Jyk9PT1mYWxzZSAmJiBQKCkuc2hpcD09PSdmaXRvdGgnICYmIFcucnVuKCdzaGlwU3dh'
        'cFJlYWR5KCknKT09PXRydWUpOwpvaygnY2FuY2VsbGluZyBob2xkcyB0aGUgcGF1c2UganVzdCB0'
        'aGUgc2FtZScsIFcuZ2V0KCdyZXN1bWVIb2xkJyk9PT10cnVlKTsKVy5ydW4oJ2NsZWFyUmVzdW1l'
        'SG9sZCgpJyk7ClcucnVuKCJ3aW5kb3cuX3NoaXBCdG5SZWN0PXt4OjY5NSx5OjQsdzoyMixoOjIw'
        'fTsgcG9pbnRlckNvbnN1bWVkKHt4OjcwMCx5OjEwfSkiKTsgb2soJ3RhcCBvbiB0aGUgYmFyIGJ1'
        'dHRvbiBvcGVucyB0aGUgbWVudScsIFcuZ2V0KCdzaGlwTWVudScpPT09dHJ1ZSk7Cgpjb25zb2xl'
        'LmxvZygnVGhlIHBhbmVsIHN3YWxsb3dzIGl0cyBvd24gY2xpY2tzJyk7CnsKICByZXNldCgpOyBX'
        'LnJ1bigic2hpcFVubG9ja2VkPTgiKTsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigpXSk7CiAg'
        'Vy5ydW4oJ3RvZ2dsZVNoaXBNZW51KCknKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7CiAgY29u'
        'c3QgcHIgPSBXLnJ1bignd2luZG93Ll9zaGlwUGFuZWxSZWN0Jyk7CiAgb2soJ3RoZSBwYW5lbCBy'
        'ZXBvcnRzIGl0cyBvdXRsaW5lJywgcHIgJiYgcHIudz4wICYmIHByLmg+MCk7CiAgLy8gVGhlIGhl'
        'YWRlciBsaW5lOiBpbnNpZGUgdGhlIHBhbmVsLCBvbiBubyByb3cgYXQgYWxsLgogIFcucnVuKGBw'
        'b2ludGVyQ29uc3VtZWQoe3g6JHtwci54KzQwfSx5OiR7cHIueSs2fX0pYCk7CiAgb2soJ2EgY2xp'
        'Y2sgb24gdGhlIGhlYWRlciBrZWVwcyB0aGUgcGFuZWwgb3BlbicsIFcuZ2V0KCdzaGlwTWVudScp'
        'PT09dHJ1ZSk7CiAgLy8gQSBnYXAgYmV0d2VlbiB0d28gcm93cy4KICBjb25zdCBycyA9IFcucnVu'
        'KCd3aW5kb3cuX3NoaXBSZWN0cycpOwogIGNvbnN0IGdhcFkgPSByc1swXS55ICsgcnNbMF0uaCAr'
        'IDI7CiAgVy5ydW4oYHBvaW50ZXJDb25zdW1lZCh7eDoke3JzWzBdLngrNDB9LHk6JHtnYXBZfX0p'
        'YCk7CiAgb2soJ2EgY2xpY2sgaW4gdGhlIGdhcCBiZXR3ZWVuIHJvd3Mga2VlcHMgaXQgb3BlbiB0'
        'b28nLCBXLmdldCgnc2hpcE1lbnUnKT09PXRydWUpOwogIC8vIFRoZSBmb290ZXIuCiAgVy5ydW4o'
        'YHBvaW50ZXJDb25zdW1lZCh7eDoke3ByLngrcHIudy8yfSx5OiR7cHIueStwci5oLTZ9fSlgKTsK'
        'ICBvaygnYW5kIG9uZSBvbiB0aGUgZm9vdGVyJywgVy5nZXQoJ3NoaXBNZW51Jyk9PT10cnVlKTsK'
        'ICBvaygnbm9uZSBvZiB0aGVtIHN3aXRjaGVkIHRoZSBzaGlwJywgUCgpLnNoaXA9PT0nZml0b3Ro'
        'Jyk7CiAgLy8gT3V0c2lkZSB0aGUgb3V0bGluZSBpcyBzdGlsbCBvdXRzaWRlLgogIFcucnVuKGBw'
        'b2ludGVyQ29uc3VtZWQoe3g6JHtwci54LTEyfSx5OiR7cHIueStwci5oLzJ9fSlgKTsKICBvaygn'
        'YSBjbGljayBiZXNpZGUgdGhlIHBhbmVsIGNsb3NlcyBpdCcsIFcuZ2V0KCdzaGlwTWVudScpPT09'
        'ZmFsc2UpOwp9Cgpjb25zb2xlLmxvZygnS2V5Ym9hcmQnKTsKY29uc3Qga2V5ID0gKGNvZGUpPT5X'
        'LnJ1bihgb25LZXkoe2NvZGU6JyR7Y29kZX0nLCBwcmV2ZW50RGVmYXVsdCgpe319KWApOwpyZXNl'
        'dCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTQiKTsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigp'
        'XSk7CmtleSgnS2V5VicpOyBvaygnViBvcGVucycsIFcuZ2V0KCdzaGlwTWVudScpPT09dHJ1ZSk7'
        'Ci8vIEZvdXIgaHVsbHMgb3Blbjogcm9zdGVyIDAgdG8gMy4gVGhlIGRpZ2l0cyBmb2xsb3cgdGhl'
        'IHBhbmVsLCBzbyA0IGlzIHRoZQovLyBTZXRoLCB3aGljaCBpcyBzdGlsbCBsb2NrZWQsIGFuZCA2'
        'IGlzIHRoZSBmaXJzdCBib21iZXIuCmtleSgnRGlnaXQ0Jyk7IG9rKCc0ICh0aGUgU2V0aCwgbm90'
        'IHVubG9ja2VkIHlldCkgZG9lcyBub3RoaW5nJywKICAgICAgICAgICAgICAgICAgVy5nZXQoJ3No'
        'aXBNZW51Jyk9PT10cnVlICYmIFAoKS5zaGlwPT09J2ZpdG90aCcpOwprZXkoJ0RpZ2l0NicpOyBv'
        'aygnNiB0YWtlcyB0aGUgT3NpcmlzLCBmaXJzdCByb3cgb2YgdGhlIGJvbWJlcnMnLAogICAgICAg'
        'ICAgICAgICAgICBQKCkuc2hpcD09PSdib29zaXJpcycgJiYgVy5nZXQoJ3NoaXBNZW51Jyk9PT1m'
        'YWxzZSk7CnJlc2V0KCk7IFcucnVuKCJzaGlwVW5sb2NrZWQ9NCIpOyBXLnNldCgnYWxsaWVzJyxb'
        'ZGVzdHJveWVyKCldKTsga2V5KCdLZXlWJyk7CmtleSgnRGlnaXQzJyk7IG9rKCczIHRha2VzIHRo'
        'ZSBTZXJhcGlzLCB0aGlyZCByb3cgZG93bicsCiAgICAgICAgICAgICAgICAgIFAoKS5zaGlwPT09'
        'J2Zpc2VyYXBpcycgJiYgVy5nZXQoJ3NoaXBNZW51Jyk9PT1mYWxzZSk7CnJlc2V0KCk7IFcucnVu'
        'KCJzaGlwVW5sb2NrZWQ9NCIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsga2V5KCdL'
        'ZXlWJyk7IGtleSgnRXNjYXBlJyk7Cm9rKCdFc2NhcGUgY2xvc2VzJywgVy5nZXQoJ3NoaXBNZW51'
        'Jyk9PT1mYWxzZSk7Cm9rKCdhbmQgaG9sZHMgdGhlIHBhdXNlLCBsaWtlIGV2ZXJ5IG90aGVyIHdh'
        'eSBvZiBsZWF2aW5nIGEgcGFuZWwnLAogICBXLmdldCgncGF1c2VkJyk9PT10cnVlICYmIFcuZ2V0'
        'KCdyZXN1bWVIb2xkJyk9PT10cnVlKTsKVy5ydW4oJ2NsZWFyUmVzdW1lSG9sZCgpJyk7Cm9rKCdh'
        'ZnRlciB0aGUgdGFwIHRoZSBnYW1lIHJ1bnMgYWdhaW4nLCBXLmdldCgncGF1c2VkJyk9PT1mYWxz'
        'ZSk7CnJlc2V0KCk7IGtleSgnS2V5VicpOyBvaygnViB3aXRob3V0IGEgZGVzdHJveWVyIGRvZXMg'
        'bm90aGluZycsIFcuZ2V0KCdzaGlwTWVudScpPT09ZmFsc2UpOwoKY29uc29sZS5sb2coJ1Jlc3Rh'
        'cnQgZ3VhcmQnKTsKVy5ydW4oImxhdW5jaEdhbWU9ZnVuY3Rpb24oKXtsYXVuY2hlZCsrfSIpOwov'
        'LyBUaGUgdGl0bGUgYW5kIHRoZSBnYW1lIG92ZXIgc2NyZWVuIGJvdGggZ28gdGhyb3VnaCB0b1Rp'
        'dGxlT3JMYXVuY2ggbm93LAovLyBzbyB0aGF0IGlzIHdoYXQgaGFzIHRvIGJlIGluIHBsYWNlIGZv'
        'ciB0aGUgcmVzdGFydCBndWFyZCB0byBiZSB0ZXN0ZWQuClcucnVuKCJ0b1RpdGxlT3JMYXVuY2g9'
        'ZnVuY3Rpb24oKXsgaWYoR1M9PT0nZ2FtZW92ZXInKXsgR1M9J3RpdGxlJzsgcmV0dXJuOyB9IGxh'
        'dW5jaEdhbWUoKTsgfSIpOwpjb25zdCBkb3duID0gKCk9PlcucnVuKCJvbkRvd24oe2J1dHRvbjow'
        'LCBjbGllbnRYOjQwMCwgY2xpZW50WTozMDB9KSIpOwpXLnJ1bigiR1M9J3RpdGxlJzsgbGF1bmNo'
        'ZWQ9MCIpOyBkb3duKCk7IG9rKCd0YXAgb24gdGl0bGUgc3RhcnRzIGF0IG9uY2UnLCBXLmdldCgn'
        'bGF1bmNoZWQnKT09PTEpOwpXLnJ1bigiR1M9J2dhbWVvdmVyJzsgZ2FtZU92ZXJBdD1wZXJmb3Jt'
        'YW5jZS5ub3coKTsgbGF1bmNoZWQ9MCIpOyBkb3duKCk7IG9rKCd0YXAgcmlnaHQgYWZ0ZXIgZHlp'
        'bmcgZG9lcyBub3QgcmVzdGFydCcsIFcuZ2V0KCdsYXVuY2hlZCcpPT09MCk7ClcucnVuKCJnYW1l'
        'T3ZlckF0PXBlcmZvcm1hbmNlLm5vdygpLTIwMDAiKTsgZG93bigpOwpvaygndGFwIGFmdGVyIDIg'
        'cyBnb2VzIGJhY2sgdG8gdGhlIHRpdGxlLCBub3QgaW50byB0aGUgbmV4dCBydW4nLAogICBXLmdl'
        'dCgnbGF1bmNoZWQnKT09PTAgJiYgVy5nZXQoJ0dTJyk9PT0ndGl0bGUnKTsKCgpjb25zb2xlLmxv'
        'ZygnSGFuZ2FycyBieSBmYWN0aW9uJyk7CmNvbnN0IGNvbG9zc3VzID0gKG8pPT5PYmplY3QuYXNz'
        'aWduKHtpbWc6J3NkY29sb3NzdXMnLCBjb2xvc3N1czp0cnVlLCBzbWFsbDpmYWxzZSwgZGVhZDpm'
        'YWxzZSwgd2FycE91dDpmYWxzZX0sIG98fHt9KTsKb2soJ2h1bGwgZmFjdGlvbiBjb21lcyBmcm9t'
        'IHRoZSBrZXknLCBXLnJ1bigiaHVsbEZhYygnZGVoYXRzaGVwc3V0JykiKT09PSd2YXN1ZGFuJwog'
        'ICAmJiBXLnJ1bigiaHVsbEZhYygnZGVvcmlvbnJpZ2h0JykiKT09PSd0ZXJyYW4nICYmIFcucnVu'
        'KCJodWxsRmFjKCdzZGNvbG9zc3VzJykiKT09PSdndHZhJyk7Cm9rKCdhIGRlZmVjdGVkIEhhbW1l'
        'ciBvZiBMaWdodCBUeXBob24gc3RpbGwgY291bnRzIGFzIFZhc3VkYW4nLAogICByZWFkeSgoKT0+'
        'Vy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcih7aW1nOidkZXR5cGhvbicsIGZhY3Rpb246J2hvbCd9'
        'KV0pKT09PXRydWUpOwpvaygnYSByZW5lZ2FkZSBIYXRzaGVwc3V0IHRvbycsCiAgIHJlYWR5KCgp'
        'PT5XLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKHtpbWc6J2RlaGF0c2hlcHN1dCcsIGZhY3Rpb246'
        'J3JlbmVnYWRlJ30pXSkpPT09dHJ1ZSk7Cm9rKCdUZXJyYW4gT3Jpb24gb25seTogbm90IHJlYWR5'
        'JywgcmVhZHkoKCk9Plcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoe2ltZzonZGVvcmlvbnJpZ2h0'
        'J30pXSkpPT09ZmFsc2UpOwpvaygnVGVycmFuIEhlY2F0ZSBvbmx5OiBub3QgcmVhZHknLCByZWFk'
        'eSgoKT0+Vy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcih7aW1nOidkZWhlY2F0ZSd9KV0pKT09PWZh'
        'bHNlKTsKb2soJ09yaW9uIHBsdXMgVHlwaG9uOiByZWFkeSwgdGhlIGxpc3RzIGFkZCB1cCcsCiAg'
        'IHJlYWR5KCgpPT5XLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKHtpbWc6J2Rlb3Jpb25yaWdodCd9'
        'KSwgZGVzdHJveWVyKHtpbWc6J2RldHlwaG9uJ30pXSkpPT09dHJ1ZSk7Cm9rKCd1bmtub3duIGNh'
        'cGl0YWwgaHVsbDogbm90IHJlYWR5JywgcmVhZHkoKCk9Plcuc2V0KCdhbGxpZXMnLFtkZXN0cm95'
        'ZXIoe2ltZzonZGVkZW1vbid9KV0pKT09PWZhbHNlKTsKCnJlc2V0KCk7IFcucnVuKCJzaGlwVW5s'
        'b2NrZWQ9MyIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKHtpbWc6J2Rlb3Jpb25yaWdodCd9'
        'KV0pOwpvaygnVmFzdWRhbiBodWxsIG5vdCBvZmZlcmVkIGJ5IGEgVGVycmFuIGhhbmdhcicsIFcu'
        'cnVuKCJzaGlwT2ZmZXJlZCgnZmlob3J1cycpIik9PT1mYWxzZSk7ClcucnVuKCJzaGlwTWVudT10'
        'cnVlOyBzd2FwU2hpcCgnZmlob3J1cycpIik7Cm9rKCdhbmQgYSBmb3JjZWQgc3dpdGNoIGlzIHJl'
        'ZnVzZWQnLCBQKCkuc2hpcD09PSdmaXRvdGgnICYmIFcuZ2V0KCdzaGlwU3dhcFdhdmUnKT09PS0x'
        'KTsKVy5zZXQoJ2FsbGllcycsW2NvbG9zc3VzKCldKTsKb2soJ3RoZSBDb2xvc3N1cyBvZmZlcnMg'
        'dGhlIFZhc3VkYW4gaHVsbCcsIFcucnVuKCJzaGlwT2ZmZXJlZCgnZmlob3J1cycpIik9PT10cnVl'
        'KTsKCnJlc2V0KCk7IFcucnVuKCJzaGlwVW5sb2NrZWQ9MyIpOyBXLnNldCgnYWxsaWVzJyxbZGVz'
        'dHJveWVyKHtpbWc6J2Rlb3Jpb25yaWdodCd9KV0pOwpXLnJ1bigndG9nZ2xlU2hpcE1lbnUoKScp'
        'OyBvaygnVGVycmFuIGhhbmdhciBvbmx5OiB0aGUgbWVudSBzdGF5cyBzaHV0JywgVy5nZXQoJ3No'
        'aXBNZW51Jyk9PT1mYWxzZSk7ClcucnVuKCJzaGlwTWVudT10cnVlOyBkcmF3U2hpcE1lbnUoKSIp'
        'Owpvaygnbm8gY2VsbCBpcyB0YXBwYWJsZSBpbiB0aGF0IHN0YXRlJywgVy5ydW4oJ3dpbmRvdy5f'
        'c2hpcFJlY3RzJykuZXZlcnkocj0+IXIua2V5KSk7Cgpjb25zb2xlLmxvZygnQ29sb3NzdXMgbGlm'
        'dHMgdGhlIG9uY2UgcGVyIHdhdmUgbGltaXQnKTsKcmVzZXQoKTsgVy5ydW4oInNoaXBVbmxvY2tl'
        'ZD0zIik7IFcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoKV0pOwpXLnJ1bigidG9nZ2xlU2hpcE1l'
        'bnUoKTsgc3dhcFNoaXAoJ2ZpaG9ydXMnKSIpOwpvaygnZmlyc3Qgc3dpdGNoIG9mIHRoZSB3YXZl'
        'IHJlZml0cycsIFAoKS5zaGlwPT09J2ZpaG9ydXMnICYmIFAoKS5ocD09PTgwICYmIFAoKS5zaD09'
        'PTEwMCAmJiBQKCkuc2VjQW1tbz09PTIwKTsKb2soJ25vIENvbG9zc3VzOiBzcGVudCBmb3IgdGhp'
        'cyB3YXZlJywgVy5ydW4oJ3NoaXBTd2FwUmVhZHkoKScpPT09ZmFsc2UpOwpXLnNldCgnYWxsaWVz'
        'JyxbZGVzdHJveWVyKCksIGNvbG9zc3VzKCldKTsKb2soJ0NvbG9zc3VzIGFycml2ZXM6IGF2YWls'
        'YWJsZSBhZ2FpbiBpbiB0aGUgc2FtZSB3YXZlJywgVy5ydW4oJ3NoaXBTd2FwUmVhZHkoKScpPT09'
        'dHJ1ZSk7ClcucnVuKCJwbGF5ZXIuaHA9NDA7IHBsYXllci5zaD01MDsgcGxheWVyLnNlY0FtbW89'
        'MTAiKTsKVy5ydW4oInRvZ2dsZVNoaXBNZW51KCk7IHN3YXBTaGlwKCdib29zaXJpcycpIik7Cm9r'
        'KCdzZWNvbmQgc3dpdGNoIGhhcHBlbnMnLCBQKCkuc2hpcD09PSdib29zaXJpcycpOwpvaygnaHVs'
        'bCBjYXJyaWVzIG92ZXIgYXMgYSBmcmFjdGlvbiwgNDAvODAgb2YgMTQwID0gNzAnLCBQKCkuaHA9'
        'PT03MCk7Cm9rKCdzaGllbGRzIGNhcnJ5IG92ZXIsIDUwLzEwMCBvZiAxMDAgPSA1MCcsIFAoKS5z'
        'aD09PTUwKTsKb2soJ2FtbW8gY2FycmllcyBvdmVyLCAxMC8yMCBvZiAxMCBib21icyA9IDUnLCBQ'
        'KCkuc2VjQW1tbz09PTUpOwpvaygnbm8gcmVmaXQ6IG5vdCBmdWxsJywgUCgpLmhwPFAoKS5tYXhI'
        'cCAmJiBQKCkuc2VjQW1tbzxQKCkuc2VjTWF4KTsKCnJlc2V0KCk7IFcucnVuKCJzaGlwVW5sb2Nr'
        'ZWQ9MyIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCksIGNvbG9zc3VzKCldKTsKVy5ydW4o'
        'InRvZ2dsZVNoaXBNZW51KCk7IHN3YXBTaGlwKCdmaWhvcnVzJykiKTsKb2soJ3dpdGggdGhlIENv'
        'bG9zc3VzIHRoZXJlIHRoZSBmaXJzdCBzd2l0Y2ggc3RpbGwgcmVmaXRzJywgUCgpLmhwPT09ODAg'
        'JiYgUCgpLnNlY0FtbW89PT0yMCk7ClcucnVuKCJwbGF5ZXIuaHA9MSIpOwpXLnJ1bigidG9nZ2xl'
        'U2hpcE1lbnUoKTsgc3dhcFNoaXAoJ2Jvb3NpcmlzJykiKTsKb2soJ2EgbmVhcmx5IGRlYWQgaHVs'
        'bCBzdGF5cyBhbGl2ZSBhZnRlciBjYXJyeWluZyBvdmVyJywgUCgpLmhwPj0xICYmIFAoKS5ocDw9'
        'Myk7CgpyZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTMiKTsgVy5zZXQoJ2FsbGllcycsW2Rl'
        'c3Ryb3llcigpLCBjb2xvc3N1cyh7ZGVhZDp0cnVlfSldKTsKVy5ydW4oInRvZ2dsZVNoaXBNZW51'
        'KCk7IHN3YXBTaGlwKCdmaWhvcnVzJykiKTsKb2soJ2RlYWQgQ29sb3NzdXMgZ3JhbnRzIG5vdGhp'
        'bmcnLCBXLnJ1bignc2hpcFN3YXBSZWFkeSgpJyk9PT1mYWxzZSk7CnJlc2V0KCk7IFcucnVuKCJz'
        'aGlwVW5sb2NrZWQ9MyIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCksIGNvbG9zc3VzKHt3'
        'YXJwT3V0OnRydWV9KV0pOwpXLnJ1bigidG9nZ2xlU2hpcE1lbnUoKTsgc3dhcFNoaXAoJ2ZpaG9y'
        'dXMnKSIpOwpvaygnQ29sb3NzdXMgd2FycGluZyBvdXQgZ3JhbnRzIG5vdGhpbmcnLCBXLnJ1bign'
        'c2hpcFN3YXBSZWFkeSgpJyk9PT1mYWxzZSk7CgpyZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2Vk'
        'PTMiKTsgVy5zZXQoJ2FsbGllcycsW2NvbG9zc3VzKCldKTsKVy5ydW4oInRvZ2dsZVNoaXBNZW51'
        'KCk7IHN3YXBTaGlwKCdmaWhvcnVzJykiKTsgVy5ydW4oInBsYXllci5ocD0yMCIpOwpXLnJ1bigi'
        'dG9nZ2xlU2hpcE1lbnUoKTsgc3dhcFNoaXAoJ2ZpdG90aCcpIik7Cm9rKCdiYWNrIG9udG8gdGhl'
        'IHN0YXJ0IGh1bGwgYXQgdGhlIENvbG9zc3VzLCAyMC84MCBvZiAxMDAgPSAyNScsIFAoKS5zaGlw'
        'PT09J2ZpdG90aCcgJiYgUCgpLmhwPT09MjUpOwpXLnJ1bignd2F2ZT0yJyk7Cm9rKCduZXcgd2F2'
        'ZSB3aXRoIHRoZSBDb2xvc3N1cyBzdGlsbCB0aGVyZTogcmVmaXRzIGFnYWluJywgVy5ydW4oJ3No'
        'aXBTd2FwUmVhZHkoKScpPT09dHJ1ZSk7ClcucnVuKCJ0b2dnbGVTaGlwTWVudSgpOyBzd2FwU2hp'
        'cCgnZmlob3J1cycpIik7IG9rKCdhbmQgaXQgaXMgYSBmdWxsIGh1bGwnLCBQKCkuaHA9PT04MCk7'
        'Cgpjb25zb2xlLmxvZygnQ3ljbGVzOiBlYWNoIGJyaW5ncyBpdHMgb3duIGZsZWV0Jyk7CnsKICBj'
        'b25zdCBob2wgPSBXLnJ1bignY3ljbGVBdCgxKScpLCBudGYgPSBXLnJ1bignY3ljbGVBdCgzMSkn'
        'KTsKICBvaygnd2F2ZXMgMSB0byAzMCBhcmUgdGhlIEhhbW1lciBvZiBMaWdodCBjeWNsZScsIFcu'
        'cnVuKCdjeWNsZUF0KDMwKScpPT09aG9sICYmIGhvbC5maXJzdD09PTEpOwogIG9rKCd3YXZlIDMx'
        'IG9wZW5zIHRoZSBOVEYgY3ljbGUsIGFuZCBpdCBob2xkcyBhZnRlciB0aGF0JywgbnRmLmZpcnN0'
        'PT09MzEgJiYgVy5ydW4oJ2N5Y2xlQXQoNTkpJyk9PT1udGYgJiYgVy5ydW4oJ2N5Y2xlQXQoMTQw'
        'KScpPT09bnRmKTsKICByZXNldCgpOwogIFcucnVuKCJzY29yZT05NTAwMDsgZW50ZXJDeWNsZShj'
        'eWNsZUF0KDMxKSkiKTsKICBvaygnZW50ZXJpbmcgaXQgcHV0cyB0aGUgcGxheWVyIGluIGEgTXly'
        'bWlkb24sIGZyZXNoJywgUCgpLnNoaXA9PT0nZmlteXJtaWRvbicgJiYgUCgpLmhwPT09UCgpLm1h'
        'eEhwKTsKICBvaygndGhlIHJvc3RlciBpcyB0aGUgVGVycmFuIG9uZSwgZWlnaHQgaHVsbHMnLAog'
        'ICAgIFcucnVuKCdQTEFZRVJfU0hJUFMubGVuZ3RoJyk9PT04ICYmIFcucnVuKCJQTEFZRVJfU0hJ'
        'UFMuZXZlcnkocz0+cy5mYWM9PT0ndGVycmFuJykiKSk7CiAgb2soJ2luIHRoZSBhZ3JlZWQgb3Jk'
        'ZXInLAogICAgIFcucnVuKCJQTEFZRVJfU0hJUFMubWFwKHM9PnMua2V5KS5qb2luKCkiKT09PSdm'
        'aW15cm1pZG9uLGZpaGVyYyxib2FydGVtaXMsZmloZXJjbWsyLGJvbWVkdXNhLGZpZXJpbnllcyxi'
        'b3Vyc2EsZmlhcmVzJyk7CiAgb2soJ29ubHkgdGhlIGZpcnN0IGh1bGwgaXMgb3BlbicsIFcuZ2V0'
        'KCdzaGlwVW5sb2NrZWQnKT09PTEpOwogIFcucnVuKCJzY29yZT05NTAwMCszOTk5OyB0aWNrU2hp'
        'cFVubG9ja3MoKSIpOwogIG9rKCd0aGUgcG9pbnRzIGJyb3VnaHQgaW50byB0aGUgY3ljbGUgZG8g'
        'bm90IGNvdW50JywgVy5nZXQoJ3NoaXBVbmxvY2tlZCcpPT09MSk7CiAgVy5ydW4oInNjb3JlPTk1'
        'MDAwKzQwMDA7IHRpY2tTaGlwVW5sb2NrcygpIik7CiAgb2soJzQwMDAgcG9pbnRzIHNjb3JlZCBJ'
        'TiB0aGUgY3ljbGUgb3BlbiB0aGUgSGVyY3VsZXMnLCBXLmdldCgnc2hpcFVubG9ja2VkJyk9PT0y'
        'ICYmIC9IRVJDVUxFUy8udGVzdChXLmdldCgnU1VCX01TR1MnKS5zbGljZSgtMSlbMF0udHh0KSk7'
        'CiAgb2soJ3RoZSBUZXJyYW4gc3VwcG9ydCBjb2x1bW4gYW5zd2VycywgdGhlIFZhc3VkYW4gb25l'
        'IGRvZXMgbm90JywKICAgICBXLnJ1bignQUxMWV9GQUNfT04udGVycmFuJyk9PT10cnVlICYmIFcu'
        'cnVuKCdBTExZX0ZBQ19PTi52YXN1ZGFuJyk9PT1mYWxzZSk7CiAgLy8gVGhlIGhhbmdhciBmb2xs'
        'b3dzIHRoZSBodWxsLCBzbyB0aGUgVGVycmFuIHJvc3RlciBuZWVkcyBhIFRlcnJhbiBkZXN0cm95'
        'ZXIuCiAgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3llcih7aW1nOidkZW9yaW9ucmlnaHQnfSldKTsK'
        'ICBvaygnYSBUZXJyYW4gZGVzdHJveWVyIG9mZmVycyB0aGUgSGVyY3VsZXMnLCBXLnJ1bigic2hp'
        'cE9mZmVyZWQoJ2ZpaGVyYycpIik9PT10cnVlICYmIFcucnVuKCdzaGlwU3dhcFJlYWR5KCknKT09'
        'PXRydWUpOwogIFcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoKV0pOwogIG9rKCdhIFZhc3VkYW4g'
        'b25lIGRvZXMgbm90JywgVy5ydW4oInNoaXBPZmZlcmVkKCdmaWhlcmMnKSIpPT09ZmFsc2UgJiYg'
        'Vy5ydW4oJ3NoaXBTd2FwUmVhZHkoKScpPT09ZmFsc2UpOwogIFcucnVuKCJlbnRlckN5Y2xlKGN5'
        'Y2xlQXQoMSkpIik7CiAgb2soJ2FuZCBiYWNrOiB0aGUgVmFzdWRhbiByb3N0ZXIgYW5kIGNvbHVt'
        'bicsIFAoKS5zaGlwPT09J2ZpdG90aCcgJiYKICAgICBXLnJ1bignQUxMWV9GQUNfT04udGVycmFu'
        'Jyk9PT1mYWxzZSAmJiBXLnJ1bignQUxMWV9GQUNfT04udmFzdWRhbicpPT09dHJ1ZSk7Cn0Kb2so'
        'J3RoZSBydW4gc3RhcnRzIGluIHRoZSBjeWNsZSBvZiBpdHMgZmlyc3Qgd2F2ZScsCiAgIC9lbHNl'
        'IGVudGVyQ3ljbGVcKGN5Y2xlQXRcKHdhdmVcKzFcKVwpOy8udGVzdChmbignbGF1bmNoR2FtZScp'
        'KSk7Cm9rKCdjcm9zc2luZyBpbnRvIGEgbmV3IGN5Y2xlIGhhbmRzIG92ZXIgdGhlIGZsZWV0JywK'
        'ICAgL2lmXChfYyE9PWN5Y2xlTm93XCkgZW50ZXJDeWNsZVwoX2NcKTsvLnRlc3QoZm4oJ25leHRX'
        'YXZlJykpKTsKb2soJz9tPSBzdGFydHMgdGhlIHJ1biBhdCB0aGF0IHdhdmUgaW5zdGVhZCBvZiBy'
        'ZXBlYXRpbmcgaXQnLAogICAvU0NSSVBUX09ORVw/U0NSSVBUX09ORS0xOjAvLnRlc3QoZm4oJ2xh'
        'dW5jaEdhbWUnKSkgJiYgIS9TQ1JJUFRfT05FIFw/IFNDUklQVF9PTkUgOiBuLy50ZXN0KHNyYykp'
        'OwoKY29uc29sZS5sb2coJ1N1cHBvcnQgY2FsbHMgYnkgZmFjdGlvbicpOwpvaygndGhlIFRlcnJh'
        'biBjb2x1bW4gaXMgb2ZmIGluIHRoaXMgY3ljbGUnLCBzcmMuaW5jbHVkZXMoImNvbnN0IEFMTFlf'
        'RkFDX09OID0ge3RlcnJhbjpmYWxzZSwgdmFzdWRhbjp0cnVlLCBndHZhOnRydWV9OyIpKTsKb2so'
        'J3RoZSBjYWxsIGlzIGdhdGVkIGluc2lkZSBjYWxsQWxseSwgbm90IG9ubHkgaW4gdGhlIG1lbnUn'
        'LAogICAvZnVuY3Rpb24gY2FsbEFsbHlcKGlkXClce1tcc1xTXXswLDQwMH1hbGx5RmFjT25cKGNk'
        'ZWZcLmZhY1wpLy50ZXN0KHNyYykpOwpvaygndGhlIG1lbnUgbm8gbG9uZ2VyIHVzZXMgdGhlIGZp'
        'eGVkIHR3byBjb2x1bW4gc3BsaXQnLCAhc3JjLmluY2x1ZGVzKCdBTExZX1RFUl9OPzA6MScpKTsK'
        'b2soJ3RoZSBDb2xvc3N1cyBpcyBhIEdUVkEgc2hpcCBub3cnLCAvY29sb3NzdXM6XHMqXHtjbHM6'
        'J2Rlc3Ryb3llcicsIGZhYzonZ3R2YScvLnRlc3Qoc3JjKSk7Cgpjb25zb2xlLmxvZygnSHVsbCBw'
        'aWN0dXJlcyBpbiB0aGVpciBvd24gY2VsbCcpOwpjb25zdCBJTUcgPSAodyxoKT0+KHt3aWR0aDp3'
        'LCBoZWlnaHQ6aH0pOwpjb25zdCBBTExfSU1HUyA9IHtmaXRvdGg6SU1HKDEyMCw5MCksIGZpaG9y'
        'dXM6SU1HKDEyMCw5MCksIGJvb3NpcmlzOklNRygxNTAsMTEwKSwKICAgICAgICAgICAgICAgICAg'
        'ZmlzZXJhcGlzOklNRygxMjAsOTApLCBmaXNldGg6SU1HKDEyMCw5MCksIGJvYmFraGE6SU1HKDE1'
        'MCwxMTApLAogICAgICAgICAgICAgICAgICBmaXRhdXJldDpJTUcoMTIwLDkwKSwgYm9zZWtobWV0'
        'OklNRygxNTAsMTEwKX07CmNvbnN0IFBJQ1cgPSBXLnJ1bignSEdfUElDX1cnKSwgUElDSCA9IFcu'
        'cnVuKCdIR19ST1cnKS02OwpyZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTgiKTsgVy5zZXQo'
        'J2FsbGllcycsW2Rlc3Ryb3llcigpXSk7IFcucnVuKCd0b2dnbGVTaGlwTWVudSgpJyk7Clcuc2V0'
        'KCdJTUdTJywge30pOwpDTFIoKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7Cm9rKCdub3RoaW5n'
        'IGxvYWRlZCB5ZXQ6IG5vIHBpY3R1cmUsIG5vIGNyYXNoLCByb3dzIHN0aWxsIHRoZXJlJywKICAg'
        'ZHJhd3MoKS5sZW5ndGg9PT0wICYmIFcucnVuKCd3aW5kb3cuX3NoaXBSZWN0cycpLmxlbmd0aD09'
        'PTgpOwpXLnNldCgnSU1HUycsIEFMTF9JTUdTKTsKQ0xSKCk7IFcucnVuKCdkcmF3U2hpcE1lbnUo'
        'KScpOwpvaygnb25lIGh1bGwgZHJhd24gcGVyIG9wZW4gcm93JywgZHJhd3MoKS5sZW5ndGg9PT04'
        'KTsKLy8gVGhlIGdsb3NzIG9uIGVhY2ggcGxhdGUgY2xpcHMgYXMgd2VsbCwgc28gdGhpcyBjb3Vu'
        'dHMgYXQgbGVhc3Qgb25lIGNsaXAKLy8gcGVyIHBpY3R1cmUgcmF0aGVyIHRoYW4gZXhhY3RseSBv'
        'bmUgaW4gdG90YWwuCm9rKCdlYWNoIG9uZSBjbGlwcGVkIHRvIGl0cyBvd24gY2VsbCBmaXJzdCcs'
        'IGNsaXBzKCkubGVuZ3RoPj04KTsKb2soJ2VhY2ggb25lIGZpdHMgaW5zaWRlIHRoZSBwaWN0dXJl'
        'IGNlbGwnLAogICBkcmF3cygpLmV2ZXJ5KGQ9PmQuYXJnc1szXTw9UElDVy01ICYmIGQuYXJnc1s0'
        'XTw9UElDSC01ICYmIGQuYXJnc1szXT4wICYmIGQuYXJnc1s0XT4wKSk7Cm9rKCdhc3BlY3QgcmF0'
        'aW8ga2VwdCcsIGRyYXdzKCkuZXZlcnkoZD0+TWF0aC5hYnMoKGQuYXJnc1szXS9kLmFyZ3NbNF0p'
        'IC0gKDEyMC85MCkpPDAuMDEKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICB8'
        'fCBNYXRoLmFicygoZC5hcmdzWzNdL2QuYXJnc1s0XSkgLSAoMTUwLzExMCkpPDAuMDEpKTsKb2so'
        'J3NhdmUgYW5kIHJlc3RvcmUgc3RheSBiYWxhbmNlZCwgbm8gbGVha2luZyBjbGlwIG9yIGFscGhh'
        'JywgYmFsYW5jZWQoKSk7Cm9rKCdhIHBpY3R1cmUgaXMgYSBwaWN0dXJlIG5vdywgbm90IGEgd2F0'
        'ZXJtYXJrJywgYWxwaGFzKCkuZXZlcnkoYT0+YT4wLjkgJiYgYTw9MSkpOwp7CiAgLy8gVGhyZWUg'
        'b3BlbiwgZml2ZSBsb2NrZWQ6IGEgbG9ja2VkIGh1bGwgaGFzIG5vIHJvdyB0YWxsIGVub3VnaCBm'
        'b3IgYQogIC8vIHBpY3R1cmUsIHNvIGl0IGdldHMgbm9uZSBhdCBhbGwuCiAgcmVzZXQoKTsgVy5y'
        'dW4oInNoaXBVbmxvY2tlZD0zIik7IFcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoKV0pOyBXLnJ1'
        'bigndG9nZ2xlU2hpcE1lbnUoKScpOwogIFcuc2V0KCdJTUdTJywgQUxMX0lNR1MpOyBDTFIoKTsg'
        'Vy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7CiAgb2soJ2EgbG9ja2VkIGh1bGwgc2hvd3Mgbm8gcGlj'
        'dHVyZScsIGRyYXdzKCkubGVuZ3RoPT09Myk7Cn0KcmVzZXQoKTsgVy5ydW4oInNoaXBVbmxvY2tl'
        'ZD04Iik7IFcuc2V0KCdhbGxpZXMnLFtkZXN0cm95ZXIoKV0pOyBXLnJ1bigndG9nZ2xlU2hpcE1l'
        'bnUoKScpOwpXLnNldCgnSU1HUycsIHtmaXRvdGg6SU1HKDAsMCl9KTsKQ0xSKCk7IFcucnVuKCdk'
        'cmF3U2hpcE1lbnUoKScpOwpvaygnYSB6ZXJvIHNpemVkIHNwcml0ZSBpcyBza2lwcGVkIGluc3Rl'
        'YWQgb2YgZGl2aWRpbmcgYnkgemVybycsIGRyYXdzKCkubGVuZ3RoPT09MCk7Clcuc2V0KCdJTUdT'
        'Jywge30pOwoKY29uc29sZS5sb2coJ0JhcnJlbHMgYW5kIHZvbGxleSBkYW1hZ2UsIGluIHRoZWly'
        'IG93biBjb2x1bW5zJyk7CmNvbnN0IHRleHRzID0gKCk9PiBDQUxMUy5maWx0ZXIoYz0+Yy5mbj09'
        'PSdmaWxsVGV4dCcpLm1hcChjPT4oe3M6U3RyaW5nKGMuYXJnc1swXSksIHg6Yy5hcmdzWzFdLCB5'
        'OmMuYXJnc1syXX0pKTsKLy8gQSBjb2x1bW4gaXMgY2hlY2tlZCBieSB3aGVyZSBpdCBhY3R1YWxs'
        'eSBsYW5kczogdGhlIHggb2YgdGhlIGNvbHVtbiBpbiB0aGUKLy8gbGF5b3V0LCBhZGRlZCB0byB0'
        'aGUgeCBvZiBhIHJvdyB0aGUgbWVudSBpdHNlbGYgcmVwb3J0ZWQuCmNvbnN0IGNvbFggPSAoayk9'
        'PiBXLnJ1bignSEdfQ09MUycpLmZpbmQoYz0+Yy5rPT09aykueDsKLy8gVGhlIGNvbHVtbiB0aXRs'
        'ZXMgc2l0IG9uIHRoZSBzYW1lIHgsIHNvIGEgdmFsdWUgb25seSBjb3VudHMgd2hlbiBpdCBhbHNv'
        'Ci8vIHNpdHMgaW5zaWRlIGEgcm93Lgpjb25zdCBpbkNvbCA9IChrKT0+ewogIGNvbnN0IHgwID0g'
        'Y29sWChrKSwgcnMgPSBXLnJ1bignd2luZG93Ll9zaGlwUmVjdHMnKTsKICByZXR1cm4gdGV4dHMo'
        'KS5maWx0ZXIodD0+IHJzLnNvbWUocj0+IHQueCA9PT0gci54ICsgeDAgJiYgdC55ID49IHIueSAm'
        'JiB0LnkgPD0gci55ICsgci5oKSk7Cn07CnJlc2V0KCk7IFcucnVuKCJzaGlwVW5sb2NrZWQ9OCIp'
        'OyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsgVy5ydW4oJ3RvZ2dsZVNoaXBNZW51KCkn'
        'KTsKVy5zZXQoJ01PVU5UUycsIHt9KTsKQ0xSKCk7IFcucnVuKCdkcmF3U2hpcE1lbnUoKScpOwpv'
        'aygnbm8gbW91bnQgZGF0YTogbm8gY2xhaW0gYWJvdXQgZ3VucyBvciB2b2xsZXkgYXQgYWxsJywK'
        'ICAgaW5Db2woJ2d1bnMnKS5sZW5ndGg9PT0wICYmIGluQ29sKCd2b2xsZXknKS5sZW5ndGg9PT0w'
        'KTsKVy5zZXQoJ01PVU5UUycsIHtmaXRvdGg6e3ByaW1hcnk6WzEsMV19LCBmaWhvcnVzOntwcmlt'
        'YXJ5OlsxLDFdfSwgYm9vc2lyaXM6e3ByaW1hcnk6WzEsMV19LAogICAgICAgICAgICAgICAgIGZp'
        'c2VyYXBpczp7cHJpbWFyeTpbMSwxXX0sIGZpc2V0aDp7cHJpbWFyeTpbMSwxXX0sIGJvYmFraGE6'
        'e3ByaW1hcnk6WzEsMV19LAogICAgICAgICAgICAgICAgIGZpdGF1cmV0OntwcmltYXJ5OlsxLDEs'
        'MV19LCBib3Nla2htZXQ6e3ByaW1hcnk6WzEsMV19fSk7CkNMUigpOyBXLnJ1bignZHJhd1NoaXBN'
        'ZW51KCknKTsKb2soJ2EgZmlndXJlIG9uIGV2ZXJ5IG9uZSBvZiB0aGUgZWlnaHQgcm93cycsCiAg'
        'IGluQ29sKCdndW5zJykubGVuZ3RoPT09OCAmJiBpbkNvbCgndm9sbGV5JykubGVuZ3RoPT09OCk7'
        'Cm9rKCd0aGUgc2V2ZW4gdHdvIGJhcnJlbCBodWxscyByZWFkIDIgYW5kIDUxJywKICAgaW5Db2wo'
        'J2d1bnMnKS5maWx0ZXIodD0+dC5zPT09JzInKS5sZW5ndGg9PT03ICYmCiAgIGluQ29sKCd2b2xs'
        'ZXknKS5maWx0ZXIodD0+dC5zPT09JzUxJykubGVuZ3RoPT09Nyk7Cm9rKCd0aGUgVGF1cmV0IHJl'
        'YWRzIDMgYW5kIDU3JywKICAgaW5Db2woJ2d1bnMnKS5maWx0ZXIodD0+dC5zPT09JzMnKS5sZW5n'
        'dGg9PT0xICYmCiAgIGluQ29sKCd2b2xsZXknKS5maWx0ZXIodD0+dC5zPT09JzU3JykubGVuZ3Ro'
        'PT09MSk7Cm9rKCd0aGUgZmlndXJlIG1hdGNoZXMgd2hhdCB2b2xsZXlEbWcgYWN0dWFsbHkgZG9l'
        'cycsCiAgIE1hdGgucm91bmQoVy5ydW4oJ3ZvbGxleVRvdGFsKDIpJykpPT09NTEgJiYgTWF0aC5y'
        'b3VuZChXLnJ1bigndm9sbGV5VG90YWwoMyknKSk9PT01NwogICAmJiBNYXRoLnJvdW5kKFcucnVu'
        'KCd2b2xsZXlUb3RhbCgxKScpKT09PTQ0KTsKb2soJ29uZSBiYXJyZWwgaXMgdGhlIGZhbGxiYWNr'
        'IG9mIHRoZSBmb3JtdWxhLCBub3QgYSBjcmFzaCcsIFcucnVuKCd2b2xsZXlUb3RhbCgwKScpPT09'
        'NDQpOwp7CiAgLy8gVGhlIHBvaW50IG9mIHRoZSBjb2x1bW5zOiBodWxsIHNpdHMgdW5kZXIgaHVs'
        'bCBvbiBldmVyeSByb3cuCiAgY29uc3QgaHVsbHMgPSBpbkNvbCgnaHVsbCcpLm1hcCh0PT50LnMp'
        'LmpvaW4oKTsKICBvaygndGhlIGh1bGwgY29sdW1uIHJlYWRzIGRvd24gdGhlIGxpc3QgaW4gb3Jk'
        'ZXInLCBodWxscz09PScxMDAsODAsODAsMTI1LDEwMCwxNDAsMTAwLDE0MCcpOwogIGNvbnN0IHNo'
        'aWVsZHMgPSBpbkNvbCgnc2hpZWxkJykubWFwKHQ9PnQucykuam9pbigpOwogIG9rKCd0aGUgc2hp'
        'ZWxkIGNvbHVtbiB0b28nLCBzaGllbGRzPT09JzEwMCwxMDAsNzAsMTMwLDEzMCwxMDAsMTAwLDEz'
        'MCcpOwogIG9rKCdldmVyeSB2YWx1ZSBpbiBhIGNvbHVtbiBzaGFyZXMgb25lIHgnLAogICAgIG5l'
        'dyBTZXQoaW5Db2woJ2h1bGwnKS5tYXAodD0+dC54KSkuc2l6ZT09PTEpOwp9CnsKICAvLyBUd28g'
        'dW5sb2NrZWQgb2YgZWlnaHQ6IHRoZSBtZW51IG5lZWRzIHR3byB0byBvcGVuIGF0IGFsbC4KICBy'
        'ZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTIiKTsgVy5zZXQoJ2FsbGllcycsW2Rlc3Ryb3ll'
        'cigpXSk7CiAgVy5zZXQoJ01PVU5UUycsIHtmaXRvdGg6e3ByaW1hcnk6WzEsMV19LCBmaWhvcnVz'
        'OntwcmltYXJ5OlsxLDFdfSwgZml0YXVyZXQ6e3ByaW1hcnk6WzEsMSwxXX19KTsKICBXLnJ1bign'
        'dG9nZ2xlU2hpcE1lbnUoKScpOyBDTFIoKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7CiAgb2so'
        'J29ubHkgdGhlIHR3byB1bmxvY2tlZCByb3dzIG1ha2UgYSBjbGFpbScsIGluQ29sKCdndW5zJyku'
        'bGVuZ3RoPT09Mik7CiAgb2soJ3RoZSBsb2NrZWQgVGF1cmV0IHN0YXlzIHNpbGVudCBldmVuIHdp'
        'dGggbW91bnQgZGF0YScsCiAgICAgaW5Db2woJ3ZvbGxleScpLmV2ZXJ5KHQ9PnQucyE9PSc1Nycp'
        'KTsKfQpXLnNldCgnTU9VTlRTJywge30pOwoKY29uc29sZS5sb2coJ09uZSBsb29rLCBhbmQgaXQg'
        'aXMgdGhlIGZvcnVtIG9uZScpOwpyZXNldCgpOyBXLnJ1bigic2hpcFVubG9ja2VkPTMiKTsgVy5z'
        'ZXQoJ2FsbGllcycsW2Rlc3Ryb3llcigpXSk7IFcucnVuKCd0b2dnbGVTaGlwTWVudSgpJyk7CkNM'
        'UigpOyBXLnJ1bignZHJhd1NoaXBNZW51KCknKTsKY29uc3QgaGxwRm9udHMgPSBDQUxMUy5maWx0'
        'ZXIoYz0+Yy5mbj09PSdzZXQgZm9udCcpLm1hcChjPT5TdHJpbmcoYy5hcmdzWzBdKSk7CmNvbnN0'
        'IGhscENlbGxzID0gVy5ydW4oJ3dpbmRvdy5fc2hpcFJlY3RzJykubWFwKHI9PnIueCsnLCcrci55'
        'KycsJytyLncrJywnK3IuaCkuam9pbignfCcpOwpvaygnbm8gQ291cmllciBsZWZ0IGluIHRoZSBo'
        'YW5nYXInLCBobHBGb250cy5ldmVyeShmPT5mLmluZGV4T2YoJ0NvdXJpZXInKTwwKSk7Cm9rKCdp'
        'dCB1c2VzIHRoZSBmb3J1bSBmYWNlcycsIGhscEZvbnRzLnNvbWUoZj0+Zi5pbmRleE9mKCdUYWhv'
        'bWEnKT49MCkgJiYgaGxwRm9udHMuc29tZShmPT5mLmluZGV4T2YoJ1NlZ29lIFVJJyk+PTApKTsK'
        'b2soJ3ZhbHVlcyBhcmUgbm8gbG9uZ2VyIHNldCBpbiA4IGFuZCA5IHBpeGVscycsCiAgIGhscEZv'
        'bnRzLmZpbHRlcihmPT4vU2Vnb2UgVUkvLnRlc3QoZikpLnNvbWUoZj0+LzFbNC05XXB4Ly50ZXN0'
        'KGYpKSk7Cm9rKCd0aGUgYWN0aXZlIHJvdyBnZXRzIGEgZ2xvdyByaW5nJywgQ0FMTFMuc29tZShj'
        'PT5jLmZuPT09J3NldCBzaGFkb3dCbHVyJykpOwpvaygnbm8gcmluZyBsZWFrcyBvdXQgb2YgaXRz'
        'IHNhdmUvcmVzdG9yZScsIGJhbGFuY2VkKCkpOwpvaygnbm90aGluZyBjaG9vc2VzIGJldHdlZW4g'
        'dHdvIGxvb2tzIGFueSBtb3JlJywgIS9FQ09cXC5odWQvLnRlc3Qoc3JjKSk7ClcucnVuKCJFQ08u'
        'c2NoZW1lPSd2b2lkJyIpOyBDTFIoKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7Cm9rKCd0aGUg'
        'aGFuZ2FyIGRyYXdzIGluIFZvaWQgdG9vJywgQ0FMTFMubGVuZ3RoPjUwKTsKb2soJ2FuZCB0aGUg'
        'cm93cyBkaWQgbm90IG1vdmUnLAogICBXLnJ1bignd2luZG93Ll9zaGlwUmVjdHMnKS5tYXAocj0+'
        'ci54KycsJytyLnkrJywnK3IudysnLCcrci5oKS5qb2luKCd8Jyk9PT1obHBDZWxscyk7ClcucnVu'
        'KCJFQ08uc2NoZW1lPSdmaXJlJyIpOwoKY29uc29sZS5sb2coJ0V2ZXJ5dGhpbmcgaXMgZHJhd24g'
        'ZnJvbSB0aGUgc3VyZmFjZSBraXQnKTsKewogIHJlc2V0KCk7IFcucnVuKCJzaGlwVW5sb2NrZWQ9'
        'OCIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsgVy5ydW4oJ3RvZ2dsZVNoaXBNZW51'
        'KCknKTsKICBDTFIoKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgpJyk7CiAgLy8gR3JhZGllbnRzIGFy'
        'ZSBhbGxvd2VkIGFnYWluLCBidXQgb25seSBhcyBnbG9zczogYSBzaG9ydCBmYWxsIG9mIGxpZ2h0'
        'CiAgLy8gb3ZlciB0aGUgdG9wIG9mIGEgcGxhdGUuIE5vbmUgbWF5IHJ1biB0aGUgaGVpZ2h0IG9m'
        'IGEgcGFuZWwgdGhlIHdheSB0aGUKICAvLyBvbGQgYm94IGdyYWRpZW50IGRpZC4KICBjb25zdCBn'
        'cmFkcyA9IENBTExTLmZpbHRlcihjPT5jLmZuPT09J2NyZWF0ZUxpbmVhckdyYWRpZW50Jyk7CiAg'
        'b2soJ2V2ZXJ5IGdyYWRpZW50IGlzIGEgZ2xvc3MsIG5vdCBhIGZ1bGwgaGVpZ2h0IGZpbGwnLAog'
        'ICAgIGdyYWRzLmxlbmd0aD4wICYmIGdyYWRzLmV2ZXJ5KGc9PihnLmFyZ3NbM10tZy5hcmdzWzFd'
        'KTw9MjAwKSk7CiAgLy8gQSBjaGFtZmVyZWQgb3V0bGluZSBpcyBzaXggY29ybmVycy4gQSByZWN0'
        'YW5nbGUgd291bGQgYmUgZm91ci4KICBjb25zdCBjbG9zZXMgPSBDQUxMUy5maWx0ZXIoYz0+Yy5m'
        'bj09PSdjbG9zZVBhdGgnKS5sZW5ndGg7CiAgb2soJ3RoZSBwYW5lbCBhbmQgZXZlcnkgcGxhdGUg'
        'YXJlIGNoYW1mZXJlZCwgbm90IHJlY3RhbmdsZXMnLCBjbG9zZXM+PTkpOwogIG9rKCdvbmUgc2Nh'
        'bGUgdW5kZXIgZWFjaCBvZiB0aGUgdHdvIGdyb3VwIGhlYWRpbmdzJywKICAgICBDQUxMUy5maWx0'
        'ZXIoYz0+Yy5mbj09PSdzZXQgbGluZVdpZHRoJyAmJiBjLmFyZ3NbMF09PT0xKS5sZW5ndGg+MCAm'
        'JiBjbG9zZXM+PTkpOwogIG9rKCdhIHJpbmcgaXMgZHJhd24sIGFuZCBvbmx5IGFyb3VuZCB0aGUg'
        'YWN0aXZlIHJvdycsCiAgICAgQ0FMTFMuZmlsdGVyKGM9PmMuZm49PT0nc2V0IHNoYWRvd0JsdXIn'
        'ICYmIGMuYXJnc1swXT09PTYpLmxlbmd0aD09PTIpOwogIG9rKCdub3RoaW5nIGxlYWtzIG91dCBv'
        'ZiBhIHNhdmUvcmVzdG9yZScsIGJhbGFuY2VkKCkpOwp9CnsKICAvLyBUaGUga2l0IGlzIHNoYXJl'
        'ZCwgc28gdGhlIGhhbmdhciBtdXN0IG5vdCByZWFjaCBwYXN0IGl0IGZvciBhIHNoYXBlIG9mCiAg'
        'Ly8gaXRzIG93bi4gdGhCZXZlbCBhbmQgdGhQYW5lbCBiZWxvbmcgdG8gdGhlIHNjcmVlbnMgbm90'
        'IHlldCByZWJ1aWx0LgogIGNvbnN0IGEgPSBzcmMuaW5kZXhPZignZnVuY3Rpb24gZHJhd1NoaXBN'
        'ZW51KCknKTsKICBjb25zdCBib2R5ID0gc3JjLnNsaWNlKGEsIHNyYy5pbmRleE9mKCdmdW5jdGlv'
        'biBkcmF3Q2FsbE1lbnUoKScpKTsKICBvaygndGhlIGhhbmdhciB1c2VzIG5vIGJldmVsIGFuZCBu'
        'byBncmFkaWVudCBwYW5lbCcsCiAgICAgYm9keS5pbmRleE9mKCd0aEJldmVsJyk8MCAmJiBib2R5'
        'LmluZGV4T2YoJ3RoUGFuZWwnKTwwKTsKICBvaygnYW5kIG5vIGRpYWxvZyBmcmFtZSBvZiBpdHMg'
        'b3duJywgYm9keS5pbmRleE9mKCd1aURpYWxvZycpPDApOwp9CnsKICAvLyBUaGUgZGlnaXQgaXMg'
        'dGhlIGtleWJvYXJkIHNob3J0Y3V0LCBzbyBpdCBoYXMgdG8gZm9sbG93IHRoZSBodWxsIHRocm91'
        'Z2gKICAvLyB0aGUgcmVncm91cGluZyByYXRoZXIgdGhhbiBjb3VudCByb3dzLgogIHJlc2V0KCk7'
        'IFcucnVuKCJzaGlwVW5sb2NrZWQ9OCIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsg'
        'Vy5ydW4oJ3RvZ2dsZVNoaXBNZW51KCknKTsKICBDTFIoKTsgVy5ydW4oJ2RyYXdTaGlwTWVudSgp'
        'Jyk7CiAgY29uc3QgcnMgPSBXLnJ1bignd2luZG93Ll9zaGlwUmVjdHMnKTsKICBjb25zdCBjaGlw'
        'WCA9IFcucnVuKCdIR19OVU0nKSArIFcucnVuKCdIR19OVU1fVycpLzI7CiAgY29uc3QgY2hpcCA9'
        'IChrZXkpPT57IGNvbnN0IHI9cnMuZmluZChyPT5yLnNoaXA9PT1rZXkpOwogICAgcmV0dXJuIHRl'
        'eHRzKCkuZmluZCh0PT4gdC54PT09ci54K2NoaXBYICYmIHQueT49ci55ICYmIHQueTw9ci55K3Iu'
        'aCk7IH07CiAgb2soJ3RoZSBPc2lyaXMgc2hvd3MgNjogZmlyc3QgYm9tYmVyLCBzaXh0aCByb3cn'
        'LAogICAgIGNoaXAoJ2Jvb3NpcmlzJykgJiYgY2hpcCgnYm9vc2lyaXMnKS5zPT09JzYnKTsKICBv'
        'aygnYW5kIHRoZSBCYWtoYSBzaG93cyA3JywgY2hpcCgnYm9iYWtoYScpICYmIGNoaXAoJ2JvYmFr'
        'aGEnKS5zPT09JzcnKTsKICBvaygndGhlIGRpZ2l0cyBydW4gMSB0byA4IHN0cmFpZ2h0IGRvd24g'
        'dGhlIHBhbmVsJywKICAgICBycy5tYXAocj0+Y2hpcChyLnNoaXApLnMpLmpvaW4oKT09PScxLDIs'
        'Myw0LDUsNiw3LDgnKTsKfQoKY29uc29sZS5sb2coJ1RoZSBwYW5lbCBncm93cyB3aXRoIHdoYXQg'
        'aXMgb3BlbicpOwp7CiAgY29uc3QgaGVpZ2h0ID0gKCk9PnsgY29uc3Qgcj1XLnJ1bignd2luZG93'
        'Ll9zaGlwUmVjdHMnKTsgcmV0dXJuIHJbci5sZW5ndGgtMV0ueStyW3IubGVuZ3RoLTFdLmggLSBy'
        'WzBdLnk7IH07CiAgcmVzZXQoKTsgVy5ydW4oInNoaXBVbmxvY2tlZD0yIik7IFcuc2V0KCdhbGxp'
        'ZXMnLFtkZXN0cm95ZXIoKV0pOyBXLnJ1bigndG9nZ2xlU2hpcE1lbnUoKTsgZHJhd1NoaXBNZW51'
        'KCknKTsKICBjb25zdCBzbWFsbCA9IGhlaWdodCgpOwogIHJlc2V0KCk7IFcucnVuKCJzaGlwVW5s'
        'b2NrZWQ9OCIpOyBXLnNldCgnYWxsaWVzJyxbZGVzdHJveWVyKCldKTsgVy5ydW4oJ3RvZ2dsZVNo'
        'aXBNZW51KCk7IGRyYXdTaGlwTWVudSgpJyk7CiAgY29uc3QgYmlnID0gaGVpZ2h0KCk7CiAgb2so'
        'J2VpZ2h0IG9wZW4gaHVsbHMgbmVlZCBtb3JlIHJvb20gdGhhbiB0d28nLCBiaWcgPiBzbWFsbCk7'
        'CiAgb2soJ2FuZCBpdCBzdGlsbCBmaXRzIG9uIHRoZSBmaWVsZCcsCiAgICAgVy5ydW4oJ3dpbmRv'
        'dy5fc2hpcFJlY3RzJykuZXZlcnkocj0+ci55Pj0wICYmIHIueStyLmg8PTUwMCkpOwp9Cgpjb25z'
        'b2xlLmxvZygnUmVhcm0gbmVlZHMgYSBjb3J2ZXR0ZSwgbm90IGFueSBzaGlwIGF0IGFsbCcpOwp7'
        'CiAgY29uc3QgY29ydmV0dGUgPSAoKT0+KHt0eXBlOidjb3J2ZXR0ZScsIHNpZGU6J2FsbHknLCBk'
        'ZWFkOmZhbHNlLCB3YXJwT3V0OjAsIHdhcnA6MH0pOwogIHJlc2V0KCk7IFcuc2V0KCdhbGxpZXMn'
        'LCBbXSk7CiAgb2soJ25vdGhpbmcgb24gdGhlIGZpZWxkLCBubyByZWFybScsIFcucnVuKCdyZWFy'
        'bVJlYWR5KCknKT09PWZhbHNlKTsKICBXLnNldCgnYWxsaWVzJywgW2Rlc3Ryb3llcigpXSk7CiAg'
        'b2soJ2EgZGVzdHJveWVyIGlzIGEgaGFuZ2FyLCBub3QgYW4gYXJtb3VyeScsIFcucnVuKCdyZWFy'
        'bVJlYWR5KCknKT09PWZhbHNlKTsKICBXLnNldCgnYWxsaWVzJywgW2NvcnZldHRlKCldKTsKICBv'
        'aygnYSBjb3J2ZXR0ZSBvcGVucyBpdCcsIFcucnVuKCdyZWFybVJlYWR5KCknKT09PXRydWUpOwog'
        'IGNvbnN0IHdhcnBpbmcgPSBjb3J2ZXR0ZSgpOyB3YXJwaW5nLndhcnAgPSA0MDsKICBXLnNldCgn'
        'YWxsaWVzJywgW3dhcnBpbmddKTsKICBvaygnb25lIHN0aWxsIGNvbWluZyBvdXQgb2YgdGhlIHZv'
        'cnRleCBkb2VzIG5vdCcsIFcucnVuKCdyZWFybVJlYWR5KCknKT09PWZhbHNlKTsKICBjb25zdCBk'
        'ZWFkID0gY29ydmV0dGUoKTsgZGVhZC5kZWFkID0gdHJ1ZTsKICBXLnNldCgnYWxsaWVzJywgW2Rl'
        'YWRdKTsKICBvaygnbm9yIGRvZXMgYSB3cmVjaycsIFcucnVuKCdyZWFybVJlYWR5KCknKT09PWZh'
        'bHNlKTsKICBXLnNldCgnYWxsaWVzJywgW2NvcnZldHRlKCldKTsKICBXLnNldCgnYWxsaWVzJywg'
        'W2NvcnZldHRlKCldKTsgICAvLyBhIGxpdmUgb25lIGFnYWluLCBhZnRlciB0aGUgd3JlY2sgYWJv'
        'dmUKICBXLnJ1bignY2xlYXJSZXN1bWVIb2xkKCknKTsgICAgICAvLyBhbmQgbm8gaG9sZCBsZWZ0'
        'IG92ZXIgZnJvbSBlYXJsaWVyCiAgLy8gUHJlc3MgdGhlIHJlY3RhbmdsZSB0aGUgYmFyIHJlcG9y'
        'dHMsIHRoZSB3YXkgYSBwbGF5ZXIgZG9lcy4gQ2FsbGluZwogIC8vIHRvZ2dsZVJlYXJtTWVudSgp'
        'IGhlcmUgdGVzdGVkIHRoZSBwYW5lbCBhbmQgbm90IHRoZSBidXR0b24sIHdoaWNoIGlzIGhvdwog'
        'IC8vIGEgYnV0dG9uIHRoYXQgd2FzIG5ldmVyIHdpcmVkIHRvIGFueXRoaW5nIHBhc3NlZC4KICAv'
        'LyBDbGVhciB0aGUgc2hpcCBidXR0b24gZmlyc3Q6IGFuIGVhcmxpZXIgY2FzZSBsZWZ0IGEgcmVj'
        'dGFuZ2xlIHN0YW5kaW5nCiAgLy8gdGhhdCBjb3ZlcnMgdGhpcyBzcG90LCBhbmQgcG9pbnRlckNv'
        'bnN1bWVkIGFza3MgYWJvdXQgaXQgb25lIGxpbmUgc29vbmVyLgogIFcucnVuKCJ3aW5kb3cuX3No'
        'aXBCdG5SZWN0PW51bGw7IHdpbmRvdy5fcmVhcm1CdG5SZWN0PXt4OjcwOSx5OjQsdzoyMixoOjQ2'
        'fTsiCiAgICAgICsgIiBwb2ludGVyQ29uc3VtZWQoe3g6NzE0LHk6MTJ9KSIpOwogIG9rKCdwcmVz'
        'c2luZyB0aGUgYnV0dG9uIGluIHRoZSBiYXIgb3BlbnMgdGhlIHBhbmVsJywgVy5nZXQoJ3JlYXJt'
        'TWVudScpPT09dHJ1ZSk7CiAgVy5ydW4oInBvaW50ZXJDb25zdW1lZCh7eDo3MTQseToxMn0pIik7'
        'CiAgb2soJ2FuZCBwcmVzc2luZyBpdCBhZ2FpbiBjbG9zZXMgaXQnLCBXLmdldCgncmVhcm1NZW51'
        'Jyk9PT1mYWxzZSk7CiAgVy5ydW4oJ3NldFJlYXJtTWVudShmYWxzZSknKTsKfQoKY29uc29sZS5s'
        'b2coJ1RoZSBzdGFuZGFyZCBmaXQgaXMgcHJvdmFibHkgdGhlIGd1biB0aGUgZ2FtZSBoYWQnKTsK'
        'ewogIGNvbnN0IHAgPSBXLnJ1bigicHJpRGVmKCdwcm9tZXRoZXVzJykiKTsKICBvaygndGhlIFBy'
        'b21ldGhldXMgY2FycmllcyBubyBmYWN0b3JzIGF0IGFsbCcsIHAuZG1nPT09MSAmJiBwLnJhdGU9'
        'PT0xKTsKICBvaygnYW5kIG5vIGxpbWl0IG9uIGl0cyByZWFjaCcsIHAucmFuZ2U9PT0wKTsKICBy'
        'ZXNldCgpOyBXLnJ1bigicGxheWVyLnByaT0ncHJvbWV0aGV1cyc7IGFwcGx5TG9hZG91dCgpIik7'
        'CiAgb2soJ3NvIHRoZSByYXRlIG9mIGZpcmUgaXMgdGhlIG9sZCAyOCBzdGVwcycsIFcuZ2V0KCdw'
        'bGF5ZXInKS5mUj09PTI4KTsKICBjb25zdCBtID0gVy5ydW4oInNlY0RlZignbXg2NCcpIik7CiAg'
        'b2soJ3RoZSBNWC02NCBpcyB0aGUgb2xkIG1pc3NpbGUsIHRvIHRoZSBudW1iZXInLAogICAgIG0u'
        'ZG1nPT09MzUgJiYgbS5jZD09PTQ1ICYmIG0uc3BkPT09My41ICYmIG0ubGlmZT09PTIyMCAmJiBt'
        'LmhvbWluZz09PXRydWUpOwogIGNvbnN0IGMgPSBXLnJ1bigic2VjRGVmKCdjeWNsb3BzJykiKTsK'
        'ICBvaygnYW5kIHRoZSBDeWNsb3BzIHRoZSBvbGQgYm9tYicsCiAgICAgYy5kbWc9PT04MCAmJiBj'
        'LmNkPT09OTAgJiYgYy5zcGQ9PT0xLjUgJiYgYy5saWZlPT09MzAwKTsKfQoKY29uc29sZS5sb2co'
        'J0EgaHVsbCBjYW4gb25seSBjYXJyeSB3aGF0IGl0IGNhbiBjYXJyeScpOwp7CiAgcmVzZXQoKTsg'
        'Vy5ydW4oImFwcGx5U2hpcCgnZml0b3RoJykiKTsKICBvaygnYSBmaWdodGVyIGlzIGdpdmVuIGEg'
        'bWlzc2lsZScsIFcucnVuKCJjdXJTZWMoKS5jbHMiKT09PSdtaXNzaWxlJyk7CiAgb2soJ2FuZCB0'
        'aGUgYmFyIGlzIHRvbGQgc28nLCBXLmdldCgncGxheWVyJykuc2VjVHlwZT09PSdtaXNzaWxlJyk7'
        'CiAgVy5ydW4oImFwcGx5U2hpcCgnYm9vc2lyaXMnKSIpOwogIG9rKCdhIGJvbWJlciBjYW5ub3Qg'
        'a2VlcCBpdCwgYW5kIGdldHMgYSBib21iJywgVy5ydW4oImN1clNlYygpLmNscyIpPT09J2JvbWIn'
        'KTsKICBvaygnYW5kIHRoZSBiYXIgYWdhaW4nLCBXLmdldCgncGxheWVyJykuc2VjVHlwZT09PSdi'
        'b21iJyk7CiAgb2soJ29ubHkgYm9tYnMgYXJlIG9mZmVyZWQgdG8gaXQnLAogICAgIFcucnVuKCJz'
        'ZWNvbmRhcmllc0ZvcignYm9vc2lyaXMnKSIpLmV2ZXJ5KHc9PncuY2xzPT09J2JvbWInKSk7CiAg'
        'b2soJ2FuZCBvbmx5IG1pc3NpbGVzIHRvIGEgZmlnaHRlcicsCiAgICAgVy5ydW4oInNlY29uZGFy'
        'aWVzRm9yKCdmaXRvdGgnKSIpLmV2ZXJ5KHc9PncuY2xzPT09J21pc3NpbGUnKSk7CiAgb2soJ3Ro'
        'ZSByYWNrIHNpemUgc3RpbGwgY29tZXMgZnJvbSB0aGUgaHVsbCcsCiAgICAgVy5nZXQoJ3BsYXll'
        'cicpLnNlY01heCA9PT0gVy5ydW4oInNoaXBTdGF0cygnYm9vc2lyaXMnKS5zZWMiKSk7Cn0KCmNv'
        'bnNvbGUubG9nKCdBIHJlZml0IGZpbGxzIHRoZSByYWNrIC0gdGhhdCBpcyB3aGF0IG1ha2VzIGl0'
        'IGEgcmVhcm0nKTsKewogIGNvbnN0IGNvcnZldHRlID0gKCk9Pih7dHlwZTonY29ydmV0dGUnLCBz'
        'aWRlOidhbGx5JywgZGVhZDpmYWxzZSwgd2FycE91dDowLCB3YXJwOjB9KTsKICByZXNldCgpOyBX'
        'LnJ1bigiYXBwbHlTaGlwKCdmaXRvdGgnKTsgc2NvcmU9MCIpOyBXLnNldCgnYWxsaWVzJywgW2Nv'
        'cnZldHRlKCldKTsKICBXLnJ1bigncGxheWVyLnNlY0FtbW89MycpOwogIFcucnVuKCd0b2dnbGVS'
        'ZWFybU1lbnUoKScpOwogIFcucnVuKCJmaXRXZWFwb24oJ214NjQnKSIpOwogIG9rKCdmaXR0aW5n'
        'IHdoYXQgaXMgYWxyZWFkeSBmaXR0ZWQgdG9wcyB0aGUgcmFjayB1cCcsCiAgICAgVy5nZXQoJ3Bs'
        'YXllcicpLnNlY0FtbW8gPT09IFcuZ2V0KCdwbGF5ZXInKS5zZWNNYXgpOwogIG9rKCdhbmQgY2xv'
        'c2VzIHRoZSBwYW5lbCcsIFcuZ2V0KCdyZWFybU1lbnUnKT09PWZhbHNlKTsKICAvLyBMb2NrZWQg'
        'd2VhcG9ucyBjYW5ub3QgYmUgdGFrZW4sIGhvd2V2ZXIgdGhleSBhcmUgcmVhY2hlZC4KICBXLnJ1'
        'bigncGxheWVyLnNlY0FtbW89MzsgdG9nZ2xlUmVhcm1NZW51KCknKTsKICBXLnJ1bigiZml0V2Vh'
        'cG9uKCdobDcnKSIpOwogIG9rKCdhIHdlYXBvbiBhYm92ZSB0aGUgc2NvcmUgY2Fubm90IGJlIGZp'
        'dHRlZCcsIFcuZ2V0KCdwbGF5ZXInKS5wcmk9PT0ncHJvbWV0aGV1cycpOwogIG9rKCdhbmQgdGhl'
        'IHBhbmVsIHN0YXlzIG9wZW4nLCBXLmdldCgncmVhcm1NZW51Jyk9PT10cnVlKTsKICBXLnJ1bign'
        'c2NvcmU9NjAwMCcpOwogIFcucnVuKCJmaXRXZWFwb24oJ2hsNycpIik7CiAgb2soJ3Bhc3QgdGhl'
        'IHRocmVzaG9sZCBpdCBjYW4nLCBXLmdldCgncGxheWVyJykucHJpPT09J2hsNycpOwogIG9rKCdh'
        'bmQgdGhlIHJhdGUgb2YgZmlyZSBmb2xsb3dzIHRoZSB3ZWFwb24nLCBXLmdldCgncGxheWVyJyku'
        'ZlI9PT0xNyk7CiAgVy5ydW4oJ3Njb3JlPTA7IHBsYXllci5wcmk9InByb21ldGhldXMiOyBhcHBs'
        'eUxvYWRvdXQoKScpOwp9Cgpjb25zb2xlLmxvZygnVGhlIHJlYXJtIHBhbmVsJyk7CnsKICBjb25z'
        'dCBjb3J2ZXR0ZSA9ICgpPT4oe3R5cGU6J2NvcnZldHRlJywgc2lkZTonYWxseScsIGRlYWQ6ZmFs'
        'c2UsIHdhcnBPdXQ6MCwgd2FycDowfSk7CiAgcmVzZXQoKTsgVy5ydW4oImFwcGx5U2hpcCgnZml0'
        'b3RoJyk7IHNjb3JlPTkwMDAiKTsgVy5zZXQoJ2FsbGllcycsIFtjb3J2ZXR0ZSgpXSk7CiAgVy5y'
        'dW4oJ3RvZ2dsZVJlYXJtTWVudSgpJyk7CiAgQ0xSKCk7IFcucnVuKCdkcmF3UmVhcm1NZW51KCkn'
        'KTsKICBjb25zdCBycyA9IFcucnVuKCd3aW5kb3cuX3JlYXJtUmVjdHMnKTsKICBjb25zdCBwciA9'
        'IFcucnVuKCd3aW5kb3cuX3JlYXJtUGFuZWxSZWN0Jyk7CiAgLy8gT25lIHJvdyBwZXIgd2VhcG9u'
        'IHRoYXQgZXhpc3RzLCBvcGVuIG9yIG5vdDogYSBsb2NrZWQgb25lIGlzIGEgdGhpbgogIC8vIGxp'
        'bmUsIGFuZCBpdCBpcyBzdGlsbCBhIHJvdy4gVGhlIGNvdW50IGZvbGxvd3MgdGhlIHRhYmxlcyBz'
        'byBhIG5ldwogIC8vIHdlYXBvbiBkb2VzIG5vdCBtYWtlIHRoaXMgZmFpbCBmb3Igbm8gcmVhc29u'
        'LgogIGNvbnN0IG9mZmVyZWQgPSBXLnJ1bignUFJJTUFSSUVTJykubGVuZ3RoICsgVy5ydW4oInNl'
        'Y29uZGFyaWVzRm9yKCdmaXRvdGgnKSIpLmxlbmd0aDsKICBvaygnb25lIHJvdyBwZXIgd2VhcG9u'
        'IG9uIG9mZmVyJywgcnMubGVuZ3RoPT09b2ZmZXJlZCk7CiAgb2soJ2V2ZXJ5IHJvdyBpcyBpbnNp'
        'ZGUgdGhlIHBhbmVsJywKICAgICBycy5ldmVyeShyPT5yLng+PXByLnggJiYgci54K3Iudzw9cHIu'
        'eCtwci53ICYmIHIueT49cHIueSAmJiByLnkrci5oPD1wci55K3ByLmgpKTsKICBvaygndGhlIHBh'
        'bmVsIGZpdHMgb24gdGhlIGZpZWxkJywgcHIueT49MCAmJiBwci55K3ByLmg8PTUwMCAmJiBwci54'
        'Pj0wICYmIHByLngrcHIudzw9ODAwKTsKICBvaygnbm8gQ291cmllciBhbnl3aGVyZScsCiAgICAg'
        'Q0FMTFMuZmlsdGVyKGM9PmMuZm49PT0nc2V0IGZvbnQnKS5ldmVyeShjPT5TdHJpbmcoYy5hcmdz'
        'WzBdKS5pbmRleE9mKCdDb3VyaWVyJyk8MCkpOwogIG9rKCd0aGUgZml0dGVkIHdlYXBvbiBnZXRz'
        'IHRoZSByaW5nJywgQ0FMTFMuc29tZShjPT5jLmZuPT09J3NldCBzaGFkb3dCbHVyJykpOwogIG9r'
        'KCdub3RoaW5nIGxlYWtzIG91dCBvZiBhIHNhdmUvcmVzdG9yZScsIGJhbGFuY2VkKCkpOwogIC8v'
        'IEEgY2xpY2sgaW5zaWRlIHRoZSBwYW5lbCB0aGF0IGhpdCBubyByb3cgbXVzdCBub3QgY2xvc2Ug'
        'aXQsIHRoZSBzYW1lCiAgLy8gcnVsZSB0aGUgaGFuZ2FyIGFuZCB0aGUgc3VwcG9ydCBtZW51IGZv'
        'bGxvdy4KICBXLnJ1bihgcG9pbnRlckNvbnN1bWVkKHt4OiR7cHIueCs0MH0seToke3ByLnkrNn19'
        'KWApOwogIG9rKCdhIGNsaWNrIG9uIHRoZSBoZWFkZXIga2VlcHMgaXQgb3BlbicsIFcuZ2V0KCdy'
        'ZWFybU1lbnUnKT09PXRydWUpOwogIFcucnVuKGBwb2ludGVyQ29uc3VtZWQoe3g6JHtwci54LTEy'
        'fSx5OiR7cHIueStwci5oLzJ9fSlgKTsKICBvaygnYSBjbGljayBiZXNpZGUgaXQgY2xvc2VzIGl0'
        'JywgVy5nZXQoJ3JlYXJtTWVudScpPT09ZmFsc2UpOwp9CnsKICAvLyBCZWxvdyB0aGUgdGhyZXNo'
        'b2xkIHRoZSBITC03IGlzIGEgdGhpbiBsaW5lLCBub3QgYSByb3cgdGhhdCBjYW4gYmUgdGFrZW4u'
        'CiAgY29uc3QgY29ydmV0dGUgPSAoKT0+KHt0eXBlOidjb3J2ZXR0ZScsIHNpZGU6J2FsbHknLCBk'
        'ZWFkOmZhbHNlLCB3YXJwT3V0OjAsIHdhcnA6MH0pOwogIHJlc2V0KCk7IFcucnVuKCJhcHBseVNo'
        'aXAoJ2ZpdG90aCcpOyBzY29yZT0wIik7IFcuc2V0KCdhbGxpZXMnLCBbY29ydmV0dGUoKV0pOwog'
        'IFcucnVuKCd0b2dnbGVSZWFybU1lbnUoKTsgZHJhd1JlYXJtTWVudSgpJyk7CiAgY29uc3QgcnMg'
        'PSBXLnJ1bignd2luZG93Ll9yZWFybVJlY3RzJyk7CiAgb2soJ2EgbG9ja2VkIHdlYXBvbiByZXBv'
        'cnRzIG5vIGtleScsIHJzLnNvbWUocj0+ci5rZXk9PT1udWxsKSk7CiAgb2soJ2FuZCBpdHMgbGlu'
        'ZSBpcyB0aGlubmVyIHRoYW4gYSByb3cgdGhhdCBjYW4gYmUgdGFrZW4nLAogICAgIE1hdGgubWlu'
        'KC4uLnJzLm1hcChyPT5yLmgpKSA8IE1hdGgubWF4KC4uLnJzLm1hcChyPT5yLmgpKSk7CiAgVy5y'
        'dW4oJ3NldFJlYXJtTWVudShmYWxzZSk7IHNjb3JlPTAnKTsKfQoKY29uc29sZS5sb2coJ1RoZSB0'
        'aXRsZSBzY3JlZW4nKTsKLy8gZHJhd1RpdGxlIGlzIHRvbyB0YW5nbGVkIHVwIHdpdGggdGhlIGJh'
        'Y2tkcm9wIHRvIHJ1biBoZXJlLCBzbyB3aGF0IGlzCi8vIGNoZWNrZWQgaXMgdGhlIHR3byB0aGlu'
        'Z3MgdGhhdCBtYWRlIGl0IGxvb2sgdGhlIHdheSBpdCBkaWQuCm9rKCdubyBvcGFxdWUgc2hlZXQg'
        'b3ZlciB0aGUgc2t5IGFueSBtb3JlJywgIS9maWxsU3R5bGU9J3JnYmFcKDAsMCw4LDBcLjc4XCkn'
        'O2N0eFwuZmlsbFJlY3RcKDAsMCxXLEhcKS8udGVzdChzcmMpKTsKb2soJ3doYXQgaXMgbGVmdCBp'
        'cyBhIGdyYWRpZW50LCBzbyB0aGUgYmFja2Ryb3Agc2hvd3MgdGhyb3VnaCB0aGUgdG9wJywKICAg'
        'L2NyZWF0ZUxpbmVhckdyYWRpZW50XCgwLCAwLCAwLCBIXClbXHNcU117MCwyNjB9P3JnYmFcKDAs'
        'MCw4LDBcLjIwXCkvLnRlc3Qoc3JjKSk7Cm9rKCd0aGUgcGFzdGVkIGxvZ28gYW5kIGl0cyAzIGFy'
        'ZSBnb25lJywKICAgIS9fbG9nb1Byb2Nlc3NlZC8udGVzdChzcmMpICYmICEvZnNfbG9nby8udGVz'
        'dChzcmMpKTsKb2soJ3RoZSB0aXRsZSBpcyBzZXQgaW4gdGhlIHRoZW1lIGZhY2UgaW5zdGVhZCcs'
        'IC9GUkVFU1BBQ0UvLnRlc3Qoc3JjKSAmJiAvdGhMYWJlbFwoNTRcKS8udGVzdChzcmMpKTsKb2so'
        'J2EgZnJlc2ggYmFja2Ryb3AgaXMgcm9sbGVkIGV2ZXJ5IHRpbWUgdGhlIHRpdGxlIGNvbWVzIHVw'
        'JywKICAgL2Z1bmN0aW9uIGVudGVyVGl0bGVcKFwpXHtbXHNcU117MCwzMDB9P25lYkN1ciA9IE5F'
        'Ql9OQU1FU1tcc1xTXXswLDEyMH0/cm9sbEJvZGllc1woXCkvLnRlc3Qoc3JjKSk7Cm9rKCdhbmQg'
        'YSBib2R5IHRoYXQgbGVhdmVzIHRoZSB0aXRsZSBpcyByZXBsYWNlZCwgbm90IHdyYXBwZWQgcm91'
        'bmQnLAogICAvaWZcKEdTPT09J3RpdGxlJ1wpXHsgcm9sbEJvZGllc1woXCk7IHJldHVybjsgXH0v'
        'LnRlc3Qoc3JjKSk7Cm9rKCd0aGUgdGl0bGUga2VlcHMgbW92aW5nIHdoaWxlIGl0IHNpdHMgdGhl'
        'cmUnLAogICAvaWZcKEdTPT09J3RpdGxlJ1wpXHsgZmNcK1wrOyB0aWNrU3RhcnNcKFwpOyB0aWNr'
        'TmVidWxhXChcKTsgcmV0dXJuOyBcfS8udGVzdChzcmMpKTsKb2soJ1RyeSBBZ2FpbiBnb2VzIGJh'
        'Y2sgdG8gdGhlIHRpdGxlIHJhdGhlciB0aGFuIGludG8gdGhlIG5leHQgcnVuJywKICAgL2Z1bmN0'
        'aW9uIHRvVGl0bGVPckxhdW5jaFwoXClce1tcc1xTXXswLDE2MH0/R1M9PT0nZ2FtZW92ZXInXCl7'
        'IGVudGVyVGl0bGVcKFwpLy50ZXN0KHNyYykpOwpvaygnYW5kIG5vdGhpbmcgY2FsbHMgbGF1bmNo'
        'R2FtZSBzdHJhaWdodCBmcm9tIHRoZSBnYW1lIG92ZXIgc2NyZWVuJywKICAgIS9nYW1lT3ZlckF0'
        'PjE1MDBcKSBsYXVuY2hHYW1lXChcKS8udGVzdChzcmMpKTsKCmNvbnNvbGUubG9nKCdCYXIgYnV0'
        'dG9uIHBsYWNlbWVudCcpOwp7CiAgLy8gVGhlIHNoaXAgc3dpdGNoIGFuZCB0aGUgcmVhcm0gYnV0'
        'dG9uIGFyZSBkcmF3biBhcyBvbmUgcGFpciBub3csIHNvIHRoZQogIC8vIHNuaXBwZXQgY292ZXJz'
        'IGJvdGggYW5kIGJvdGggYXJlIGNoZWNrZWQuCiAgY29uc3QgYSA9IHNyYy5pbmRleE9mKCcgIC8v'
        'IFNISVAgU1dJVENIIGFuZCBSRUFSTScpLCBiID0gc3JjLmluZGV4T2YoJyAgLy8gU0VUVElOR1Mg'
        'YW5kIFBBVVNFJyk7CiAgY29uc3Qgc25pcCA9IHNyYy5zbGljZShhLCBiKTsKICBXLnJ1bigidmFy'
        'IEgyPTU0OyBzaGlwTWVudT1mYWxzZTsgcmVhcm1NZW51PWZhbHNlOyBhbGxpZXM9W107IgogICAg'
        'ICArICIgd2luZG93Ll9zaGlwQnRuUmVjdD11bmRlZmluZWQ7IHdpbmRvdy5fcmVhcm1CdG5SZWN0'
        'PXVuZGVmaW5lZDsgIiArIHNuaXApOwogIGNvbnN0IHIgPSBXLnJ1bignd2luZG93Ll9zaGlwQnRu'
        'UmVjdCcpLCBybSA9IFcucnVuKCd3aW5kb3cuX3JlYXJtQnRuUmVjdCcpOwogIG9rKCd0aGUgc2hp'
        'cCBidXR0b24gc2l0cyBiZXR3ZWVuIHRpY2tldHMgKDY2NSkgYW5kIGdlYXIgKDc0OCknLCByICYm'
        'IHIueD42NjUgJiYgci54K3Iudzw3NDgpOwogIG9rKCd0aGUgcmVhcm0gYnV0dG9uIHNpdHMgYmVz'
        'aWRlIGl0LCBhbHNvIGNsZWFyIG9mIHRoZSBnZWFyJywKICAgICBybSAmJiBybS54ID49IHIueCty'
        'LncgJiYgcm0ueCtybS53IDwgNzQ4KTsKICBvaygndGhleSBkbyBub3Qgb3ZlcmxhcCcsIHJtICYm'
        'IHJtLnggPj0gci54ICsgci53KTsKICBXLnJ1bigiRlMxX01PREU9dHJ1ZTsgIiArIHNuaXApOwog'
        'IG9rKCduZWl0aGVyIGJ1dHRvbiBpbiBGUzEgbW9kZScsCiAgICAgVy5ydW4oJ3dpbmRvdy5fc2hp'
        'cEJ0blJlY3QnKT09PW51bGwgJiYgVy5ydW4oJ3dpbmRvdy5fcmVhcm1CdG5SZWN0Jyk9PT1udWxs'
        'KTsKICBXLnJ1bignRlMxX01PREU9ZmFsc2UnKTsKfQpjb25zb2xlLmxvZygnQ3ljbGUgc2NhbGlu'
        'ZyBrZWVwcyB0aGUgaHVsbCcpOwpvaygnbmV4dFdhdmUgc2NhbGVzIGZyb20gdGhlIGh1bGwgYmFz'
        'ZSwgbm90IGZyb20gMTAwJywgc3JjLmluY2x1ZGVzKCdwbGF5ZXIubWF4SHA9TWF0aC5yb3VuZCgo'
        'cGxheWVyLmJhc2VIcHx8MTAwKSpwbSk7JykpOwpvaygncmVzcGF3biByZXN0b3JlcyB0aGUgZnVs'
        'bCBodWxsJywgc3JjLmluY2x1ZGVzKCdwbGF5ZXIuaHA9cGxheWVyLm1heEhwO3BsYXllci54PTgw'
        'OycpKTsKCmNvbnNvbGUubG9nKCdcbicgKyAoZmFpbHMgPyBmYWlscysnIEZBSUxFRCcgOiAnYWxs'
        'IHBhc3NlZCcpKTsKcHJvY2Vzcy5leGl0KGZhaWxzPzE6MCk7Cg=='
    ),
    'fieldsim.js': (
        'Ly8gRmllbGQgc2ltdWxhdGlvbjogcnVucyB0aGUgUkVBTCBnYW1lIGluIGEgaGVhZGxlc3MgYnJv'
        'd3Nlci4KLy8KLy8gVGhlIG90aGVyIHNpbXVsYXRpb25zIGxpZnQgc2luZ2xlIGZ1bmN0aW9ucyBv'
        'dXQgb2YgdGhlIGxvZ2ljIGZpbGUuIFRoaXMgb25lCi8vIGxvYWRzIHRoZSB3aG9sZSBmaWxlLCBz'
        'dGFydHMgYSByZWFsIHJ1biB3aXRoID9tPU5OIGFuZCBzdGVwcyB0aGUgcmVhbAovLyB1cGRhdGUo'
        'KSAtIHNwYXduIHF1ZXVlLCBldmVudHMsIGFsbGllZCBhbmQgZW5lbXkgZmxpZ2h0LCB0aGUgbG90'
        'LiBUaGF0IGlzCi8vIHRoZSBwYXJ0IHRoZSBvdGhlcnMgY2Fubm90IHNlZTogd2hldGhlciBhIG1p'
        'c3Npb24gYWN0dWFsbHkgcGxheXMgb3V0LgovLwovLyBObyBzcHJpdGVzIGFyZSBlbWJlZGRlZCBp'
        'biBhIGxvZ2ljIGZpbGUsIHNvIGV2ZXJ5IGh1bGwgZ2V0cyBhIHBsYWluIG9wYXF1ZQovLyBzdGFu'
        'ZC1pbiBvZiBhIGZpdHRpbmcgc2hhcGUsIGFuZCB0aGUgbW91bnQgZGF0YSBpcyBwdXQgaW4gdGhl'
        'IHdheSB0aGUKLy8gcGFja2VyIHB1dHMgaXQgaW4uIFRoZSBwbGF5ZXIgY2Fubm90IGRpZTsgdGhl'
        'IHNjZW5hcmlvcyBkZWNpZGUgd2hhdCBnZXRzCi8vIHNob3QgZG93biwgYW5kIHdoZW4uCi8vCi8v'
        'IE5lZWRzIFBsYXl3cmlnaHQgd2l0aCBDaHJvbWl1bSAoaXQgcnVucyB3aGVyZSB0aGUgYnVpbGQg'
        'aXMgY2hlY2tlZCwgbm90IG9uCi8vIHRoZSBzZXJ2ZXIpLgovLyBVc2FnZTogbm9kZSBmaWVsZHNp'
        'bS5qcyA8bG9naWMuaHRtbD4gW2hscF9tb3VudHNfZmluYWwuanNvbl0KY29uc3QgZnMgPSByZXF1'
        'aXJlKCdmcycpLCBwYXRoID0gcmVxdWlyZSgncGF0aCcpLCBvcyA9IHJlcXVpcmUoJ29zJyk7CmNv'
        'bnN0IHsgZXhlY1N5bmMgfSA9IHJlcXVpcmUoJ2NoaWxkX3Byb2Nlc3MnKTsKY29uc3QgUFcgPSBw'
        'YXRoLmpvaW4oZXhlY1N5bmMoJ25wbSByb290IC1nJykudG9TdHJpbmcoKS50cmltKCksICdwbGF5'
        'd3JpZ2h0Jyk7CmNvbnN0IHsgY2hyb21pdW0gfSA9IHJlcXVpcmUoUFcpOwoKY29uc3QgbG9naWMg'
        'PSBwcm9jZXNzLmFyZ3ZbMl07CmNvbnN0IG1vdW50cyA9IHByb2Nlc3MuYXJndlszXSB8fCAnaGxw'
        'X21vdW50c19maW5hbC5qc29uJzsKbGV0IGh0bWwgPSBmcy5yZWFkRmlsZVN5bmMobG9naWMsICd1'
        'dGY4Jyk7CmNvbnN0IE0gPSBmcy5yZWFkRmlsZVN5bmMobW91bnRzLCAndXRmOCcpOwovLyBTYW1l'
        'IHNoYXBlIGFzIGJ1aWxkX2dhbWUucHkncyByZW5kZXJfbW91bnRzKCksIHBsYWNlZCBmaXJzdCBz'
        'byBpdCBleGlzdHMKLy8gYmVmb3JlIGFueXRoaW5nIGFza3MgZm9yIGl0LgpodG1sID0gaHRtbC5y'
        'ZXBsYWNlKC88c2NyaXB0KFtePl0qKT4vLCAnPHNjcmlwdCQxPlxuY29uc3QgTU9VTlRTPScgKyBK'
        'U09OLnN0cmluZ2lmeShKU09OLnBhcnNlKE0pKSArICc7XG4nKTsKY29uc3QgdG1wID0gcGF0aC5q'
        'b2luKG9zLnRtcGRpcigpLCAnZmllbGRzaW1fJyArIHByb2Nlc3MucGlkICsgJy5odG1sJyk7CmZz'
        'LndyaXRlRmlsZVN5bmModG1wLCBodG1sKTsKCi8vIEluLXBhZ2UgaGVscGVycy4gRXZlcnl0aGlu'
        'ZyBoZXJlIHJ1bnMgYWdhaW5zdCB0aGUgZ2FtZSdzIG93biBnbG9iYWxzLgpjb25zdCBIRUxQRVJT'
        'ID0gYAogIHdpbmRvdy5GUyA9IHsKICAgIGZha2VJbWFnZXMoKXsKICAgICAgZm9yKGNvbnN0IGsg'
        'b2YgT2JqZWN0LmtleXMoSFVMTF9MRU4pKXsKICAgICAgICBjb25zdCBzbWFsbCA9IC9eKGZpfGJv'
        'fHNnfGZjfGVwKS8udGVzdChrKSAmJiBIVUxMX0xFTltrXSA8IDgwOwogICAgICAgIGNvbnN0IGMg'
        'PSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdjYW52YXMnKTsKICAgICAgICBjLndpZHRoID0gc21h'
        'bGwgPyA2MCA6IDMyMDsgYy5oZWlnaHQgPSBzbWFsbCA/IDQwIDogOTA7CiAgICAgICAgY29uc3Qg'
        'ZyA9IGMuZ2V0Q29udGV4dCgnMmQnKTsgZy5maWxsU3R5bGUgPSAnIzg4OCc7IGcuZmlsbFJlY3Qo'
        'MCwwLGMud2lkdGgsYy5oZWlnaHQpOwogICAgICAgIElNR1Nba10gPSBjOwogICAgICB9CiAgICB9'
        'LAogICAgc3RlcChuKXsgZm9yKGxldCBpPTA7aTxuO2krKyl7IHBsYXllci5ocCA9IHBsYXllci5t'
        'YXhIcDsgcGxheWVyLnNoID0gcGxheWVyLm1heFNoOwogICAgICAgICAgICAgaWYodHlwZW9mIGxp'
        'dmVzIT09J3VuZGVmaW5lZCcpIGxpdmVzID0gMzsgdXBkYXRlKCk7IGlmKGklMjU9PT0wKSBkcmF3'
        'KCk7IH0gfSwKICAgIC8vIFNob290IGRvd24gZXZlcnkgZW5lbXkgZmlnaHRlciBhbmQgYm9tYmVy'
        'IHRoYXQgaXMgb3V0IG9mIGl0cyB2b3J0ZXgsCiAgICAvLyB0aGUgYm9tYnMgaW4gZmxpZ2h0IGFu'
        'ZCByb2NrcyBjbG9zaW5nIG9uIGFuIGVzY29ydCAtIHdoYXQgYSBwbGF5ZXIKICAgIC8vIGRlZmVu'
        'ZGluZyBvbmUgZG9lcy4KICAgIGtpbGxTbWFsbCgpeyBmb3IoY29uc3QgZSBvZiBlbmVtaWVzKSBp'
        'ZigoZS50eXBlPT09J2ZpZ2h0ZXInfHxlLnR5cGU9PT0nYm9tYmVyJykgJiYgIShlLndhcnA+MCkp'
        'IGUuaHAgPSAwOwogICAgICAgICAgICAgICAgIGZvcihsZXQgaT1lQnVsbGV0cy5sZW5ndGgtMTtp'
        'Pj0wO2ktLSkgaWYoZUJ1bGxldHNbaV0ua2luZD09PSdib21iJykgZUJ1bGxldHMuc3BsaWNlKGks'
        'MSk7CiAgICAgICAgICAgICAgICAgLy8gTG9vc2Ugcm9ja3MgYWJvdXQgdG8gaGl0IGFuIGVzY29y'
        'dCBhcyB3ZWxsLgogICAgICAgICAgICAgICAgIGZvcihjb25zdCBlIG9mIGVuZW1pZXMpIGlmKGUu'
        'dHlwZT09PSdhc3Rlcm9pZCcgJiYgIWUuc2NlbmVyeSAmJgogICAgICAgICAgICAgICAgICAgYWxs'
        'aWVzLnNvbWUoYT0+IWEuc21hbGwgJiYgTWF0aC5oeXBvdChhLngtZS54LCBhLnktZS55KSA8IDE4'
        'MCkpIGUuaHAgPSAwOyB9LAogICAga2lsbElkKGlkKXsgZm9yKGNvbnN0IGUgb2YgZW5lbWllcykg'
        'aWYoZS51aWQ9PT1pZCAmJiAhKGUud2FycD4wKSkgZS5ocCA9IDA7IH0sCiAgICAvLyBTdGVwIHVu'
        'dGlsIGNvbmQoKSBob2xkcywgY2xlYXJpbmcgc21hbGwgY3JhZnQgZXZlcnkgc28gb2Z0ZW4uCiAg'
        'ICB1bnRpbChjb25kLCBtYXgsIGNsZWFyLCBhbGwpeyBmb3IobGV0IHQ9MDt0PG1heDt0Kz0yMCl7'
        'IGlmKGNvbmQoKSkgcmV0dXJuIHQ7CiAgICAgICAgICAgICBpZihjbGVhciAmJiB0JTIwMD09PTAp'
        'IEZTLmtpbGxTbWFsbCgpOwogICAgICAgICAgICAgaWYoYWxsICYmIHQlMjAwPT09MCkgZm9yKGNv'
        'bnN0IGUgb2YgZW5lbWllcykgaWYoIShlLndhcnA+MCkgJiYgIWUuaW52dWxuICYmICFlLnNjZW5l'
        'cnkpIGUuaHAgPSAwOwogICAgICAgICAgICAgRlMuc3RlcCgyMCk7IH0gcmV0dXJuIC0xOyB9LAog'
        'ICAgaWRzKGlkKXsgcmV0dXJuIGJ5SWQoaWQpOyB9LAogICAgZW5lbXlJZHMoKXsgcmV0dXJuIGVu'
        'ZW1pZXMubWFwKGU9PmUudWlkfHxlLnR5cGUpOyB9LAogICAgYWxseUlkcygpeyByZXR1cm4gYWxs'
        'aWVzLm1hcChhPT5hLnVpZHx8YS50eXBlKTsgfQogIH07YDsKCmNvbnN0IHNjZW5hcmlvcyA9IFtd'
        'OwpmdW5jdGlvbiBzY2VuYXJpbyhuYW1lLCBxdWVyeSwgYm9keSwgbm9MYXVuY2gpeyBzY2VuYXJp'
        'b3MucHVzaCh7bmFtZSwgcXVlcnksIGJvZHksIG5vTGF1bmNofSk7IH0KCi8vIOKUgOKUgCBTY2Vu'
        'YXJpb3Mg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
        '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
        '4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA'
        '4pSA4pSA4pSACnNjZW5hcmlvKCdNMzEgRGVyIEF1ZnN0YW5kJywgJ209MzEnLCBgCiAgY29uc3Qg'
        'ciA9IHt9OwogIHIud2F2ZSA9IHdhdmU7IHIuc2hpcCA9IHBsYXllci5zaGlwOwogIHIudGVycmFu'
        'Q2FsbCA9IEFMTFlfRkFDX09OLnRlcnJhbj09PXRydWUgJiYgQUxMWV9GQUNfT04udmFzdWRhbj09'
        'PWZhbHNlOwogIEZTLnN0ZXAoNDAwKTsKICBjb25zdCBhID0gYWxsaWVzLmZpbmQoeD0+eC51aWQ9'
        'PT0nQTEnKTsKICByLmFsbHlBdFN0YXJ0ID0gISFhICYmIGEuaW1nPT09J2NybGV2aWF0aGFuJzsK'
        'ICByLmxvY2tTZXQgPSAhIWEgJiYgYS5kZWZlY3RMb2NrPT09dHJ1ZTsKICAvLyBIYW1tZXIgaGVy'
        'IHdoaWxlIHNoZSBpcyBzdGlsbCBvdXJzOiBzaGUgbXVzdCBub3QgZGllIGJlZm9yZSB0aGUgdHVy'
        'bi4KICBpZihhKXsgYS5ocCA9IDE7IEZTLnN0ZXAoNSk7IH0KICByLnN1cnZpdmVzTG9jayA9ICEh'
        'YWxsaWVzLmZpbmQoeD0+eC51aWQ9PT0nQTEnKTsKICAvLyBTdGVwIGJ5IHN0ZXAgdXAgdG8gdGhl'
        'IHR1cm46IHdoZXJlIHNoZSB3YXMgbGFzdCBhcyBhbiBhbGx5LCBhbmQgd2hlcmUKICAvLyBzaGUg'
        'aXMgaW4gdGhlIGZpcnN0IHN0ZXAgYXMgYW4gZW5lbXkuCiAgbGV0IGxhc3QgPSBudWxsLCBmaXJz'
        'dCA9IG51bGw7CiAgZm9yKGxldCBrPTA7azw4MDAwICYmICFmaXJzdDtrKyspewogICAgaWYoayUy'
        'MDA9PT0wKSBGUy5raWxsU21hbGwoKTsKICAgIGNvbnN0IGFsID0gYWxsaWVzLmZpbmQoeD0+eC51'
        'aWQ9PT0nQTEnKTsKICAgIGlmKGFsKSBsYXN0ID0ge3g6YWwueCwgeTphbC55fTsKICAgIEZTLnN0'
        'ZXAoMSk7CiAgICBjb25zdCBlbiA9IGVuZW1pZXMuZmluZCh4PT54LnVpZD09PSdBMScpOwogICAg'
        'aWYoZW4pIGZpcnN0ID0ge3g6ZW4ueCwgeTplbi55fTsKICB9CiAgci50dXJuc0luUGxhY2UgPSAh'
        'IWxhc3QgJiYgISFmaXJzdCAmJiBNYXRoLmFicyhmaXJzdC54LWxhc3QueCkgPCAyICYmIE1hdGgu'
        'YWJzKGZpcnN0LnktbGFzdC55KSA8IDI7CiAgRlMuc3RlcCg0MCk7CiAgY29uc3QgZSA9IGVuZW1p'
        'ZXMuZmluZCh4PT54LnVpZD09PSdBMScpOwogIHIudHVybmVkID0gISFlICYmICFhbGxpZXMuc29t'
        'ZSh4PT54LnVpZD09PSdBMScpOwogIHIubnRmSHVsbCA9ICEhZSAmJiBlLmltZz09PSdudGZjcmxl'
        'dmlhdGhhbic7CiAgci5lbmVteVNoYXBlID0gISFlICYmIGUudHlwZT09PSdjcnVpc2VyJyAmJiBl'
        'LnNpZGU9PT0nZW5lbXknICYmICFlLmRlYWQgJiYgZS5ocD4wOwogIHIuaGFzU3VicyA9ICEhZSAm'
        'JiAhIWUuc3VicyAmJiBlLnN1YnMubGVuZ3RoPT09NTsKICByLmhhc0d1bnMgPSAhIWUgJiYgISEo'
        'ZS5ndW5zfHxlLm1vdW50c3x8ZS53cG58fGUuYmVhbXMpOwogIHIuZmFjZXNXaGVyZVNoZUdvZXMg'
        'PSAhIWUgJiYgZS5mbGlwPT09bmVlZHNGbGlwKGUuaW1nLCBmYWxzZSk7CiAgY29uc3QgeDAgPSBl'
        'ID8gZS54IDogMDsKICBGUy5zdGVwKDIwMCk7CiAgci53YXZlT3BlbldoaWxlU2hlTGl2ZXMgPSAh'
        'd2F2ZU92ZXI7CiAgci5oZWFkc1JpZ2h0ID0gISFlICYmIGUueCA+IHgwOwogIC8vIExlZnQgYWxv'
        'bmUgc2hlIHJlYWNoZXMgdGhlIGVkZ2UgYW5kIGp1bXBzLgogIGNvbnN0IHQgPSBGUy51bnRpbCgo'
        'KT0+ISFFVl9MRUZUWydBMSddLCA4MDAwLCB0cnVlKTsKICByLmp1bXBzQXRUaGVFZGdlID0gdD49'
        'MCAmJiBlLndhcnBPdXQ+MCAmJiBlLnggPCBXOwogIHIud2hpbGVGdWxseU9uU2NyZWVuID0gISFl'
        'ICYmIGUueCArIElNR1NbZS5pbWddLndpZHRoKmUuc2MqMC41IDw9IFc7CiAgRlMudW50aWwoKCk9'
        'PiFlbmVtaWVzLmluY2x1ZGVzKGUpLCAxMDAwLCBmYWxzZSk7CiAgci5nb25lQWZ0ZXJKdW1wID0g'
        'IWVuZW1pZXMuaW5jbHVkZXMoZSk7CiAgRlMudW50aWwoKCk9PndhdmVPdmVyLCA0MDAwLCB0cnVl'
        'KTsKICByLndhdmVFbmRzID0gd2F2ZU92ZXI7CiAgcmV0dXJuIHI7YCk7CgpzY2VuYXJpbygnTTMx'
        'IGVuZ2luZXMgc3RvcCBoZXInLCAnbT0zMScsIGAKICBGUy5zdGVwKDMwMCk7CiAgRlMudW50aWwo'
        'KCk9PiFlbmVtaWVzLnNvbWUoZT0+ZS51aWQ9PT0nRTEnKSAmJiAhc3Bhd25RLnNvbWUocT0+cS51'
        'aWQ9PT0nRTEnKSwgNjAwMCwgdHJ1ZSk7CiAgRlMuc3RlcCg0MCk7CiAgY29uc3QgZSA9IGVuZW1p'
        'ZXMuZmluZCh4PT54LnVpZD09PSdBMScpOwogIGZvcihjb25zdCBzIG9mIGUuc3VicykgaWYocy5p'
        'ZD09PSdlbmdpbmVzJyl7IHMuZGVhZCA9IHRydWU7IHMuaHAgPSAwOyB9CiAgY29uc3QgeDAgPSBl'
        'Lng7IEZTLnN0ZXAoNjAwKTsKICByZXR1cm4ge3N0b3BwZWQ6IE1hdGguYWJzKGUueC14MCkgPCAw'
        'LjAxICYmICFFVl9MRUZUWydBMSddfTtgKTsKCnNjZW5hcmlvKCdNMzIgRGllIEZyYWNodHJvdXRl'
        'JywgJ209MzInLCBgCiAgY29uc3QgciA9IHt9OwogIEZTLnN0ZXAoMzAwKTsKICBjb25zdCBmID0g'
        'YWxsaWVzLmZpbHRlcih4PT54LnVpZD09PSdGMScpOwogIHIudHdvRnJlaWdodGVycyA9IGYubGVu'
        'Z3RoPT09MiAmJiBmLmV2ZXJ5KHg9PnguaW1nPT09J2ZycG9zZWlkb24nKTsKICByLnRlcnJhblNp'
        'ZGUgPSBmLmV2ZXJ5KHg9PnguZmFjdGlvbj09PSd0ZXJyYW4nKTsKICByLm1lZHVzYXMgPSBlbmVt'
        'aWVzLmZpbHRlcihlPT5lLnVpZD09PSdCMScpLmV2ZXJ5KGU9PmUuaW1nPT09J2JvbWVkdXNhJykg'
        'JiYgZW5lbWllcy5zb21lKGU9PmUudWlkPT09J0IxJyk7CiAgci5maWdodGVyQ292ZXIgPSBlbmVt'
        'aWVzLnNvbWUoZT0+ZS51aWQ9PT0nRTEnICYmIGUudHlwZT09PSdmaWdodGVyJykgfHwgc3Bhd25R'
        'LnNvbWUocT0+cS51aWQ9PT0nRTEnKTsKICBjb25zdCB4MCA9IGYubGVuZ3RoID8gZlswXS54IDog'
        'MDsgRlMuc3RlcCgzMDApOwogIHIuY3Jvc3NpbmcgPSBmLmxlbmd0aD4wICYmIGZbMF0ueCA+IHgw'
        'OwogIEZTLnVudGlsKCgpPT4hZW5lbWllcy5zb21lKGU9PmUudWlkPT09J0IxJyksIDQwMDAsIHRy'
        'dWUpOwogIEZTLnN0ZXAoMzAwKTsKICByLnNlY29uZFJhaWQgPSBlbmVtaWVzLnNvbWUoZT0+ZS51'
        'aWQ9PT0nQjInKSB8fCBzcGF3blEuc29tZShxPT5xLnVpZD09PSdCMicpOwogIHIuZW5kc1doZW5U'
        'aHJvdWdoID0gRlMudW50aWwoKCk9PndhdmVPdmVyLCAyMDAwMCwgdHJ1ZSkgPj0gMDsKICByZXR1'
        'cm4gcjtgKTsKCnNjZW5hcmlvKCdNMzMgRGllIFJlbGFpc3N0YXRpb24nLCAnbT0zMycsIGAKICBj'
        'b25zdCByID0ge307CiAgRlMuc3RlcCgzMDApOwogIGNvbnN0IHMgPSBlbmVtaWVzLmZpbmQoZT0+'
        'ZS51aWQ9PT0nUzEnKTsKICByLmZhdXN0dXMgPSAhIXMgJiYgcy5pbWc9PT0nc2NmYXVzdHVzJzsK'
        'ICByLmF0R2l2ZW5IZWlnaHQgPSAhIXMgJiYgTWF0aC5hYnMocy55LTI1MCkgPCAxOwogIGNvbnN0'
        'IHgwID0gcyA/IHMueCA6IDA7CiAgRlMuc3RlcCgxMjAwKTsKICByLnN0YXlzUHV0ID0gISFzICYm'
        'IE1hdGguYWJzKHMueC14MCkgPCAxICYmIE1hdGguYWJzKHMueS0yNTApIDwgMTsKICByLm5vRmxh'
        'ayA9ICEhcyAmJiBmbGFrSGFzKHMpPT09ZmFsc2U7CiAgci5ndW5zID0gZW5lbWllcy5maWx0ZXIo'
        'ZT0+ZS51aWQ9PT0nRzEnKS5sZW5ndGg9PT00OwogIC8vIFJlaW5mb3JjZW1lbnRzIGtlZXAgY29t'
        'aW5nIHdoaWxlIHNoZSBzdGFuZHMuCiAgRlMua2lsbFNtYWxsKCk7IEZTLnN0ZXAoOTAwKTsKICBy'
        'LnJlaW5mb3JjZWQgPSBlbmVtaWVzLnNvbWUoZT0+ZS50eXBlPT09J2ZpZ2h0ZXInICYmICFlLnVp'
        'ZCkgfHwgc3Bhd25RLnNvbWUocT0+IXEudWlkICYmIC9eZmlfLy50ZXN0KHEudHlwZSkpOwogIGNv'
        'bnN0IGJlZm9yZSA9IFNIT0NLUy5sZW5ndGg7CiAgRlMua2lsbElkKCdTMScpOyBGUy5zdGVwKDMp'
        'OwogIHIuYmlnQmxhc3QgPSBTSE9DS1Muc29tZShrPT5rLnJNYXg9PT0zMDApOwogIEZTLmtpbGxT'
        'bWFsbCgpOyBGUy5zdGVwKDEyMDApOyBGUy5raWxsU21hbGwoKTsgRlMuc3RlcCg2MDApOwogIHIu'
        'cmVpbmZPZmYgPSBldlJlaW5mPT09ZmFsc2U7CiAgcmV0dXJuIHI7YCk7CgpzY2VuYXJpbygnTTM0'
        'IERpZSBGbGFrd2FuZCcsICdtPTM0JywgYAogIGNvbnN0IHIgPSB7fTsKICBzY29yZSA9IDIwMDAw'
        'OyAgIC8vIGVub3VnaCBmb3IgdGhlIEFydGVtaXMgdG8gYmUgb3BlbiBpbiB0aGlzIGN5Y2xlCiAg'
        'RlMuc3RlcCg0MDApOwogIGNvbnN0IGsgPSBlbmVtaWVzLmZpbHRlcihlPT5lLnVpZD09PSdLMScp'
        'OwogIHIudHdvQWVvbHVzID0gay5sZW5ndGg9PT0yICYmIGsuZXZlcnkoZT0+ZS5pbWc9PT0nbnRm'
        'Y3JhZW9sdXMnKTsKICByLmZsYWsgPSBrLmV2ZXJ5KGU9PmZsYWtIYXMoZSkpOwogIHIubm9IYW5n'
        'YXJZZXQgPSAhYWxsaWVzLnNvbWUoYT0+YS51aWQ9PT0nQTEnKTsKICBGUy51bnRpbCgoKT0+IWVu'
        'ZW1pZXMuc29tZShlPT5lLnVpZD09PSdFMScpICYmICFzcGF3blEuc29tZShxPT5xLnVpZD09PSdF'
        'MScpLCA1MDAwLCB0cnVlKTsKICBGUy5zdGVwKDQwMCk7CiAgY29uc3QgbyA9IGFsbGllcy5maW5k'
        'KGE9PmEudWlkPT09J0ExJyk7CiAgci5vcmlvbiA9ICEhbyAmJiBvLmltZz09PSdkZW9yaW9ucmln'
        'aHQnOwogIHRpY2tTaGlwVW5sb2NrcygpOwogIHIuYm9tYmVyT2ZmZXJlZCA9IHNoaXBPZmZlcmVk'
        'KCdib2FydGVtaXMnKSAmJiBzaGlwU3dhcFJlYWR5KCk7CiAgcmV0dXJuIHI7YCk7CgpzY2VuYXJp'
        'bygnTTM1IERlciBVZWJlcmxhZXVmZXInLCAnbT0zNScsIGAKICBjb25zdCByID0ge307CiAgRlMu'
        'c3RlcCgzMDApOwogIGNvbnN0IGQgPSBhbGxpZXMuZmluZChhPT5hLnVpZD09PSdBMScpOwogIHIu'
        'bnRmRGVpbW9zID0gISFkICYmIGQuaW1nPT09J250ZmNvZGVpbW9zJyAmJiBkLnR5cGU9PT0nY29y'
        'dmV0dGUnOwogIHIuY29tZXNGcm9tVGhlUmlnaHQgPSAhIWQgJiYgZC54ID4gVyowLjY7CiAgci5m'
        'YWNlc0xlZnQgPSAhIWQgJiYgZC5mbGlwPT09bmVlZHNGbGlwKCdudGZjb2RlaW1vcycsIHRydWUp'
        'OwogIHIuY3Jvc3NpbmcgPSAhIWQgJiYgZC50cmFuc2l0PT09dHJ1ZTsKICByLmZpcnN0V2luZ0h1'
        'bnRzSGVyID0gd2F2ZUh1bnQ9PT0nQTEnOwogIGNvbnN0IHgwID0gZCA/IGQueCA6IDA7IEZTLnN0'
        'ZXAoMjAwKTsKICByLmhlYWRzTGVmdCA9ICEhZCAmJiBkLnggPCB4MDsKICBGUy51bnRpbCgoKT0+'
        'IWVuZW1pZXMuc29tZShlPT5lLnVpZD09PSdFMScpICYmICFzcGF3blEuc29tZShxPT5xLnVpZD09'
        'PSdFMScpLCA1MDAwLCB0cnVlKTsKICBGUy5zdGVwKDIwKTsKICByLnJlaW5mb3JjZW1lbnRzT24g'
        'PSBldlJlaW5mPT09dHJ1ZTsKICByLmZvbGxvd1Vwc1NjcmVlbiA9IHdhdmVIdW50PT09Jyc7CiAg'
        'ci5yZWFybSA9IGNvcnZldHRlT25GaWVsZCgpOwogIHIubm90T25DYWxsTWVudSA9IEFMTFlfT1JE'
        'RVIuaW5kZXhPZignbnRmX2RlaW1vcycpPDA7CiAgY29uc3QgZ290ID0gRlMudW50aWwoKCk9PiFh'
        'bGxpZXMuc29tZShhPT5hLnVpZD09PSdBMScpLCA5MDAwLCB0cnVlKTsKICByLmdldHNBY3Jvc3Mg'
        'PSBnb3Q+PTAgJiYgIWd1YXJkTG9zdDsKICByLmxlZnRDb3VudHMgPSAhIUVWX0xFRlRbJ0ExJ107'
        'CiAgci5ub3RoaW5nTW9yZUNvbWVzID0gZXZSZWluZj09PWZhbHNlICYmIHNwYXduUS5sZW5ndGg9'
        'PT0wOwogIEZTLnVudGlsKCgpPT53YXZlT3ZlciwgNDAwMCwgdHJ1ZSk7CiAgci53YXZlRW5kcyA9'
        'IHdhdmVPdmVyOwogIHJldHVybiByO2ApOwoKc2NlbmFyaW8oJ00zNiBEaWUgSWNlbmknLCAnbT0z'
        'NicsIGAKICBjb25zdCByID0ge307CiAgY29uc3QgczAgPSBzY29yZSA9IDUwMDA7CiAgRlMuc3Rl'
        'cCgzMDApOwogIGNvbnN0IGkgPSBlbmVtaWVzLmZpbmQoZT0+ZS51aWQ9PT0nVjEnKTsKICByLmlj'
        'ZW5pID0gISFpICYmIGkuaWNlbmk9PT10cnVlICYmIGkuaW1nPT09J2NvaWNlbmknOwogIHIubm9O'
        'YXZpZ2F0aW9uID0gISFpICYmICEhaS5zdWJzICYmIGkuc3Vicy5sZW5ndGg9PT00ICYmIHN1Yk9L'
        'KGksJ25hdmlnYXRpb24nKTsKICByLmRlYWRsaW5lID0gISFpICYmIGkuZmxlZVQ+MCAmJiBpLmZs'
        'ZWVUIDw9IDI1KlRJQ0tfSFo7CiAgRlMuc3RlcCg2MDApOwogIHIud2hvbGVIdWxsT25TY3JlZW4g'
        'PSAhIWkgJiYgaS54ICsgSU1HU1tpLmltZ10ud2lkdGgqaS5zYyowLjUgPD0gVzsKICBjb25zdCB0'
        'ID0gRlMudW50aWwoKCk9PiFlbmVtaWVzLnNvbWUoZT0+ZS51aWQ9PT0nVjEnKSwgNjAwMCwgZmFs'
        'c2UpOwogIHIuanVtcHNPdXQgPSB0Pj0wICYmIGljZW5Fc2NhcGVzPT09MTsKICByLm5vUGVuYWx0'
        'eSA9IHNjb3JlID49IHMwOwogIHIuZmVucmlzID0gZW5lbWllcy5zb21lKGU9PmUudWlkPT09J0sx'
        'JyAmJiBlLmltZz09PSdudGZjcmZlbnJpcycpOwogIHJldHVybiByO2ApOwoKc2NlbmFyaW8oJ0N5'
        'Y2xlIGNoYW5nZSAzMCAtPiAzMScsICdtPTMwJywgYAogIGNvbnN0IHIgPSB7fTsKICByLnN0YXJ0'
        'c1Zhc3VkYW4gPSBwbGF5ZXIuc2hpcD09PSdmaXRvdGgnICYmIEFMTFlfRkFDX09OLnZhc3VkYW49'
        'PT10cnVlOwogIHNjb3JlID0gOTAwMDA7CiAgLy8gQ2xlYXIgd2F2ZSAzMCBieSBmb3JjZSBhbmQg'
        'bGV0IHRoZSBqdW1wIGhhcHBlbi4KICBmb3IobGV0IGs9MDtrPDYwICYmIHdhdmU9PT0zMDtrKysp'
        'eyBmb3IoY29uc3QgZSBvZiBlbmVtaWVzKSBpZighKGUud2FycD4wKSAmJiAhZS5pbnZ1bG4pIGUu'
        'aHA9MDsgRlMuc3RlcCgyMDApOyB9CiAgci53YXZlID0gd2F2ZTsKICByLm15cm1pZG9uID0gcGxh'
        'eWVyLnNoaXA9PT0nZmlteXJtaWRvbic7CiAgci5vbmVIdWxsID0gc2hpcFVubG9ja2VkPT09MSAm'
        'JiBjeWNsZUJhc2U9PT1zY29yZSAtIChzY29yZS1jeWNsZUJhc2UpOwogIHIuYmFzZVNldCA9IGN5'
        'Y2xlQmFzZSA+PSA5MDAwMDsKICByLnRlcnJhbiA9IEFMTFlfRkFDX09OLnRlcnJhbj09PXRydWUg'
        'JiYgQUxMWV9GQUNfT04udmFzdWRhbj09PWZhbHNlOwogIHJldHVybiByO2ApOwoKc2NlbmFyaW8o'
        'J00xMyBib3RoIHRyYW5zcG9ydHMgb24gdGltZScsICdtPTEzJywgYAogIEZTLnN0ZXAoMzAwKTsK'
        'ICByZXR1cm4ge2JvdGhUcmFuc3BvcnRzOiBhbGxpZXMuZmlsdGVyKGE9PmEudWlkPT09J1QxJyku'
        'bGVuZ3RoPT09Mn07YCk7CgovLyBFdmVyeSB3cml0dGVuIG1pc3Npb24gaGFzIHRvIGNvbWUgdG8g'
        'YW4gZW5kIHdoZW4gaXRzIGVuZW1pZXMgZ28gZG93biwKLy8gd2l0aCBub3RoaW5nIHRocm93biBv'
        'biB0aGUgd2F5LiBFbmVteSBzaGlwcyBhcmUgY2xlYXJlZCBldmVyeSB0d28gc2Vjb25kcwovLyBv'
        'bmNlIHRoZXkgYXJlIG91dCBvZiB0aGVpciB2b3J0ZXggLSBhIHBsYXllciB3aG8gaGl0cyBldmVy'
        'eXRoaW5nLgovLyBTY2FuIG1pc3Npb25zICgxMiwgMjMpIG5lZWQgdGhlIHBsYXllciB0byBmbHkg'
        'dGhlIHNjYW4gYW5kIGFyZSBsZWZ0IG91dC4KZm9yKGxldCBtPTE7bTw9MzY7bSsrKSBpZihtIT09'
        'MTIgJiYgbSE9PTIzKSBzY2VuYXJpbygnTScgKyBTdHJpbmcobSkucGFkU3RhcnQoMiwnMCcpICsg'
        'JyBwbGF5cyB0byB0aGUgZW5kJywgJ209JyArIG0sIGAKICBjb25zdCB0ID0gRlMudW50aWwoKCk9'
        'PndhdmVPdmVyLCA0MDAwMCwgZmFsc2UsIHRydWUpOwogIElURU1TLmxlbmd0aCA9IDA7ICAgICAv'
        'LyBwaWNrdXBzIGhvbGQgdGhlIGp1bXAgb3BlbiB1bnRpbCB0aGV5IGV4cGlyZQogIGNvbnN0IGog'
        'PSBGUy51bnRpbCgoKT0+d2F2ZSA9PT0gJHttfSsxLCA2MDAwLCBmYWxzZSwgZmFsc2UpOwogIHJl'
        'dHVybiB7ZW5kczogdCA+PSAwLCBuZXh0V2F2ZTogaiA+PSAwfTtgKTsKCnNjZW5hcmlvKCdQaWNr'
        'dXBzIGFyZSBkcmF3biB0byB0aGUgc2hpcCcsICdtPTEnLCBgCiAgRlMuc3RlcCgyMDApOwogIGNv'
        'bnN0IHIgPSB7fTsKICB0aWNrZXRzLmNydWlzZXIgPSAwOwogIElURU1TLnB1c2goe3g6cGxheWVy'
        'LngrMTAwLCB5OnBsYXllci55LCB2eDpJVEVNX0RSSUZULCB2eTowLCBraW5kOidjcnVpc2VyJywg'
        'bGlmZTo1MDAwfSk7CiAgSVRFTVMucHVzaCh7eDpwbGF5ZXIueCs0MDAsIHk6cGxheWVyLnkrMTAw'
        'LCB2eDowLCB2eTowLCBraW5kOidyZXBhaXInLCBsaWZlOjUwMDB9KTsKICBjb25zdCBmYXIgPSBJ'
        'VEVNU1sxXTsKICBGUy5zdGVwKDYwKTsKICByLm5lYXJPbmVDb2xsZWN0ZWQgPSB0aWNrZXRzLmNy'
        'dWlzZXI9PT0xOwogIHIuZmFyT25lTGVmdEFsb25lID0gSVRFTVMuaW5jbHVkZXMoZmFyKSAmJiAh'
        'ZmFyLmNhdWdodDsKICAvLyBDYXVnaHQsIGl0IGtlZXBzIGZvbGxvd2luZyBldmVuIGlmIHRoZSBz'
        'aGlwIHB1bGxzIGF3YXkuCiAgcGxheWVyLnggPSAxMDA7IHBsYXllci55ID0gMjUwOwogIElURU1T'
        'LnB1c2goe3g6MjEwLCB5OjI1MCwgdng6MCwgdnk6MCwga2luZDonY29ydmV0dGUnLCBsaWZlOjUw'
        'MDB9KTsKICBjb25zdCBjID0gSVRFTVNbSVRFTVMubGVuZ3RoLTFdOwogIEZTLnN0ZXAoMSk7CiAg'
        'ci5jYXVnaHQgPSBjLmNhdWdodD09PXRydWU7CiAgbGV0IGdvdCA9IGZhbHNlOwogIGZvcihsZXQg'
        'az0wO2s8MjAwICYmICFnb3Q7aysrKXsgcGxheWVyLnggPSA2MDsgcGxheWVyLnkgPSAyNTA7IEZT'
        'LnN0ZXAoMSk7IGdvdCA9ICFJVEVNUy5pbmNsdWRlcyhjKTsgfQogIHIuZm9sbG93c0FuZEFycml2'
        'ZXMgPSBnb3Q7CiAgcmV0dXJuIHI7YCk7CgpzY2VuYXJpbygnVGl0bGU6IGZ1bGxzY3JlZW4gYnV0'
        'dG9uJywgJycsIGAKICBjb25zdCByID0ge307CiAgbGV0IGNhbGxzID0gMDsKICB0b2dnbGVGdWxs'
        'c2NyZWVuID0gZnVuY3Rpb24oKXsgY2FsbHMrKzsgfTsKICBkcmF3KCk7CiAgY29uc3QgYiA9IHdp'
        'bmRvdy5fdGl0bGVGc1JlY3Q7CiAgci5zaG93biA9ICEhYiAmJiBiLnggPj0gMCAmJiBiLnggKyBi'
        'LncgPD0gVyAmJiBiLnkgPj0gMCAmJiBiLnkgKyBiLmggPD0gSDsKICByLmNsZWFyT2ZUaGVUaXRs'
        'ZSA9ICEhYiAmJiBiLnkgKyBiLmggPCAxMjggLSA1NDsKICBjb25zdCBjciA9IENWUy5nZXRCb3Vu'
        'ZGluZ0NsaWVudFJlY3QoKTsKICBjb25zdCBjbGljayA9IChneCwgZ3kpPT57CiAgICBjb25zdCBl'
        'diA9IG5ldyBNb3VzZUV2ZW50KCdtb3VzZWRvd24nLCB7YnV0dG9uOjAsIGJ1YmJsZXM6dHJ1ZSwK'
        'ICAgICAgY2xpZW50WDogY3IubGVmdCArIGd4KmNyLndpZHRoL1csIGNsaWVudFk6IGNyLnRvcCAr'
        'IGd5KmNyLmhlaWdodC9IfSk7CiAgICBDVlMuZGlzcGF0Y2hFdmVudChldik7CiAgICBDVlMuZGlz'
        'cGF0Y2hFdmVudChuZXcgTW91c2VFdmVudCgnbW91c2V1cCcsIHtidXR0b246MCwgYnViYmxlczp0'
        'cnVlfSkpOwogIH07CiAgY2xpY2soYi54ICsgYi53LzIsIGIueSArIGIuaC8yKTsKICByLmJ1dHRv'
        'blN3aXRjaGVzID0gY2FsbHM9PT0xOwogIHIuYW5kRG9lc05vdFN0YXJ0VGhlUnVuID0gR1M9PT0n'
        'dGl0bGUnOwogIGRvY3VtZW50LmRpc3BhdGNoRXZlbnQobmV3IEtleWJvYXJkRXZlbnQoJ2tleWRv'
        'd24nLCB7Y29kZTonS2V5Rid9KSk7CiAgZG9jdW1lbnQuZGlzcGF0Y2hFdmVudChuZXcgS2V5Ym9h'
        'cmRFdmVudCgna2V5dXAnLCB7Y29kZTonS2V5Rid9KSk7CiAgci5mS2V5T25UaGVUaXRsZSA9IGNh'
        'bGxzPT09MiAmJiBHUz09PSd0aXRsZSc7CiAgY2xpY2soVy8yLCBILzIpOwogIHIuZWxzZXdoZXJl'
        'U3RhcnRzVGhlUnVuID0gR1M9PT0ncGxheWluZycgJiYgY2FsbHM9PT0yOwogIHJldHVybiByO2As'
        'IHRydWUpOwoKc2NlbmFyaW8oJ0hvTCBzdGFydCB1bmNoYW5nZWQnLCAnbT0xJywgYAogIHJldHVy'
        'biB7d2F2ZTogd2F2ZSwgdGhvdGg6IHBsYXllci5zaGlwPT09J2ZpdG90aCcsIHZhc3VkYW5DYWxs'
        'OiBBTExZX0ZBQ19PTi52YXN1ZGFuPT09dHJ1ZSAmJiBBTExZX0ZBQ19PTi50ZXJyYW49PT1mYWxz'
        'ZX07YCk7CgovLyDilIDilIAgUnVubmVyIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKU'
        'gOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAooYXN5bmMoKT0+ewogIGNvbnN0'
        'IGJyb3dzZXIgPSBhd2FpdCBjaHJvbWl1bS5sYXVuY2goKTsKICBsZXQgZmFpbHMgPSAwOwogIGNv'
        'bnN0IG9ubHkgPSBwcm9jZXNzLmFyZ3ZbNF07CiAgZm9yKGNvbnN0IHNjIG9mIHNjZW5hcmlvcyl7'
        'CiAgICBpZihvbmx5ICYmIHNjLm5hbWUuaW5kZXhPZihvbmx5KTwwKSBjb250aW51ZTsKICAgIGNv'
        'bnN0IHBhZ2UgPSBhd2FpdCBicm93c2VyLm5ld1BhZ2UoKTsKICAgIGNvbnN0IGVycnMgPSBbXTsK'
        'ICAgIHBhZ2Uub24oJ3BhZ2VlcnJvcicsIGU9PmVycnMucHVzaChTdHJpbmcoZS5tZXNzYWdlfHxl'
        'KSkpOwogICAgYXdhaXQgcGFnZS5nb3RvKCdmaWxlOi8vJyArIHRtcCArICc/JyArIHNjLnF1ZXJ5'
        'KTsKICAgIGF3YWl0IHBhZ2Uud2FpdEZvclRpbWVvdXQoMzAwKTsKICAgIGxldCByZXM7CiAgICB0'
        'cnl7CiAgICAgIHJlcyA9IGF3YWl0IHBhZ2UuZXZhbHVhdGUoSEVMUEVSUyArIGBcbkZTLmZha2VJ'
        'bWFnZXMoKTtgICsgKHNjLm5vTGF1bmNoID8gJycgOiAnIGxhdW5jaEdhbWUoKTsnKSArIGBcbihm'
        'dW5jdGlvbigpeyR7c2MuYm9keX19KSgpYCk7CiAgICB9Y2F0Y2goZSl7IHJlcyA9IG51bGw7IGVy'
        'cnMucHVzaChTdHJpbmcoZS5tZXNzYWdlfHxlKSk7IH0KICAgIGNvbnNvbGUubG9nKHNjLm5hbWUg'
        'KyAnICAoPycgKyBzYy5xdWVyeSArICcpJyk7CiAgICBpZihyZXMpIGZvcihjb25zdCBbayx2XSBv'
        'ZiBPYmplY3QuZW50cmllcyhyZXMpKXsKICAgICAgY29uc3QgZ29vZCA9ICh0eXBlb2Ygdj09PSdi'
        'b29sZWFuJykgPyB2IDogdHJ1ZTsKICAgICAgaWYoIWdvb2QpIGZhaWxzKys7CiAgICAgIGNvbnNv'
        'bGUubG9nKChnb29kID8gJyAgb2sgICAgJyA6ICcgIEZBSUwgICcpICsgayArICh0eXBlb2Ygdj09'
        'PSdib29sZWFuJyA/ICcnIDogJyA9ICcgKyBKU09OLnN0cmluZ2lmeSh2KSkpOwogICAgfQogICAg'
        'aWYoZXJycy5sZW5ndGgpeyBmYWlscysrOyBjb25zb2xlLmxvZygnICBGQUlMICBwYWdlIGVycm9y'
        'czpcbiAgICAnICsgZXJycy5zbGljZSgwLDQpLmpvaW4oJ1xuICAgICcpKTsgfQogICAgYXdhaXQg'
        'cGFnZS5jbG9zZSgpOwogIH0KICBhd2FpdCBicm93c2VyLmNsb3NlKCk7CiAgZnMudW5saW5rU3lu'
        'Yyh0bXApOwogIGNvbnNvbGUubG9nKCdcbicgKyAoZmFpbHMgPyBmYWlscyArICcgRkFJTEVEJyA6'
        'ICdhbGwgcGFzc2VkJykpOwogIHByb2Nlc3MuZXhpdChmYWlscyA/IDEgOiAwKTsKfSkoKTsK'
    ),
}
for name, data in TEST_FILES.items():
    open(name, 'wb').write(base64.b64decode(data))
print("v131 applied: M31 turns in place, fullscreen button on the title, checks updated. Now run: python3 assemble.py 131")
