#!/usr/bin/env python3
"""FS3 v188 - capital hulls in FS2 ratio, subsystems where the models have them.

    Hulls       Within each class a capital ship has the hull ratio of
                ships.tbl (Silvio, way A); the class average stays what it
                was, and both sides get the same. Cruisers: Fenris 0.27,
                Aten 0.49, Cain 0.54, Leviathan 0.95, Aeolus 1.03,
                Rakshasa 1.08, Mentu 1.62, Lilith 2.03 of the class value.
                Destroyers: Orion/Hecate/Ravana 0.84, Typhon 1.01,
                Hatshepsut 1.13, Demon 1.34. Corvettes are all 80000 in
                FS2 and stay as they are. AWACS, Iceni, platforms and the
                big ships keep their own tuning. The support menu shows the
                hull the ship will really have.
    Missions    Where the protected ship now fell every time, that one ship
                keeps its old hull in that mission: the Aten in M16 (x2),
                the Orion in M62 and M67 (x1.2).
    Subsystems  Positions from the MediaVP models (.pof), laid onto the
                sprites; today's sizes. A circle that would sit deep inside
                the hull moves to the nearest edge, where shots land.
                Overlapping circles are pushed apart, and a hit goes to the
                nearest centre.

Needs v187b. Edits src/ and hlp_mounts_final.json in place, updates the
simulations. Run assemble.py afterwards.
"""
import base64
import os
import sys

if "v187b" not in open("src/56_banks.js", encoding="utf-8").read():
    sys.exit("Abbruch: erst v187b einspielen.")
if "FS2_CAP_HULL" in open("src/50_combat.js", encoding="utf-8").read():
    sys.exit("Abbruch: v188 ist schon eingespielt.")

F = {}
def load(p):
    if p not in F: F[p] = open(p, encoding="utf-8").read()
def rep(p, old, new, count=1):
    load(p)
    n = F[p].count(old)
    if n != count:
        sys.exit("Abbruch (%s): Suchtext %d-mal gefunden, erwartet %d.\n%s" % (p, n, count, old[:200]))
    F[p] = F[p].replace(old, new)
rep('src/30_waves.js',
    "     ]},\n\n  16:{name:'The Mutiny', fac:'hol', o:'guard', live:5, u:[\n       {id:'A1', c:'cr', n:1, spr:'craten', side:'ally'},\n       {id:'A2', c:'fi', n:2, side:'ally'},\n       {id:'E1', c:'fi', n:3},\n       {id:'E2', c:'fi', n:3, wait:true}\n",
    "     ]},\n\n  16:{name:'The Mutiny', fac:'hol', o:'guard', live:5, u:[\n       // v188: the Aten has her FS2 hull now, half a cruiser's. She is the\n       // ship to guard here, so this one keeps the hull she had (x2).\n       {id:'A1', c:'cr', n:1, spr:'craten', side:'ally', hp:2},\n       {id:'A2', c:'fi', n:2, side:'ally'},\n       {id:'E1', c:'fi', n:3},\n       {id:'E2', c:'fi', n:3, wait:true}\n")
rep('src/30_waves.js',
    "       // One GTVA destroyer against Shivan cruisers coming through the\n       // portal, two at a time (Silvio). Her hangar is open: the Terran tab.\n       {id:'P1', c:'in', n:1, spr:'inknossos45deg', invuln:true, edge:0.5, y:275},\n       {id:'A1', c:'de', n:1, spr:'deorionright', side:'ally', x:150, y:270, still:true,\n        guard:true, callsOk:true},\n       // No extra hull of their own (Silvio, v167): the step every 20 waves\n       // (x1.75 from 61) is hard enough.\n       {id:'K1', c:'cr', n:1, spr:'crcain',     t:3,  noFlee:true},\n",
    "       // One GTVA destroyer against Shivan cruisers coming through the\n       // portal, two at a time (Silvio). Her hangar is open: the Terran tab.\n       {id:'P1', c:'in', n:1, spr:'inknossos45deg', invuln:true, edge:0.5, y:275},\n       // v188: the Orion's FS2 hull is 0.84 of the class; the ship to\n       // protect keeps the hull she had (x1.2).\n       {id:'A1', c:'de', n:1, spr:'deorionright', side:'ally', x:150, y:270, still:true,\n        guard:true, callsOk:true, hp:1.2},\n       // No extra hull of their own (Silvio, v167): the step every 20 waves\n       // (x1.75 from 61) is hard enough.\n       {id:'K1', c:'cr', n:1, spr:'crcain',     t:3,  noFlee:true},\n")
rep('src/30_waves.js',
    "       // Rahu miners are hard to grind down with guns. TAG them and the\n       // Orion's beams find them in the gas. The Deimos is there to rearm.\n       // A miner goes up with a very big blast - keep clear.\n       {id:'A1', c:'de', n:1, spr:'deorionright', side:'ally', x:130, y:250, still:true,\n        guard:true, callsOk:true},\n       {id:'A2', c:'co', n:1, spr:'codeimos', side:'ally', x:230, y:440, still:true, callsOk:true},\n       {id:'G1', c:'fr', n:1, spr:'gmrahu', x:520, y:150, still:true, hp:3},\n       {id:'G2', c:'fr', n:1, spr:'gmrahu', x:650, y:260, still:true, hp:3},\n",
    "       // Rahu miners are hard to grind down with guns. TAG them and the\n       // Orion's beams find them in the gas. The Deimos is there to rearm.\n       // A miner goes up with a very big blast - keep clear.\n       // v188: as in M62, the Orion keeps the hull she had (x1.2).\n       {id:'A1', c:'de', n:1, spr:'deorionright', side:'ally', x:130, y:250, still:true,\n        guard:true, callsOk:true, hp:1.2},\n       {id:'A2', c:'co', n:1, spr:'codeimos', side:'ally', x:230, y:440, still:true, callsOk:true},\n       {id:'G1', c:'fr', n:1, spr:'gmrahu', x:520, y:150, still:true, hp:3},\n       {id:'G2', c:'fr', n:1, spr:'gmrahu', x:650, y:260, still:true, hp:3},\n")
rep('src/40_world.js',
    "    const cr={type:'cruiser',img:spr,faction:typeFac(type),\n      // Cruisers screen the heavier ships, so they take the forward band.\n      // This used to be the rearmost of the three.\n      pts:400,x:W-20,y,warpX:W-20,warpY:y,targetX:W-118-Math.random()*40,hp:capHull(HULL.cruiser),maxHp:capHull(HULL.cruiser),\n      vy:(Math.random()<.5?1:-1)*(0.25+Math.random()*0.3),\n      minY:HUD_H+60,maxY:H-60,fT:80,fR:70,pat:0,dead:false,sc,warp:190};\n    initBeams(cr);return cr;}\n",
    "    const cr={type:'cruiser',img:spr,faction:typeFac(type),\n      // Cruisers screen the heavier ships, so they take the forward band.\n      // This used to be the rearmost of the three.\n      pts:400,x:W-20,y,warpX:W-20,warpY:y,targetX:W-118-Math.random()*40,hp:capHull(HULL.cruiser*capHullF(spr)),maxHp:capHull(HULL.cruiser*capHullF(spr)),\n      vy:(Math.random()<.5?1:-1)*(0.25+Math.random()*0.3),\n      minY:HUD_H+60,maxY:H-60,fT:80,fR:70,pat:0,dead:false,sc,warp:190};\n    initBeams(cr);return cr;}\n")
rep('src/40_world.js',
    '      // Haelfte eines 195 Bildpunkte breiten Rumpfs lag ausserhalb des\n      // Feldes, waehrend das verbuendete Gegenstueck ganz zu sehen war.\n      targetX:W-150-Math.random()*34,\n      hp:capHull(HULL.corvette),maxHp:capHull(HULL.corvette),\n      vy:(Math.random()<.5?1:-1)*(0.2+Math.random()*0.3),\n      minY:HUD_H+60,maxY:H-60,fT:80,fR:70,pat:0,dead:false,sc,warp:220};\n    initBeams(ent); return ent;\n',
    '      // Haelfte eines 195 Bildpunkte breiten Rumpfs lag ausserhalb des\n      // Feldes, waehrend das verbuendete Gegenstueck ganz zu sehen war.\n      targetX:W-150-Math.random()*34,\n      hp:capHull(HULL.corvette*capHullF(spr)),maxHp:capHull(HULL.corvette*capHullF(spr)),\n      vy:(Math.random()<.5?1:-1)*(0.2+Math.random()*0.3),\n      minY:HUD_H+60,maxY:H-60,fT:80,fR:70,pat:0,dead:false,sc,warp:220};\n    initBeams(ent); return ent;\n')
rep('src/40_world.js',
    "    const ent={type:'destroyer',img:spr,faction:typeFac(type),\n      pts:1200,x:W-80,y,warpX:W-80,warpY:y,\n      targetX:W-230-Math.random()*34,\n      hp:capHull(HULL.destroyer),maxHp:capHull(HULL.destroyer),\n      vy:(Math.random()<.5?1:-1)*(0.15+Math.random()*0.2),\n      minY:HUD_H+46,maxY:H-46,fT:100,fR:80,pat:0,dead:false,sc,warp:260};\n    initBeams(ent); return ent;\n",
    "    const ent={type:'destroyer',img:spr,faction:typeFac(type),\n      pts:1200,x:W-80,y,warpX:W-80,warpY:y,\n      targetX:W-230-Math.random()*34,\n      hp:capHull(HULL.destroyer*capHullF(spr)),maxHp:capHull(HULL.destroyer*capHullF(spr)),\n      vy:(Math.random()<.5?1:-1)*(0.15+Math.random()*0.2),\n      minY:HUD_H+46,maxY:H-46,fT:100,fR:80,pat:0,dead:false,sc,warp:260};\n    initBeams(ent); return ent;\n")
rep('src/40_world.js',
    '  return false;\n}\n\nfunction mkAlly(id){\n  const d = ALLY_DEFS[id]; if(!d) return null;\n  const spr = d.spr; if(!spr) return null;\n',
    "  return false;\n}\n\n// What an escort's hull is, for the ship and for the support menu alike.\nfunction allyHull(d){\n  return capHull(HULL[d.cls]*(d.colossus?COLOSSUS_HULL_MULT:1)*(d.hullMul||1)*capHullF(d.spr));\n}\nfunction mkAlly(id){\n  const d = ALLY_DEFS[id]; if(!d) return null;\n  const spr = d.spr; if(!spr) return null;\n")
rep('src/40_world.js',
    '    img:spr, faction:d.fac,\n    x:cx, y:y, warpX:cx, warpY:y, targetX:cx,\n    // hullMul: a lighter hull than the class gives (the Charybdis, v166).\n    hp:capHull(HULL[d.cls]*(d.colossus?COLOSSUS_HULL_MULT:1)*(d.hullMul||1)),\n    maxHp:capHull(HULL[d.cls]*(d.colossus?COLOSSUS_HULL_MULT:1)*(d.hullMul||1)),\n    vy:d.colossus?0:(Math.random()<.5?1:-1)*(0.2+Math.random()*0.25),\n    minY:d.colossus?y:HUD_H+geo.mar, maxY:d.colossus?y:H-geo.mar,\n    fT:60, fR:70, pat:0, dead:false, sc:colSc, ang:0,\n',
    '    img:spr, faction:d.fac,\n    x:cx, y:y, warpX:cx, warpY:y, targetX:cx,\n    // hullMul: a lighter hull than the class gives (the Charybdis, v166).\n    // capHullF: the FS2 ratio within the class (v188).\n    hp:allyHull(d),\n    maxHp:allyHull(d),\n    vy:d.colossus?0:(Math.random()<.5?1:-1)*(0.2+Math.random()*0.25),\n    minY:d.colossus?y:HUD_H+geo.mar, maxY:d.colossus?y:H-geo.mar,\n    fT:60, fR:70, pat:0, dead:false, sc:colSc, ang:0,\n')
rep('src/50_combat.js',
    '  return {x:e.x+px*ca-py*sa, y:e.y+px*sa+py*ca};\n}\n\nfunction subAt(e, hx, hy){\n  if(!e.subs || hx==null) return null;\n  for(const s of e.subs){\n    if(s.dead) continue;\n    const p = subPos(e, s);\n    const dx = hx-p.x, dy = hy-p.y;\n    const rr = subRadius(e, s);\n    if(dx*dx+dy*dy <= rr*rr) return s;\n  }\n  return null;\n}\n\n// Applies a hit that may have landed on a subsystem. Returns the damage\n',
    '  return {x:e.x+px*ca-py*sa, y:e.y+px*sa+py*ca};\n}\n\n// Where two circles overlap, the hit goes to the subsystem whose centre is\n// nearest, not to whichever comes first in the list (v188).\nfunction subAt(e, hx, hy){\n  if(!e.subs || hx==null) return null;\n  let best = null, bd = Infinity;\n  for(const s of e.subs){\n    if(s.dead) continue;\n    const p = subPos(e, s);\n    const dx = hx-p.x, dy = hy-p.y;\n    const rr = subRadius(e, s), d2 = dx*dx+dy*dy;\n    if(d2 <= rr*rr && d2 < bd){ bd = d2; best = s; }\n  }\n  return best;\n}\n\n// Applies a hit that may have landed on a subsystem. Returns the damage\n')
rep('src/50_combat.js',
    '}\n// Small craft grow too since v185 (smallStats), as the player always did.\nfunction capHull(v){ return Math.round(v*cycleMult()); }\n\nconst HULL = {\n  fighter:   48,     // vorher 24\n',
    "}\n// Small craft grow too since v185 (smallStats), as the player always did.\nfunction capHull(v){ return Math.round(v*cycleMult()); }\n// v188 (Silvio, way A): capital ships keep the hull ratio FreeSpace gives\n// them within their class. The class value below stays the average, so a\n// class as a whole is as tough as before; inside it a Fenris is a quarter\n// of a Lilith, as in ships.tbl. Same for both sides. Hulls not listed here\n// (the AWACS, the Iceni, platforms, the big ships) keep their own tuning.\nconst FS2_CAP_HULL = {\n  cr: {aeolus:38000, aten:18000, cain:20000, fenris:10000, leviathan:35000, lilith:75000, mentu:60000, rakshasa:40000},\n  co: {deimos:80000, sobek:80000, moloch:80000},\n  de: {orion:100000, hecate:100000, ravana:100000, typhon:120000, hatshepsut:135000, demon:160000}\n};\nconst CAP_HULL_F = (function(){\n  const f = {};\n  for(const c in FS2_CAP_HULL){\n    const t = FS2_CAP_HULL[c], names = Object.keys(t);\n    const mean = names.reduce(function(s, n){ return s + t[n]; }, 0) / names.length;\n    for(const n of names) f[c + n] = t[n] / mean;\n  }\n  return f;\n})();\n// The factor for a sprite key: 'ntfcrfenris' and 'crfenris' are one hull,\n// 'deorionleft' and 'deorionright' are the Orion.\nfunction capHullF(img){\n  if(!img) return 1;\n  let k = img.indexOf('ntf') === 0 ? img.slice(3) : img;\n  k = k.replace(/(left|right)$/, '');\n  return CAP_HULL_F[k] || 1;\n}\n\nconst HULL = {\n  fighter:   48,     // vorher 24\n")
rep('src/70_ui.js',
    "\n  let sub;\n  if(d.colossus)                sub = COLOSSUS_TIME+' s on station, then she jumps out';\n  else if(d.cls==='destroyer')  sub = 'DESTROYER  -  HULL '+capHull(HULL[d.cls])+'  -  WINGS';\n  else                          sub = d.cls.toUpperCase()+'  -  HULL '+capHull(HULL[d.cls]);\n  ctx.fillStyle = TH('textDim'); ctx.font = thValue(9, false);\n  ctx.fillText(thFit(sub, textW), x+CM_NAME, y+27);\n\n",
    "\n  let sub;\n  if(d.colossus)                sub = COLOSSUS_TIME+' s on station, then she jumps out';\n  // The hull the ship will really have (v188: FS2 ratio within the class).\n  else if(d.cls==='destroyer')  sub = 'DESTROYER  -  HULL '+allyHull(d)+'  -  WINGS';\n  else                          sub = d.cls.toUpperCase()+'  -  HULL '+allyHull(d);\n  ctx.fillStyle = TH('textDim'); ctx.font = thValue(9, false);\n  ctx.fillText(thFit(sub, textW), x+CM_NAME, y+27);\n\n")
rep('callsim.js',
    '  // The practice log is not what is tested here.\n  function plogCall(){} function plogRefine(){}\n  function capHull(v){ return Math.round(v); }\n  function allyReady(){ return true; }\n  function allyAffordable(id){ return affordAll; }\n  function mkAlly(id){ return {id:id}; }\n',
    '  // The practice log is not what is tested here.\n  function plogCall(){} function plogRefine(){}\n  function capHull(v){ return Math.round(v); }\n  function allyHull(d){ return capHull(HULL[d.cls]); }\n  function allyReady(){ return true; }\n  function allyAffordable(id){ return affordAll; }\n  function mkAlly(id){ return {id:id}; }\n')
rep('fieldsim.js',
    "scenario('HoL start unchanged', 'm=1', `\n  return {wave: wave, thoth: player.ship==='fitoth', vasudanCall: ALLY_FAC_ON.vasudan===true && ALLY_FAC_ON.terran===false};`);\n\n// ── Runner ─────────────────────────────────────────────────────────────\n(async()=>{\n  const browser = await chromium.launch();\n",
    "scenario('HoL start unchanged', 'm=1', `\n  return {wave: wave, thoth: player.ship==='fitoth', vasudanCall: ALLY_FAC_ON.vasudan===true && ALLY_FAC_ON.terran===false};`);\n\nscenario('v188: capital hulls in FS2 ratio, subsystems from the models', 'm=31', `\n  const r = {};\n  const mk = (t, spr) => { const e = mkEnemy(t, spr, 250); return e; };\n  const fen = mk('cr_ntf', 'ntfcrfenris'), lil = mk('cr_sh', 'crlilith'), aeo = mk('cr_ntf', 'ntfcraeolus');\n  // ships.tbl: Lilith 75000, Fenris 10000 - the same ratio here\n  r.fenrisQuarterOfLilith = Math.abs(fen.maxHp/lil.maxHp - 10000/75000) < 0.01;\n  // the class keeps its average: the eight cruisers average the old value\n  const names = ['craeolus','craten','crcain','crfenris','crleviathan','crlilith','crmentu','crrakshasa'];\n  const avg = names.reduce((s,n)=>s+capHullF(n),0)/names.length;\n  r.classAverageKept = Math.abs(avg-1) < 1e-9;\n  r.ntfSameAsTerran = capHullF('ntfcrfenris') === capHullF('crfenris') && capHullF('deorionleft') === capHullF('deorionright');\n  r.othersUntouched = capHullF('casetekh')===1 && capHullF('coiceni')===1 && capHullF('sdcolossus')===1 && capHullF('sgmjolnir')===1;\n  // the escort has the hull the support menu shows\n  const a = mkAlly('ter_fenris');\n  r.menuShowsRealHull = !!a && a.maxHp === allyHull(ALLY_DEFS.ter_fenris) && a.maxHp < capHull(HULL.cruiser);\n  // subsystems: where two circles overlap, the nearer centre takes the hit\n  const e = aeo; e.x = 400; e.y = 250; e.warp = 0; initSubsystems(e);\n  const s0 = e.subs[0], s1 = e.subs[1];\n  const p0 = subPos(e, s0), p1 = subPos(e, s1);\n  const mx = p0.x + (p1.x-p0.x)*0.3, my = p0.y + (p1.y-p0.y)*0.3;\n  const big = s0.r; s0.r = s1.r = 1;   // make them overlap\n  r.nearestTakesHit = subAt(e, mx, my) === s0;\n  s0.r = big; s1.r = big;\n  // the Aten's weapons sit forward, by the bow, as in the model\n  r.atenWeaponsForward = (MOUNTS.craten.subs.find(s=>s.id==='weapons').dx > 0.5);\n  return r;`);\n\n// ── Runner ─────────────────────────────────────────────────────────────\n(async()=>{\n  const browser = await chromium.launch();\n")
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.117,\n        "dy": 0.141,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.358,\n        "dy": -0.884,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.67,\n        "dy": 0.193,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.05,\n        "dy": -0.347,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.907,\n        "dy": -0.199,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.084,\n        "dy": 0.205,\n        "r": 0.0741\n      },\n      {\n        "id": "sensors",\n        "dx": 0.777,\n        "dy": 0.149,\n        "r": 0.0741\n      },\n      {\n        "id": "navigation",\n        "dx": 0.102,\n        "dy": -0.175,\n        "r": 0.0741\n      },\n      {\n        "id": "communication",\n        "dx": 0.211,\n        "dy": 0.43,\n        "r": 0.0741\n      },\n      {\n        "id": "engines",\n        "dx": -0.879,\n        "dy": -0.218,\n        "r": 0.0741\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.638,\n        "dy": 0.292,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.272,\n        "dy": -0.357,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.385,\n        "dy": -0.257,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.91,\n        "dy": 0.05,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.852,\n        "dy": -0.376,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.9,\n        "dy": -0.019,\n        "r": 0.0723\n      },\n      {\n        "id": "sensors",\n        "dx": -0.703,\n        "dy": 0.311,\n        "r": 0.0723\n      },\n      {\n        "id": "navigation",\n        "dx": -0.388,\n        "dy": -0.028,\n        "r": 0.0723\n      },\n      {\n        "id": "communication",\n        "dx": 0.035,\n        "dy": -0.123,\n        "r": 0.0723\n      },\n      {\n        "id": "engines",\n        "dx": -0.863,\n        "dy": -0.21,\n        "r": 0.0723\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.14,\n        "dy": -0.483,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.794,\n        "dy": -0.517,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.027,\n        "dy": 0.538,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.371,\n        "dy": -0.772,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.651,\n        "dy": 0.204,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.457,\n        "dy": -0.629,\n        "r": 0.0308\n      },\n      {\n        "id": "sensors",\n        "dx": 0.938,\n        "dy": 0.4,\n        "r": 0.0308\n      },\n      {\n        "id": "navigation",\n        "dx": -0.053,\n        "dy": -0.402,\n        "r": 0.0308\n      },\n      {\n        "id": "communication",\n        "dx": 0.964,\n        "dy": -0.154,\n        "r": 0.0308\n      },\n      {\n        "id": "engines",\n        "dx": -0.374,\n        "dy": 0.8,\n        "r": 0.0308\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.716,\n        "dy": 0.628,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.402,\n        "dy": -0.357,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.212,\n        "dy": 0.585,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.63,\n        "dy": -0.323,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.047,\n        "dy": 0.877,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.137,\n        "dy": -0.848,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.609,\n        "dy": 0.665,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.908,\n        "dy": -0.425,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.684,\n        "dy": -0.47,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.346,\n        "dy": 0.796,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.243,\n        "dy": -0.505,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.36,\n        "dy": 0.043,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.509,\n        "dy": -0.574,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.039,\n        "dy": 0.039,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.765,\n        "dy": -0.483,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.409,\n        "dy": -0.497,\n        "r": 0.0306\n      },\n      {\n        "id": "sensors",\n        "dx": 0.943,\n        "dy": -0.123,\n        "r": 0.0306\n      },\n      {\n        "id": "navigation",\n        "dx": -0.023,\n        "dy": -0.388,\n        "r": 0.0306\n      },\n      {\n        "id": "communication",\n        "dx": -0.313,\n        "dy": -0.535,\n        "r": 0.0306\n      },\n      {\n        "id": "engines",\n        "dx": 0.434,\n        "dy": 0.203,\n        "r": 0.0306\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.048,\n        "dy": 0.213,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.163,\n        "dy": 0.649,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.385,\n        "dy": 0.197,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.669,\n        "dy": 0.814,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.537,\n        "dy": -0.076,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.262,\n        "dy": 0.572,\n        "r": 0.0343\n      },\n      {\n        "id": "sensors",\n        "dx": 0.86,\n        "dy": 0.708,\n        "r": 0.0343\n      },\n      {\n        "id": "navigation",\n        "dx": -0.019,\n        "dy": 0.266,\n        "r": 0.0343\n      },\n      {\n        "id": "communication",\n        "dx": 0.576,\n        "dy": 0.331,\n        "r": 0.0343\n      },\n      {\n        "id": "engines",\n        "dx": -0.541,\n        "dy": -0.069,\n        "r": 0.0343\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.494,\n        "dy": -0.617,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.621,\n        "dy": 0.68,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.046,\n        "dy": 0.722,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.129,\n        "dy": -0.639,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.937,\n        "dy": -0.123,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.893,\n        "dy": -0.336,\n        "r": 0.0571\n      },\n      {\n        "id": "sensors",\n        "dx": 0.545,\n        "dy": -0.565,\n        "r": 0.0571\n      },\n      {\n        "id": "navigation",\n        "dx": -0.159,\n        "dy": -0.654,\n        "r": 0.0571\n      },\n      {\n        "id": "communication",\n        "dx": 0.475,\n        "dy": 0.666,\n        "r": 0.0571\n      },\n      {\n        "id": "engines",\n        "dx": -0.204,\n        "dy": 0.493,\n        "r": 0.0571\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.432,\n        "dy": -0.282,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.107,\n        "dy": -0.862,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.058,\n        "dy": 0.817,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.418,\n        "dy": 0.555,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.767,\n        "dy": -0.614,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.839,\n        "dy": 0.57,\n        "r": 0.0638\n      },\n      {\n        "id": "sensors",\n        "dx": 0.168,\n        "dy": -0.408,\n        "r": 0.0638\n      },\n      {\n        "id": "navigation",\n        "dx": 0.604,\n        "dy": 0.33,\n        "r": 0.0638\n      },\n      {\n        "id": "communication",\n        "dx": -0.502,\n        "dy": 0.349,\n        "r": 0.0638\n      },\n      {\n        "id": "engines",\n        "dx": -0.305,\n        "dy": -0.562,\n        "r": 0.0638\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.147,\n        "dy": 0.835,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.384,\n        "dy": -0.905,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.344,\n        "dy": 0.574,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.35,\n        "dy": -0.23,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.808,\n        "dy": -0.155,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.162,\n        "dy": -0.061,\n        "r": 0.0723\n      },\n      {\n        "id": "sensors",\n        "dx": -0.17,\n        "dy": -0.284,\n        "r": 0.0723\n      },\n      {\n        "id": "navigation",\n        "dx": 0.639,\n        "dy": -0.861,\n        "r": 0.0723\n      },\n      {\n        "id": "communication",\n        "dx": -0.255,\n        "dy": 0.342,\n        "r": 0.0723\n      },\n      {\n        "id": "engines",\n        "dx": -0.464,\n        "dy": -0.162,\n        "r": 0.0723\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.142,\n        "dy": 0.33,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.332,\n        "dy": -0.217,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.246,\n        "dy": -0.221,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.048,\n        "dy": -0.688,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.86,\n        "dy": -0.298,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.24,\n        "dy": -0.565,\n        "r": 0.06\n      },\n      {\n        "id": "sensors",\n        "dx": 0.893,\n        "dy": -0.273,\n        "r": 0.06\n      },\n      {\n        "id": "navigation",\n        "dx": 0.471,\n        "dy": 0.238,\n        "r": 0.06\n      },\n      {\n        "id": "communication",\n        "dx": 0.817,\n        "dy": 0.085,\n        "r": 0.06\n      },\n      {\n        "id": "engines",\n        "dx": 0.062,\n        "dy": -0.361,\n        "r": 0.06\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.108,\n        "dy": 0.34,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.328,\n        "dy": -0.323,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.229,\n        "dy": -0.268,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.052,\n        "dy": -0.733,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.903,\n        "dy": -0.363,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.242,\n        "dy": -0.662,\n        "r": 0.06\n      },\n      {\n        "id": "sensors",\n        "dx": 0.895,\n        "dy": -0.352,\n        "r": 0.06\n      },\n      {\n        "id": "navigation",\n        "dx": 0.472,\n        "dy": 0.192,\n        "r": 0.06\n      },\n      {\n        "id": "communication",\n        "dx": 0.819,\n        "dy": 0.029,\n        "r": 0.06\n      },\n      {\n        "id": "engines",\n        "dx": 0.062,\n        "dy": -0.443,\n        "r": 0.06\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.365,\n        "dy": -0.913,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.13,\n        "dy": 0.791,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.352,\n        "dy": 0.582,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.356,\n        "dy": -0.271,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.781,\n        "dy": -0.149,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.162,\n        "dy": -0.049,\n        "r": 0.0723\n      },\n      {\n        "id": "sensors",\n        "dx": -0.17,\n        "dy": -0.274,\n        "r": 0.0723\n      },\n      {\n        "id": "navigation",\n        "dx": 0.639,\n        "dy": -0.851,\n        "r": 0.0723\n      },\n      {\n        "id": "communication",\n        "dx": -0.255,\n        "dy": 0.354,\n        "r": 0.0723\n      },\n      {\n        "id": "engines",\n        "dx": -0.464,\n        "dy": -0.151,\n        "r": 0.0723\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.483,\n        "dy": -0.341,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.411,\n        "dy": -0.693,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.069,\n        "dy": 0.3,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.008,\n        "dy": -0.858,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.828,\n        "dy": -0.033,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.22,\n        "dy": 0.47,\n        "r": 0.0513\n      },\n      {\n        "id": "sensors",\n        "dx": 0.598,\n        "dy": -0.317,\n        "r": 0.0513\n      },\n      {\n        "id": "navigation",\n        "dx": 0.083,\n        "dy": -0.749,\n        "r": 0.0513\n      },\n      {\n        "id": "communication",\n        "dx": 0.315,\n        "dy": -0.514,\n        "r": 0.0513\n      },\n      {\n        "id": "engines",\n        "dx": -0.864,\n        "dy": 0.183,\n        "r": 0.0513\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.354,\n        "dy": 0.413,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.262,\n        "dy": -0.513,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.17,\n        "dy": 0.073,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.444,\n        "dy": -0.514,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.714,\n        "dy": -0.904,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.423,\n        "dy": -0.565,\n        "r": 0.0488\n      },\n      {\n        "id": "sensors",\n        "dx": 0.083,\n        "dy": 0.108,\n        "r": 0.0488\n      },\n      {\n        "id": "navigation",\n        "dx": 0.676,\n        "dy": -0.229,\n        "r": 0.0488\n      },\n      {\n        "id": "communication",\n        "dx": -0.266,\n        "dy": -0.337,\n        "r": 0.0488\n      },\n      {\n        "id": "engines",\n        "dx": -0.655,\n        "dy": 0.085,\n        "r": 0.0488\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.463,\n        "dy": 0.088,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.611,\n        "dy": 0.382,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.208,\n        "dy": 0.371,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.671,\n        "dy": -0.221,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.778,\n        "dy": -0.305,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.459,\n        "dy": 0.184,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.95,\n        "dy": 0.134,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.499,\n        "dy": 0.238,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.469,\n        "dy": -0.13,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.426,\n        "dy": -0.361,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.139,\n        "dy": 0.77,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.616,\n        "dy": 0.507,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.073,\n        "dy": -0.569,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.402,\n        "dy": -0.844,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.801,\n        "dy": -0.368,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.19,\n        "dy": 0.764,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.1,\n        "dy": 0.5,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.862,\n        "dy": 0.481,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.081,\n        "dy": -0.533,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.904,\n        "dy": -0.042,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.084,\n        "dy": -0.06,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.156,\n        "dy": -0.504,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.616,\n        "dy": 0.033,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.788,\n        "dy": -0.912,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.804,\n        "dy": 0.124,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.165,\n        "dy": -0.018,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.342,\n        "dy": -0.659,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.806,\n        "dy": -0.917,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.716,\n        "dy": -0.92,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.685,\n        "dy": 0.149,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.462,\n        "dy": 0.422,\n        "r": 0.05\n      },\n      {\n        "id": "sensors",\n        "dx": -0.217,\n        "dy": 0.639,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.926,\n        "dy": -0.116,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.41,\n        "dy": -0.542,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.904,\n        "dy": -0.213,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.595,\n        "dy": 0.728,\n        "r": 0.05\n      },\n      {\n        "id": "sensors",\n        "dx": -0.25,\n        "dy": 0.613,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.05,\n        "dy": -0.444,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.377,\n        "dy": -0.438,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.399,\n        "dy": 0.7,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.47,\n        "dy": 0.561,\n        "r": 0.05\n      },\n      {\n        "id": "sensors",\n        "dx": 0.361,\n        "dy": 0.55,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.928,\n        "dy": -0.156,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.412,\n        "dy": -0.52,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.91,\n        "dy": -0.198,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.605,\n        "dy": 0.712,\n        "r": 0.05\n      },\n      {\n        "id": "sensors",\n        "dx": 0.25,\n        "dy": 0.613,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.05,\n        "dy": -0.444,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.377,\n        "dy": -0.438,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.402,\n        "dy": 0.721,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.672,\n        "dy": -0.752,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.606,\n        "dy": -0.106,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.744,\n        "dy": 0.232,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.177,\n        "dy": 0.427,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.932,\n        "dy": -0.53,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.562,\n        "dy": 0.081,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.258,\n        "dy": -0.274,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.416,\n        "dy": 0.111,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.148,\n        "dy": -0.332,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.816,\n        "dy": -0.301,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.191,\n        "dy": -0.57,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.269,\n        "dy": 0.604,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.066,\n        "dy": -0.825,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.405,\n        "dy": 0.212,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.645,\n        "dy": -0.364,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.186,\n        "dy": 0.316,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.079,\n        "dy": -0.668,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.812,\n        "dy": -0.045,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.128,\n        "dy": -0.678,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.362,\n        "dy": 0.265,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.132,\n        "dy": 0.933,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.07,\n        "dy": -0.219,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.708,\n        "dy": -0.197,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.262,\n        "dy": -0.793,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.809,\n        "dy": 0.016,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.632,\n        "dy": -0.311,\n        "r": 0.0435\n      },\n      {\n        "id": "sensors",\n        "dx": 0.766,\n        "dy": -0.497,\n        "r": 0.0435\n      },\n      {\n        "id": "navigation",\n        "dx": 0.567,\n        "dy": -0.636,\n        "r": 0.0435\n      },\n      {\n        "id": "communication",\n        "dx": -0.272,\n        "dy": -0.636,\n        "r": 0.0435\n      },\n      {\n        "id": "engines",\n        "dx": -0.488,\n        "dy": -0.025,\n        "r": 0.0435\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.089,\n        "dy": -0.398,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.895,\n        "dy": 0.553,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.016,\n        "dy": 0.651,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.348,\n        "dy": -0.702,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.633,\n        "dy": 0.314,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.457,\n        "dy": -0.568,\n        "r": 0.0308\n      },\n      {\n        "id": "sensors",\n        "dx": -0.938,\n        "dy": 0.441,\n        "r": 0.0308\n      },\n      {\n        "id": "navigation",\n        "dx": 0.053,\n        "dy": -0.345,\n        "r": 0.0308\n      },\n      {\n        "id": "communication",\n        "dx": -0.964,\n        "dy": -0.102,\n        "r": 0.0308\n      },\n      {\n        "id": "engines",\n        "dx": 0.374,\n        "dy": 0.834,\n        "r": 0.0308\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.484,\n        "dy": 0.629,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.498,\n        "dy": -0.462,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.856,\n        "dy": -0.308,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.895,\n        "dy": -0.628,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.234,\n        "dy": 0.4,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.883,\n        "dy": -0.27,\n        "r": 0.0571\n      },\n      {\n        "id": "sensors",\n        "dx": -0.535,\n        "dy": -0.473,\n        "r": 0.0571\n      },\n      {\n        "id": "navigation",\n        "dx": 0.169,\n        "dy": -0.552,\n        "r": 0.0571\n      },\n      {\n        "id": "communication",\n        "dx": -0.465,\n        "dy": 0.618,\n        "r": 0.0571\n      },\n      {\n        "id": "engines",\n        "dx": 0.214,\n        "dy": 0.464,\n        "r": 0.0571\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.227,\n        "dy": 0.315,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.331,\n        "dy": -0.262,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.113,\n        "dy": 0.312,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.044,\n        "dy": -0.902,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.715,\n        "dy": -0.338,\n        "r": 0.03\n      }\n    ],\n    "thrusters": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.244,\n        "dy": -0.592,\n        "r": 0.06\n      },\n      {\n        "id": "sensors",\n        "dx": -0.911,\n        "dy": -0.311,\n        "r": 0.06\n      },\n      {\n        "id": "navigation",\n        "dx": -0.481,\n        "dy": 0.181,\n        "r": 0.06\n      },\n      {\n        "id": "communication",\n        "dx": -0.833,\n        "dy": 0.033,\n        "r": 0.06\n      },\n      {\n        "id": "engines",\n        "dx": -0.064,\n        "dy": -0.395,\n        "r": 0.06\n      }\n    ],\n    "thrusters": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.108,\n        "dy": 0.34,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.328,\n        "dy": -0.323,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.229,\n        "dy": -0.268,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.052,\n        "dy": -0.733,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.903,\n        "dy": -0.363,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.246,\n        "dy": -0.694,\n        "r": 0.06\n      },\n      {\n        "id": "sensors",\n        "dx": -0.913,\n        "dy": -0.396,\n        "r": 0.06\n      },\n      {\n        "id": "navigation",\n        "dx": -0.482,\n        "dy": 0.127,\n        "r": 0.06\n      },\n      {\n        "id": "communication",\n        "dx": -0.835,\n        "dy": -0.03,\n        "r": 0.06\n      },\n      {\n        "id": "engines",\n        "dx": -0.064,\n        "dy": -0.484,\n        "r": 0.06\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.475,\n        "dy": 0.052,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.427,\n        "dy": 0.845,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.031,\n        "dy": -0.114,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.807,\n        "dy": -0.946,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.776,\n        "dy": 0.143,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.157,\n        "dy": -0.018,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.344,\n        "dy": -0.664,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.823,\n        "dy": -0.927,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.734,\n        "dy": -0.93,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.702,\n        "dy": 0.15,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.479,\n        "dy": 0.643,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.386,\n        "dy": 0.495,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.641,\n        "dy": 0.038,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.419,\n        "dy": -0.475,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.901,\n        "dy": -0.266,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.614,\n        "dy": 0.616,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": -0.25,\n        "dy": 0.578,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.05,\n        "dy": -0.401,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.377,\n        "dy": -0.396,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": 0.402,\n        "dy": 0.678,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.828,\n        "dy": -0.291,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.772,\n        "dy": 0.212,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.335,\n        "dy": 0.168,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.003,\n        "dy": -0.08,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.382,\n        "dy": -0.264,\n        "r": 0.03\n      }\n    ],\n    "docks": [\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.695,\n        "dy": 0.082,\n        "r": 0.08\n      },\n      {\n        "id": "sensors",\n        "dx": -0.092,\n        "dy": 0.016,\n        "r": 0.08\n      },\n      {\n        "id": "navigation",\n        "dx": 0.789,\n        "dy": -0.318,\n        "r": 0.08\n      },\n      {\n        "id": "communication",\n        "dx": 0.364,\n        "dy": -0.296,\n        "r": 0.08\n      },\n      {\n        "id": "engines",\n        "dx": -0.404,\n        "dy": 0.151,\n        "r": 0.08\n      }\n    ],\n    "docks": [\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.119,\n        "dy": -0.814,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.296,\n        "dy": -0.282,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.91,\n        "dy": -0.494,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.387,\n        "dy": -0.1,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.826,\n        "dy": -0.118,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.398,\n        "dy": -0.023,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.824,\n        "dy": -0.312,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.022,\n        "dy": -0.935,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.385,\n        "dy": -0.624,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.224,\n        "dy": 0.843,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.024,\n        "dy": -0.843,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.751,\n        "dy": 0.443,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.454,\n        "dy": 0.52,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.494,\n        "dy": -0.029,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.807,\n        "dy": 0.118,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": -0.108,\n        "dy": -0.848,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.853,\n        "dy": -0.087,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.28,\n        "dy": 0.191,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.457,\n        "dy": 0.083,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.726,\n        "dy": 0.236,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.225,\n        "dy": 0.276,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.467,\n        "dy": -0.429,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.166,\n        "dy": 0.09,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.333,\n        "dy": 0.049,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.667,\n        "dy": -0.243,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.505,\n        "dy": 0.442,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.937,\n        "dy": 0.27,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.862,\n        "dy": -0.169,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.512,\n        "dy": -0.394,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.029,\n        "dy": 0.078,\n        "r": 0.03\n      }\n    ],\n')
rep('hlp_mounts_final.json',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.254,\n        "dy": 0.3,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.036,\n        "dy": 0.357,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": 0.225,\n        "dy": -0.737,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": -0.317,\n        "dy": -0.736,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.798,\n        "dy": -0.28,\n        "r": 0.03\n      }\n    ],\n',
    '    "subs": [\n      {\n        "id": "weapons",\n        "dx": 0.432,\n        "dy": -0.602,\n        "r": 0.03\n      },\n      {\n        "id": "sensors",\n        "dx": 0.282,\n        "dy": -0.003,\n        "r": 0.03\n      },\n      {\n        "id": "navigation",\n        "dx": -0.259,\n        "dy": 0.511,\n        "r": 0.03\n      },\n      {\n        "id": "communication",\n        "dx": 0.406,\n        "dy": 0.42,\n        "r": 0.03\n      },\n      {\n        "id": "engines",\n        "dx": -0.712,\n        "dy": 0.219,\n        "r": 0.03\n      }\n    ],\n')

for p, t in F.items():
    open(p, "w", encoding="utf-8").write(t)
print("v188 eingespielt. Jetzt: python3 assemble.py 188")
