#!/usr/bin/env python3
"""FS3 v189 - hull floor, quiet scenery bosses, M16, slow seekers.

    Hulls       No capital ship falls below 75 % of its class value any
                more (Silvio after the M36 log). The Fenris now has 0.75
                instead of 0.27; ships above the class value are unchanged.
    Music       An invulnerable boss (the Lucifer in M69/71/72/74) is
                scenery and no longer starts the boss track. That is why a
                new piece began in nearly every mission.
    M16         The Aten keeps 1.33 of the new cruiser hull; both enemy
                groups fly with 2 ships instead of 3.
    Seekers     Trebuchet, Cyclops and Stiletto II look for a capital ship
                first and take a fighter only when none is in the cone.

Needs v188. Edits src/ in place, updates the simulations. Run assemble.py
afterwards.
"""
import base64
import os
import sys

if "FS2_CAP_HULL" not in open("src/50_combat.js", encoding="utf-8").read():
    sys.exit("Abbruch: erst v188 einspielen.")
if "CAP_HULL_MIN" in open("src/50_combat.js", encoding="utf-8").read():
    sys.exit("Abbruch: v189 ist schon eingespielt.")

F = {}
def load(p):
    if p not in F: F[p] = open(p, encoding="utf-8").read()
def rep(p, old, new, count=1):
    load(p)
    n = F[p].count(old)
    if n != count:
        sys.exit("Abbruch (%s): Suchtext %d-mal gefunden, erwartet %d.\n%s" % (p, n, count, old[:200]))
    F[p] = F[p].replace(old, new)
rep('src/12_audio.js',
    "function musicWant(){\n  if(GS === 'title') return 'title';\n  if(GS === 'gameover') return 'game_over';\n  for(const e of enemies){\n    if(e.type === 'boss' && !e.dead && !(e.warp > 0))\n      return (e.faction === 'vasudan' || e.faction === 'hol') ? 'boss_vasudan' : 'boss';\n  }\n  return 'fight';\n",
    "function musicWant(){\n  if(GS === 'title') return 'title';\n  if(GS === 'gameover') return 'game_over';\n  // An invulnerable boss is scenery (the Lucifer in M69, M71, M72, M74):\n  // no boss music for her, the fight piece plays on (v189, Silvio).\n  for(const e of enemies){\n    if(e.type === 'boss' && !e.dead && !(e.warp > 0) && !e.invuln)\n      return (e.faction === 'vasudan' || e.faction === 'hol') ? 'boss_vasudan' : 'boss';\n  }\n  return 'fight';\n")
rep('src/30_waves.js',
    "     ]},\n\n  16:{name:'The Mutiny', fac:'hol', o:'guard', live:5, u:[\n       // v188: the Aten has her FS2 hull now, half a cruiser's. She is the\n       // ship to guard here, so this one keeps the hull she had (x2).\n       {id:'A1', c:'cr', n:1, spr:'craten', side:'ally', hp:2},\n       {id:'A2', c:'fi', n:2, side:'ally'},\n       {id:'E1', c:'fi', n:3},\n       {id:'E2', c:'fi', n:3, wait:true}\n     ], ev:[\n       {t:'alleZerstoert', a:'E1', w:'meldung', a2:'escort turning hostile'},\n       {t:'alleZerstoert', a:'E1', w:'seite', a2:'A2'},\n",
    "     ]},\n\n  16:{name:'The Mutiny', fac:'hol', o:'guard', live:5, u:[\n       // v188: the Aten has her FS2 hull now. She is the ship to guard\n       // here, so this one keeps the hull she had (v189: 0.75 x 1.33).\n       {id:'A1', c:'cr', n:1, spr:'craten', side:'ally', hp:1.33},\n       {id:'A2', c:'fi', n:2, side:'ally'},\n       // v189: 3+3 -> 2+2. Since v185 the Thoth has her FS2 values and\n       // six deaths in fifty seconds was the result (Silvio).\n       {id:'E1', c:'fi', n:2},\n       {id:'E2', c:'fi', n:2, wait:true}\n     ], ev:[\n       {t:'alleZerstoert', a:'E1', w:'meldung', a2:'escort turning hostile'},\n       {t:'alleZerstoert', a:'E1', w:'seite', a2:'A2'},\n")
rep('src/50_combat.js',
    "})();\n// The factor for a sprite key: 'ntfcrfenris' and 'crfenris' are one hull,\n// 'deorionleft' and 'deorionright' are the Orion.\nfunction capHullF(img){\n  if(!img) return 1;\n  let k = img.indexOf('ntf') === 0 ? img.slice(3) : img;\n  k = k.replace(/(left|right)$/, '');\n  return CAP_HULL_F[k] || 1;\n}\n\nconst HULL = {\n",
    "})();\n// The factor for a sprite key: 'ntfcrfenris' and 'crfenris' are one hull,\n// 'deorionleft' and 'deorionright' are the Orion.\n// v189 (Silvio): never under three quarters of the class - at 0.27 a\n// Fenris went down in nine seconds.\nconst CAP_HULL_MIN = 0.75;\nfunction capHullF(img){\n  if(!img) return 1;\n  let k = img.indexOf('ntf') === 0 ? img.slice(3) : img;\n  k = k.replace(/(left|right)$/, '');\n  const f = CAP_HULL_F[k];\n  return f ? Math.max(CAP_HULL_MIN, f) : 1;\n}\n\nconst HULL = {\n")
rep('src/56_banks.js',
    "   fs:{d:20, v:1800, w:0.15, l:2.0, e:1.0, a:1.3, s:0.2, u:1.0},\n   col:'#ff6a3a', glow:'rgba(255,100,50,0.34)', note:'hull and subsystems, useless against shields'}\n];\n// Secondaries. cargo: rack space per round (SBank Capacity / cargo =\n// rounds). turn: FS2 turn time in seconds. homing: 'heat' goes for the\n// nearest, 'aspect' keeps the target it was fired at.\nconst ARSENAL_S = [\n",
    "   fs:{d:20, v:1800, w:0.15, l:2.0, e:1.0, a:1.3, s:0.2, u:1.0},\n   col:'#ff6a3a', glow:'rgba(255,100,50,0.34)', note:'hull and subsystems, useless against shields'}\n];\n// Secondaries. bigFirst (v189, Silvio): slow to turn, so the seeker goes\n// for a capital ship when there is one and only takes a fighter otherwise.\n// cargo: rack space per round (SBank Capacity / cargo =\n// rounds). turn: FS2 turn time in seconds. homing: 'heat' goes for the\n// nearest, 'aspect' keeps the target it was fired at.\nconst ARSENAL_S = [\n")
rep('src/56_banks.js',
    '   fs:{d:150, v:120, w:5.0, l:7.0, a:1.0, s:0.75, u:1.0, cargo:10, turn:1,\n       child:{d:100, v:250, l:0.3}},      // 14 x "Cluster Bomb Baby"\n   note:\'fired straight - press again to burst it into 14 small seekers\'},\n  {key:\'trebuchet\', name:\'Trebuchet\', cls:\'missile\', unlock:18000, snd:\'m_angel\', homing:\'aspect\',\n   fs:{d:350, v:280, w:6.0, l:18.0, a:0.9, s:0.5, u:2.4, cargo:8, turn:3.0},\n   note:\'long range, heavy, for subsystems\'},\n  {key:\'stiletto2\', name:\'Stiletto II\', cls:\'missile\', unlock:26000, snd:\'m_stiletto\', homing:\'heat\', subs:true,\n   fs:{d:775, v:220, w:2.0, l:25.0, a:0.01, s:0.0, u:1.0, cargo:8, turn:1.0},\n   note:\'into the subsystems, not the hull\'},\n  {key:\'tagc\', name:\'TAG-C\', cls:\'missile\', unlock:0, fromWave:67, snd:\'m_angel\', homing:\'aspect\', tag:true,\n   fs:{d:10, v:205, w:8.0, l:13.0, a:0.1, s:0.1, u:0.1, cargo:4, turn:1.75},\n   note:\'marks the target - our beams find it, even in the nebula\'},\n  {key:\'cyclops\', name:\'Cyclops\', cls:\'bomb\', unlock:0, snd:\'m_tsunami\', homing:\'aspect\',\n   fs:{d:2000, v:95, w:20.0, l:25.0, a:1.0, s:0.02, u:0.5, cargo:15, turn:1.0},\n   note:\'slow and heavy, for hulls that cannot dodge\'}\n];\n',
    '   fs:{d:150, v:120, w:5.0, l:7.0, a:1.0, s:0.75, u:1.0, cargo:10, turn:1,\n       child:{d:100, v:250, l:0.3}},      // 14 x "Cluster Bomb Baby"\n   note:\'fired straight - press again to burst it into 14 small seekers\'},\n  {key:\'trebuchet\', name:\'Trebuchet\', cls:\'missile\', unlock:18000, snd:\'m_angel\', homing:\'aspect\', bigFirst:true,\n   fs:{d:350, v:280, w:6.0, l:18.0, a:0.9, s:0.5, u:2.4, cargo:8, turn:3.0},\n   note:\'long range, heavy, for subsystems\'},\n  {key:\'stiletto2\', name:\'Stiletto II\', cls:\'missile\', unlock:26000, snd:\'m_stiletto\', homing:\'heat\', subs:true, bigFirst:true,\n   fs:{d:775, v:220, w:2.0, l:25.0, a:0.01, s:0.0, u:1.0, cargo:8, turn:1.0},\n   note:\'into the subsystems, not the hull\'},\n  {key:\'tagc\', name:\'TAG-C\', cls:\'missile\', unlock:0, fromWave:67, snd:\'m_angel\', homing:\'aspect\', tag:true,\n   fs:{d:10, v:205, w:8.0, l:13.0, a:0.1, s:0.1, u:0.1, cargo:4, turn:1.75},\n   note:\'marks the target - our beams find it, even in the nebula\'},\n  {key:\'cyclops\', name:\'Cyclops\', cls:\'bomb\', unlock:0, snd:\'m_tsunami\', homing:\'aspect\', bigFirst:true,\n   fs:{d:2000, v:95, w:20.0, l:25.0, a:1.0, s:0.02, u:0.5, cargo:15, turn:1.0},\n   note:\'slow and heavy, for hulls that cannot dodge\'}\n];\n')
rep('src/60_effects.js',
    "const CLUSTER_CHILD = {key:'cluster_child', name:'Infyrno', cls:'missile'};\n// An aspect seeker locks on at launch: the nearest lockable target ahead,\n// failing that the nearest at all. It keeps that target (v186).\nfunction aspectTarget(x, y, head){\n  let best=null, bd=Infinity, any=null, ad=Infinity;\n  for(const e of enemies){\n    if(e.dead || !canLockOn(e)) continue;\n    const d=Math.hypot(e.x-x, e.y-y);\n    if(d<ad){ ad=d; any=e; }\n    let off=Math.atan2(e.y-y, e.x-x)-head;\n",
    "const CLUSTER_CHILD = {key:'cluster_child', name:'Infyrno', cls:'missile'};\n// An aspect seeker locks on at launch: the nearest lockable target ahead,\n// failing that the nearest at all. It keeps that target (v186).\n// bigFirst: Trebuchet, Cyclops, Stiletto II look among the capital ships\n// first and take a fighter only when there is none (v189).\nfunction aspectTarget(x, y, head, bigFirst){\n  if(bigFirst){\n    const big = aspectTarget(x, y, head, false, true);\n    if(big) return big;\n  }\n  const onlyBig = arguments[4] === true;\n  let best=null, bd=Infinity, any=null, ad=Infinity;\n  for(const e of enemies){\n    if(e.dead || !canLockOn(e)) continue;\n    if(onlyBig && !isLargeShip(e)) continue;\n    const d=Math.hypot(e.x-x, e.y-y);\n    if(d<ad){ ad=d; any=e; }\n    let off=Math.atan2(e.y-y, e.x-x)-head;\n")
rep('src/60_effects.js',
    "    w:bomb?16:18, h:bomb?16:6, sec:true,\n    type:bomb?'bomb':'missile', homing:!!wp.homing, aspect:aspect, life:wp.life,\n    maxSpd:wp.spd, turn:wp.turn, f:wp.f, wd:wp,\n    target:aspect ? aspectTarget(sp.x, sp.y, sa) : null, dmg:wp.dmg, wpn:wp.key, burst:!!wp.burst});\n}\n\n// Held secondary button: the next round leaves as soon as the launcher is\n",
    "    w:bomb?16:18, h:bomb?16:6, sec:true,\n    type:bomb?'bomb':'missile', homing:!!wp.homing, aspect:aspect, life:wp.life,\n    maxSpd:wp.spd, turn:wp.turn, f:wp.f, wd:wp,\n    target:aspect ? aspectTarget(sp.x, sp.y, sa, !!wp.bigFirst) : null, dmg:wp.dmg, wpn:wp.key, burst:!!wp.burst});\n}\n\n// Held secondary button: the next round leaves as soon as the launcher is\n")
rep('src/60_effects.js',
    "        if(b.target && !b.target.dead && enemies.indexOf(b.target)>=0 && canLockOn(b.target)) nearest=b.target;\n      } else if(b.ally && b.target && !b.target.dead && enemies.indexOf(b.target)>=0){\n        nearest=b.target;               // an escort's bomb stays on its capital ship\n      } else\n      for(var j=0;j<enemies.length;j++){\n        if(!canLockOn(enemies[j])) continue;   // stealth hulls cannot be held\n        if(b.ally && playerOnly(enemies[j])) continue;\n        var d=Math.hypot(enemies[j].x-b.x,enemies[j].y-b.y);\n        if(d<minD){minD=d;nearest=enemies[j];}\n      }\n      if(nearest){\n        // On the Lucifer in subspace only a reactor counts: aim at one (v171).\n",
    "        if(b.target && !b.target.dead && enemies.indexOf(b.target)>=0 && canLockOn(b.target)) nearest=b.target;\n      } else if(b.ally && b.target && !b.target.dead && enemies.indexOf(b.target)>=0){\n        nearest=b.target;               // an escort's bomb stays on its capital ship\n      } else {\n      // A heat seeker that is slow to turn (Stiletto II) takes the nearest\n      // capital ship when there is one (v189).\n      var bigOnly = !!(b.wd && b.wd.bigFirst && !b.ally);\n      for(var pass=0; pass<2 && !nearest; pass++){\n        for(var j=0;j<enemies.length;j++){\n          if(!canLockOn(enemies[j])) continue;   // stealth hulls cannot be held\n          if(b.ally && playerOnly(enemies[j])) continue;\n          if(pass===0 && bigOnly && !isLargeShip(enemies[j])) continue;\n          var d=Math.hypot(enemies[j].x-b.x,enemies[j].y-b.y);\n          if(d<minD){minD=d;nearest=enemies[j];}\n        }\n        if(!bigOnly) break;\n      }\n      }\n      if(nearest){\n        // On the Lucifer in subspace only a reactor counts: aim at one (v171).\n")
rep('wpnsim.js',
    '// written down per ship so the test can ask who was struck.\nvar LOCK_OK = true, HITS = [];\nfunction canLockOn(o){ return LOCK_OK && !!o; }\nfunction eBox(e){ return [e.x-15, e.y-15, 30, 30]; }\nfunction overlap(ax,ay,aw,ah,bx,by,bw,bh){ return ax<bx+bw && ax+aw>bx && ay<by+bh && ay+ah>by; }\nfunction bulletOnHull(){ return true; }\n',
    "// written down per ship so the test can ask who was struck.\nvar LOCK_OK = true, HITS = [];\nfunction canLockOn(o){ return LOCK_OK && !!o; }\nfunction isLargeShip(o){ return o.type==='cruiser' || o.type==='corvette' || o.type==='destroyer'; }\nfunction eBox(e){ return [e.x-15, e.y-15, 30, 30]; }\nfunction overlap(ax,ay,aw,ah,bx,by,bw,bh){ return ax<bx+bw && ax+aw>bx && ay<by+bh && ay+ah>by; }\nfunction bulletOnHull(){ return true; }\n")
rep('wpnsim.js',
    "  run('enemies.length=0'); clear();\n}\n\nconsole.log('\\nv187: Lamprey, Hornet, Piranha, Helios are out');\n{\n  const gone = ['lamprey','hornet','piranha','helios'];\n",
    "  run('enemies.length=0'); clear();\n}\n\nconsole.log('\\nv189: slow seekers go for a capital ship first');\n{\n  const fi = {x:220, y:250, hp:1e6, dead:false, type:'fighter'}, cr = {x:600, y:250, hp:1e6, dead:false, type:'cruiser'};\n  run('enemies.length=0'); run('enemies').push(fi, cr);\n  fitShip('fitoth', ['promr'], ['trebuchet']); run('player.x=100; player.y=250; player.head=0; player.secTimer=0; fireSecondary()');\n  ok('a Trebuchet locks the cruiser, not the nearer fighter', bullets().find(x=>x.sec).target === cr);\n  clear(); fitShip('fitoth', ['promr'], ['harpoon']); run('player.secTimer=0; fireSecondary()');\n  ok('a Harpoon still takes the nearer fighter', bullets().find(x=>x.sec).target === fi);\n  clear(); fitShip('boosiris', ['mekhu'], ['stiletto2']); run('player.secTimer=0; fireSecondary()');\n  const st = bullets().find(x=>x.sec), vy0 = st.vy;\n  cr.y = 150; run('updateSecBullets()');\n  ok('a Stiletto II steers for the cruiser (up), not the fighter ahead', st.vy < vy0);\n  run('enemies.length=0'); run('enemies').push(fi);\n  clear(); fitShip('fitoth', ['promr'], ['trebuchet']); run('player.secTimer=0; fireSecondary()');\n  ok('with no capital ship about, the Trebuchet takes the fighter', bullets().find(x=>x.sec).target === fi);\n  run('enemies.length=0'); clear();\n}\n\nconsole.log('\\nv187: Lamprey, Hornet, Piranha, Helios are out');\n{\n  const gone = ['lamprey','hornet','piranha','helios'];\n")
rep('fieldsim.js',
    "  const r = {};\n  const mk = (t, spr) => { const e = mkEnemy(t, spr, 250); return e; };\n  const fen = mk('cr_ntf', 'ntfcrfenris'), lil = mk('cr_sh', 'crlilith'), aeo = mk('cr_ntf', 'ntfcraeolus');\n  // ships.tbl: Lilith 75000, Fenris 10000 - the same ratio here\n  r.fenrisQuarterOfLilith = Math.abs(fen.maxHp/lil.maxHp - 10000/75000) < 0.01;\n  // the class keeps its average: the eight cruisers average the old value\n  const names = ['craeolus','craten','crcain','crfenris','crleviathan','crlilith','crmentu','crrakshasa'];\n  const avg = names.reduce((s,n)=>s+capHullF(n),0)/names.length;\n  r.classAverageKept = Math.abs(avg-1) < 1e-9;\n  r.ntfSameAsTerran = capHullF('ntfcrfenris') === capHullF('crfenris') && capHullF('deorionleft') === capHullF('deorionright');\n  r.othersUntouched = capHullF('casetekh')===1 && capHullF('coiceni')===1 && capHullF('sdcolossus')===1 && capHullF('sgmjolnir')===1;\n  // the escort has the hull the support menu shows\n",
    "  const r = {};\n  const mk = (t, spr) => { const e = mkEnemy(t, spr, 250); return e; };\n  const fen = mk('cr_ntf', 'ntfcrfenris'), lil = mk('cr_sh', 'crlilith'), aeo = mk('cr_ntf', 'ntfcraeolus');\n  // ships.tbl ratio, but never under three quarters of the class (v189)\n  r.fenrisFloor = Math.abs(fen.maxHp/lil.maxHp - 0.75/(75000/37000)) < 0.01 && capHullF('crfenris') === 0.75;\n  r.lilithFull = Math.abs(capHullF('crlilith') - 75000/37000) < 1e-9;\n  // an invulnerable boss is scenery: no boss music for her (v189)\n  const fakeBoss = {type:'boss', invuln:true, dead:false, faction:'shivan'};\n  enemies.push(fakeBoss); r.sceneryBossNoMusic = musicWant() === 'fight';\n  fakeBoss.invuln = false; r.realBossMusic = musicWant() === 'boss';\n  enemies.splice(enemies.indexOf(fakeBoss), 1);\n  r.ntfSameAsTerran = capHullF('ntfcrfenris') === capHullF('crfenris') && capHullF('deorionleft') === capHullF('deorionright');\n  r.othersUntouched = capHullF('casetekh')===1 && capHullF('coiceni')===1 && capHullF('sdcolossus')===1 && capHullF('sgmjolnir')===1;\n  // the escort has the hull the support menu shows\n")

for p, t in F.items():
    open(p, "w", encoding="utf-8").write(t)
print("v189 eingespielt. Jetzt: python3 assemble.py 189")
