#!/usr/bin/env python3
"""FS3 v193 - smooth 3D previews, the Colossus is a juggernaut.

    3D view    The model is no longer copied into the 2D picture every
               frame; it sits as its own layer right over the picture,
               which the graphics card shows directly. The turn speeds up
               and slows down softly, the wheel zoom glides to its target
               instead of jumping (Silvio: turning and zoom were jerky).
    Colossus   Support card and list row call her JUGGERNAUT, not
               DESTROYER (Silvio).

Needs v192. Edits src/58_model3d.js and src/70_ui.js. Run assemble.py
afterwards.
"""
import base64
import os
import sys

if "drawInfoCard" not in open("src/70_ui.js", encoding="utf-8").read():
    sys.exit("Abbruch: erst v192 einspielen.")
if "m3dEndFrame" in open("src/58_model3d.js", encoding="utf-8").read():
    sys.exit("Abbruch: v193 ist schon eingespielt.")

F = {}
def load(p):
    if p not in F: F[p] = open(p, encoding="utf-8").read()
def rep(p, old, new, count=1):
    load(p)
    n = F[p].count(old)
    if n != count:
        sys.exit("Abbruch (%s): Suchtext %d-mal gefunden, erwartet %d.\n%s" % (p, n, count, old[:200]))
    F[p] = F[p].replace(old, new)
rep('src/58_model3d.js',
    "  try{\n    if(typeof document === 'undefined' || !document.createElement) return false;\n    const can = document.createElement('canvas');\n    const gl = can.getContext('webgl', {alpha:true, premultipliedAlpha:true, antialias:true, preserveDrawingBuffer:true});\n    if(!gl) return false;\n    M3D.deriv = !!gl.getExtension('OES_standard_derivatives');\n    gl.getExtension('OES_element_index_uint');\n",
    "  try{\n    if(typeof document === 'undefined' || !document.createElement) return false;\n    const can = document.createElement('canvas');\n    // v193 (Silvio: turning and zoom looked jerky): the model canvas sits as\n    // its own layer over the game canvas, so the browser composites it on\n    // the GPU instead of the page copying every frame back into the 2D\n    // picture. Pointer events go through it to the game below.\n    const ov = !!(document.body && document.body.appendChild);\n    if(ov){\n      const st = can.style;\n      st.position = 'fixed'; st.pointerEvents = 'none'; st.zIndex = '5'; st.display = 'none';\n      st.left = '0px'; st.top = '0px';\n      document.body.appendChild(can);\n    }\n    M3D.overlay = ov;\n    const gl = can.getContext('webgl', {alpha:true, premultipliedAlpha:true, antialias:true, preserveDrawingBuffer:!ov});\n    if(!gl) return false;\n    M3D.deriv = !!gl.getExtension('OES_standard_derivatives');\n    gl.getExtension('OES_element_index_uint');\n")
rep('src/58_model3d.js',
    "  if(!key || !m3dInit()) return false;\n  const m = m3dModel(key);\n  o = o || {};\n  if((o.zoom||1) >= M3D_ZOOM_HI && !m.hi) m.hi = m3dLevel(key, 'hi', 1024);\n  const L = (m.hi && m.hi.state === 'ready') ? m.hi : m.lo;\n  if(L.state !== 'ready') return false;\n  const gl = M3D.gl, can = M3D.can, loc = M3D.loc;\n  const k = (typeof CVS !== 'undefined' && CVS.width) ? CVS.width / W : 1;\n  const pw = Math.max(1, Math.round(w*k)), ph = Math.max(1, Math.round(h*k));\n  if(can.width !== pw || can.height !== ph){ can.width = pw; can.height = ph; }\n  gl.viewport(0, 0, pw, ph);\n  gl.clearColor(0, 0, 0, 0); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);\n",
    "  if(!key || !m3dInit()) return false;\n  const m = m3dModel(key);\n  o = o || {};\n  if(Math.max(o.zoom||1, M3D_VIEW.zoomT||1) >= M3D_ZOOM_HI && !m.hi) m.hi = m3dLevel(key, 'hi', 1024);\n  const L = (m.hi && m.hi.state === 'ready') ? m.hi : m.lo;\n  if(L.state !== 'ready') return false;\n  const gl = M3D.gl, can = M3D.can, loc = M3D.loc;\n  let pw, ph;\n  if(M3D.overlay && typeof CVS !== 'undefined' && CVS.getBoundingClientRect){\n    // place the layer over the box, in CSS pixels, sharp on a HiDPI screen\n    const r = CVS.getBoundingClientRect(), sx = r.width / W, sy = r.height / H;\n    const dpr = (typeof window !== 'undefined' && window.devicePixelRatio) || 1;\n    const cl = Math.round(r.left + x*sx), ct = Math.round(r.top + y*sy);\n    const cw = Math.max(1, Math.round(w*sx)), ch = Math.max(1, Math.round(h*sy));\n    const st = can.style, box = cl+','+ct+','+cw+','+ch;\n    if(M3D.box !== box){ M3D.box = box; st.left = cl+'px'; st.top = ct+'px'; st.width = cw+'px'; st.height = ch+'px'; }\n    pw = Math.max(1, Math.round(cw*dpr)); ph = Math.max(1, Math.round(ch*dpr));\n    if(st.display === 'none') st.display = 'block';\n    M3D.used = true;\n  } else {\n    const k = (typeof CVS !== 'undefined' && CVS.width) ? CVS.width / W : 1;\n    pw = Math.max(1, Math.round(w*k)); ph = Math.max(1, Math.round(h*k));\n  }\n  if(can.width !== pw || can.height !== ph){ can.width = pw; can.height = ph; }\n  gl.viewport(0, 0, pw, ph);\n  gl.clearColor(0, 0, 0, 0); gl.clear(gl.COLOR_BUFFER_BIT | gl.DEPTH_BUFFER_BIT);\n")
rep('src/58_model3d.js',
    "    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, p.idx);\n    gl.drawElements(gl.TRIANGLES, p.n, p.big ? gl.UNSIGNED_INT : gl.UNSIGNED_SHORT, 0);\n  }\n  ctx.drawImage(can, x, y, w, h);\n  return true;\n}\n// The picture's own state: turning while the pointer is on it, zoom from\n// the wheel, easing back to rest when the pointer leaves.\nconst M3D_VIEW = {yaw:M3D_YAW0, zoom:1, t:0, key:null};\nfunction m3dView(key, hot){\n  const now = (typeof performance !== 'undefined') ? performance.now() : Date.now();\n  const dt = M3D_VIEW.t ? Math.min(0.1, (now - M3D_VIEW.t)/1000) : 0;\n  M3D_VIEW.t = now;\n  if(M3D_VIEW.key !== key){ M3D_VIEW.key = key; M3D_VIEW.yaw = M3D_YAW0; M3D_VIEW.zoom = 1; }\n  if(hot) M3D_VIEW.yaw += M3D_SPIN*dt;\n  else {\n    // back to rest the short way round\n    let d = (M3D_YAW0 - M3D_VIEW.yaw) % (Math.PI*2);\n    if(d > Math.PI) d -= Math.PI*2; if(d < -Math.PI) d += Math.PI*2;\n    M3D_VIEW.yaw += d*Math.min(1, dt*4);\n    M3D_VIEW.zoom += (1 - M3D_VIEW.zoom)*Math.min(1, dt*3);\n  }\n  return {yaw:M3D_VIEW.yaw, zoom:M3D_VIEW.zoom};\n}\nfunction m3dWheel(dy){\n  M3D_VIEW.zoom = Math.max(1, Math.min(M3D_ZOOM_MAX, M3D_VIEW.zoom*(dy < 0 ? 1.15 : 1/1.15)));\n}\n",
    "    gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER, p.idx);\n    gl.drawElements(gl.TRIANGLES, p.n, p.big ? gl.UNSIGNED_INT : gl.UNSIGNED_SHORT, 0);\n  }\n  if(!M3D.overlay) ctx.drawImage(can, x, y, w, h);\n  return true;\n}\n// Called once per frame after everything is drawn: a model that was not\n// drawn this frame (its window closed) takes its layer away.\nfunction m3dEndFrame(){\n  if(!M3D.overlay || !M3D.can) return;\n  if(!M3D.used && M3D.can.style.display !== 'none') M3D.can.style.display = 'none';\n  M3D.used = false;\n}\n// The picture's own state: turning while the pointer is on it, zoom from\n// the wheel, easing back to rest when the pointer leaves.\n// v193: the turn speeds up and slows down instead of starting and\n// stopping dead, and the wheel sets a target the zoom glides to.\nconst M3D_VIEW = {yaw:M3D_YAW0, zoom:1, zoomT:1, spin:0, t:0, key:null};\nconst M3D_EASE_SPIN = 3.0, M3D_EASE_ZOOM = 9.0, M3D_EASE_REST = 3.0;\nfunction m3dView(key, hot){\n  const now = (typeof performance !== 'undefined') ? performance.now() : Date.now();\n  const dt = M3D_VIEW.t ? Math.min(0.05, (now - M3D_VIEW.t)/1000) : 0;\n  M3D_VIEW.t = now;\n  if(M3D_VIEW.key !== key){ M3D_VIEW.key = key; M3D_VIEW.yaw = M3D_YAW0; M3D_VIEW.zoom = M3D_VIEW.zoomT = 1; M3D_VIEW.spin = 0; }\n  const ease = function(rate){ return 1 - Math.exp(-rate*dt); };\n  M3D_VIEW.spin += ((hot ? M3D_SPIN : 0) - M3D_VIEW.spin)*ease(M3D_EASE_SPIN);\n  M3D_VIEW.yaw += M3D_VIEW.spin*dt;\n  if(!hot){\n    M3D_VIEW.zoomT = 1;\n    // back to rest the short way round, once the turn has run out\n    if(M3D_VIEW.spin < 0.05){\n      let d = (M3D_YAW0 - M3D_VIEW.yaw) % (Math.PI*2);\n      if(d > Math.PI) d -= Math.PI*2; if(d < -Math.PI) d += Math.PI*2;\n      M3D_VIEW.yaw += d*ease(M3D_EASE_REST);\n    }\n  }\n  M3D_VIEW.zoom += (M3D_VIEW.zoomT - M3D_VIEW.zoom)*ease(M3D_EASE_ZOOM);\n  return {yaw:M3D_VIEW.yaw, zoom:M3D_VIEW.zoom};\n}\nfunction m3dWheel(dy){\n  M3D_VIEW.zoomT = Math.max(1, Math.min(M3D_ZOOM_MAX, M3D_VIEW.zoomT*(dy < 0 ? 1.12 : 1/1.12)));\n}\n")
rep('src/70_ui.js',
    "  const d = ALLY_DEFS[id], m = (typeof mountsFor === 'function' && mountsFor(d.spr)) || {};\n  const beams = m.beams || [], heavy = beams.filter(function(b){ return b.large; }).length, light = beams.length - heavy;\n  const guns = (m.primary||[]).length, mis = (m.secondary||[]).length;\n  const facts = [d.cls.toUpperCase(), 'HULL '+allyHull(d)];\n  if(light) facts.push(light+' ANTI-FIGHTER '+(light === 1 ? 'BEAM' : 'BEAMS'));\n  facts.push(heavy ? heavy+' HEAVY '+(heavy === 1 ? 'BEAM' : 'BEAMS') : 'NO HEAVY BEAMS');\n  if(guns) facts.push(guns+(guns === 1 ? ' TURRET' : ' TURRETS'));\n",
    "  const d = ALLY_DEFS[id], m = (typeof mountsFor === 'function' && mountsFor(d.spr)) || {};\n  const beams = m.beams || [], heavy = beams.filter(function(b){ return b.large; }).length, light = beams.length - heavy;\n  const guns = (m.primary||[]).length, mis = (m.secondary||[]).length;\n  // The Colossus fights as a destroyer, but she is a juggernaut (Silvio).\n  const facts = [d.colossus ? 'JUGGERNAUT' : d.cls.toUpperCase(), 'HULL '+allyHull(d)];\n  if(light) facts.push(light+' ANTI-FIGHTER '+(light === 1 ? 'BEAM' : 'BEAMS'));\n  facts.push(heavy ? heavy+' HEAVY '+(heavy === 1 ? 'BEAM' : 'BEAMS') : 'NO HEAVY BEAMS');\n  if(guns) facts.push(guns+(guns === 1 ? ' TURRET' : ' TURRETS'));\n")
rep('src/70_ui.js',
    "  ctx.fillText(thFit(allyLabel(d), textW), x+nameX, y+13);\n\n  let sub;\n  if(d.colossus)                sub = COLOSSUS_TIME+' s on station, then she jumps out';\n  // The hull the ship will really have (v188: FS2 ratio within the class).\n  else if(d.cls==='destroyer')  sub = 'DESTROYER  -  HULL '+allyHull(d)+'  -  WINGS';\n  else                          sub = d.cls.toUpperCase()+'  -  HULL '+allyHull(d);\n",
    "  ctx.fillText(thFit(allyLabel(d), textW), x+nameX, y+13);\n\n  let sub;\n  if(d.colossus)                sub = 'JUGGERNAUT  -  '+COLOSSUS_TIME+' S ON STATION';\n  // The hull the ship will really have (v188: FS2 ratio within the class).\n  else if(d.cls==='destroyer')  sub = 'DESTROYER  -  HULL '+allyHull(d)+'  -  WINGS';\n  else                          sub = d.cls.toUpperCase()+'  -  HULL '+allyHull(d);\n")
rep('src/70_ui.js',
    '  try{drawCallMenu();}catch(e){}\n  try{drawShipMenu();}catch(e){}\n  try{drawRearmMenu();}catch(e){}\n  try{drawResumeHint();}catch(e){}\n  try{drawCtxNotice();}catch(e){}\n})();\n',
    "  try{drawCallMenu();}catch(e){}\n  try{drawShipMenu();}catch(e){}\n  try{drawRearmMenu();}catch(e){}\n  try{ if(typeof m3dEndFrame === 'function') m3dEndFrame(); }catch(e){}\n  try{drawResumeHint();}catch(e){}\n  try{drawCtxNotice();}catch(e){}\n})();\n")

for p, t in F.items():
    open(p, "w", encoding="utf-8").write(t)
print("v193 eingespielt. Jetzt: python3 assemble.py 193")
